// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#include <vector>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

// --- nyx Standard Core Helpers ---
template<typename T> int64_t len(const T& c) { return (int64_t)c.size(); }
template<typename T> int64_t length(const T& c) { return (int64_t)c.size(); }
template<typename T, typename V> void push(vector<T>& v, const V& val) { v.push_back(val); }
template<typename T> auto& _nyx_at(vector<T>& v, int64_t i) { return v[i]; }
template<typename T> const auto& _nyx_at(const vector<T>& v, int64_t i) { return v[i]; }
inline string _nyx_at(const string& s, int64_t i) { if (i < 0 || (size_t)i >= s.size()) return ""; return string(1, s[i]); }
template<typename F> struct _NyxScopeExit { F f; ~_NyxScopeExit() { f(); } };
template<typename F> _NyxScopeExit<F> _nyx_make_scope_exit(F f) { return {f}; }

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    auto a = vector{10, 20};
    auto b = vector{a, vector{30, 40}};
    cout << _nyx_at(_nyx_at(b, 0), 0) << endl;
    return 0;
}