// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

// --- nyx Standard Core Helpers ---
template<typename F> struct _NyxScopeExit { F f; ~_NyxScopeExit() { f(); } };
template<typename F> _NyxScopeExit<F> _nyx_make_scope_exit(F f) { return {f}; }

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    auto n = nullptr;
    cout << (n == nullptr) << endl;
    return 0;
}