// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

auto f1(auto x) {
    return (f2(x) + 1);
}

auto f2(auto x) {
    return (f3(x) * 2);
}

auto f3(auto x) {
    return (x + 10);
}

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    cout << f1(5) << endl;
    return 0;
}