// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

int64_t add_typed(int64_t a, int64_t b);

int64_t add_typed(int64_t a, int64_t b) {
    return (a + b);
}

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    cout << add_typed(20, 30) << endl;
    return 0;
}