// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    auto count = 0;
    for (int64_t i = 1; i <= (int64_t)(3); i++) {
        for (int64_t j = 1; j <= (int64_t)(2); j++) {
            count = (count + 1);
        }
    }
    cout << count << endl;
    return 0;
}