// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    auto a = 0;
    auto b = 10;
    while (((a < 5) && (b > 5))) {
        a = (a + 1);
        b = (b - 1);
    }
    cout << a << " " << b << endl;
    return 0;
}