// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    auto s = 0;
    for (int64_t i = 1; i <= (int64_t)(4); i++) {
        s = (s + i);
    }
    cout << s << endl;
    return 0;
}