// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    auto c = 3;
    while ((c > 0)) {
        cout << c << endl;
        c = (c - 1);
    }
    return 0;
}