// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    auto step = 0;
    while (true) {
        step = (step + 1);
        if ((step == 4)) {
            break;
        }
    }
    cout << step << endl;
    return 0;
}