// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    optional<User> x = nullptr;
    if ((x == nullptr)) {
        cout << string("Is Null") << endl;
    } else {
        cout << string("Not Null") << endl;
    }
    return 0;
}