// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

struct Box {
    string val;
    Box() : val() {}
    Box(string val) : val(val) {}

};

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    optional<Box> b = Box(50);
    cout << ((b.val.value_or(0)) + 10) << endl;
    return 0;
}