// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

struct User {
    string name;
    User() : name() {}
    User(string name) : name(name) {}

};

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    auto u = User(string("Ali"));
    cout << (u.name.value_or(string("None"))) << endl;
    return 0;
}