// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

// --- nyx Standard Core Helpers ---
template<typename F> struct _NyxScopeExit { F f; ~_NyxScopeExit() { f(); } };
template<typename F> _NyxScopeExit<F> _nyx_make_scope_exit(F f) { return {f}; }

auto ack(auto m, auto n) {
    if ((m == 0)) {
        return (n + 1);
    }
    if (((m > 0) && (n == 0))) {
        return ack((m - 1), 1);
    }
    return ack((m - 1), ack(m, (n - 1)));
}

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    cout << ack(2, 2) << endl;
    return 0;
}