// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

auto fib(auto n) {
    if ((n <= 0)) {
        return 0;
    }
    if ((n == 1)) {
        return 1;
    }
    return (fib((n - 1)) + fib((n - 2)));
}

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    cout << fib(7) << endl;
    return 0;
}