// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

auto power(auto b, auto e) {
    if ((e == 0)) {
        return 1;
    }
    return (b * power(b, (e - 1)));
}

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    cout << power(2, 8) << endl;
    return 0;
}