// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    auto n = 10;
    auto _match_val = n;
    if (_match_val == 10) {
        cout << (n * 5) << endl;
    }
    if (_match_val == string("_")) {
        cout << 0 << endl;
    }
    return 0;
}