// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    auto code = 2;
    auto _match_val = code;
    if (_match_val == 1) {
        cout << string("ONE") << endl;
    }
    if (_match_val == 2) {
        cout << string("TWO") << endl;
    }
    if (_match_val == string("_")) {
        cout << string("MANY") << endl;
    }
    return 0;
}