// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    auto role = string("admin");
    auto _match_val = role;
    if (_match_val == string("admin")) {
        cout << string("FULL ACCESS") << endl;
    }
    if (_match_val == string("user")) {
        cout << string("READ ONLY") << endl;
    }
    if (_match_val == string("_")) {
        cout << string("DENY") << endl;
    }
    return 0;
}