// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

// --- nyx Standard Core Helpers ---
template<typename T, typename E = string>
struct Result { bool is_ok; T value; E error; Result() : is_ok(false), value(), error() {} Result(bool ok, T val, E err) : is_ok(ok), value(val), error(err) {} template<typename U> Result(const Result<U, E>& o) : is_ok(o.is_ok), value((T)o.value), error(o.error) {} T unwrap() const { return value; } };
template<typename T> Result<T, string> Ok(T val) { return Result<T, string>(true, val, ""); }
template<typename T = int64_t> Result<T, string> Err(string err) { return Result<T, string>(false, T{}, err); }

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    auto r = Ok(200);
    auto _match_val = r;
    if (_match_val.is_ok == true) {
        auto v = _match_val.value;
        cout << string("OK:") << " " << v << endl;
    }
    if (_match_val.is_ok == false) {
        auto e = _match_val.error;
        cout << string("ERR") << endl;
    }
    if (_match_val == string("_")) {
        cout << string("OTHER") << endl;
    }
    return 0;
}