// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

// --- nyx Standard Core Helpers ---
template<typename F> struct _NyxScopeExit { F f; ~_NyxScopeExit() { f(); } };
template<typename F> _NyxScopeExit<F> _nyx_make_scope_exit(F f) { return {f}; }

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    auto status = string("ready");
    auto _match_val = status;
    if (_match_val == string("ready")) {
        // --- BEGIN UNSAFE BLOCK ---
        cout << string("SYSTEM READY") << endl;
        cout << string("ONLINE") << endl;
        // --- END UNSAFE BLOCK ---
    }
    if (_match_val == string("_")) {
        cout << string("OFFLINE") << endl;
    }
    return 0;
}