// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

auto check_status(auto s) {
    auto _match_val = s;
    if (_match_val == string("ok")) {
        return 1;
    }
    if (_match_val == string("_")) {
        return 0;
    }
}

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    cout << check_status(string("ok")) << endl;
    return 0;
}