// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

// --- nyx Standard Core Helpers ---
int to_int(const string& s) { try { return stoi(s); } catch(...) { return 0; } }

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    cout << (to_int(string("42")) + 8) << endl;
    return 0;
}