// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

// --- nyx Standard Core Helpers ---
inline string to_string(const string& s) { return s; }
inline string to_string(const char* s) { return string(s); }
inline string to_string(bool b) { return b ? "true" : "false"; }
string to_string_val(int v) { return to_string(v); }
template<typename F> struct _NyxScopeExit { F f; ~_NyxScopeExit() { f(); } };
template<typename F> _NyxScopeExit<F> _nyx_make_scope_exit(F f) { return {f}; }

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    cout << (string("Num: ") + to_string(123)) << endl;
    return 0;
}