// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

// --- nyx Standard Core Helpers ---
bool contains(const string& s, const string& sub) { return s.find(sub) != string::npos; }

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    cout << contains(string("radar_scan"), string("target")) << endl;
    return 0;
}