// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

struct Point {
    string x;
    string y;
    Point() : x(), y() {}
    Point(string x, string y) : x(x), y(y) {}

};

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    auto p = Point(10, 20);
    cout << p.x << " " << p.y << endl;
    return 0;
}