// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

struct A {
    string val;
    A() : val() {}
    A(string val) : val(val) {}

};

struct B {
    string a;
    B() : a() {}
    B(string a) : a(a) {}

};

struct C {
    string b;
    C() : b() {}
    C(string b) : b(b) {}

};

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    auto c = C(B(A(777)));
    cout << c.b.a.val << endl;
    return 0;
}