// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#include <vector>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

// --- nyx Standard Core Helpers ---
template<typename T> int64_t len(const T& c) { return (int64_t)c.size(); }
template<typename T> int64_t length(const T& c) { return (int64_t)c.size(); }
template<typename T, typename V> void push(vector<T>& v, const V& val) { v.push_back(val); }
template<typename T> auto& _nyx_at(vector<T>& v, int64_t i) { return v[i]; }
template<typename T> const auto& _nyx_at(const vector<T>& v, int64_t i) { return v[i]; }
inline string _nyx_at(const string& s, int64_t i) { if (i < 0 || (size_t)i >= s.size()) return ""; return string(1, s[i]); }
template<typename F> struct _NyxScopeExit { F f; ~_NyxScopeExit() { f(); } };
template<typename F> _NyxScopeExit<F> _nyx_make_scope_exit(F f) { return {f}; }

struct Item {
    int64_t id;
    Item() : id() {}
    Item(int64_t id) : id(id) {}

};

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    auto items = vector{Item(1), Item(2)};
    cout << _nyx_at(items, 1).id << endl;
    return 0;
}