// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

struct Pair {
    string a;
    string b;
    Pair() : a(), b() {}
    Pair(string a, string b) : a(a), b(b) {}

};

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    auto p1 = Pair(1, 2);
    auto p2 = p1;
    cout << p2.a << " " << p2.b << endl;
    return 0;
}