// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

struct Address {
    string city;
    Address() : city() {}
    Address(string city) : city(city) {}

};

struct User {
    string name;
    string addr;
    User() : name(), addr() {}
    User(string name, string addr) : name(name), addr(addr) {}

};

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    auto u = User(string("Umut"), Address(string("Istanbul")));
    cout << u.name << " " << u.addr.city << endl;
    return 0;
}