// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#include <cstdint>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

// --- nyx Standard Core Helpers ---
uintptr_t addr(void* ptr) { return (uintptr_t)ptr; }
template<typename T> uintptr_t addr(T& val) { return (uintptr_t)&val; }
uintptr_t peek(uintptr_t a) { return *(uintptr_t*)a; }
template<typename F> struct _NyxScopeExit { F f; ~_NyxScopeExit() { f(); } };
template<typename F> _NyxScopeExit<F> _nyx_make_scope_exit(F f) { return {f}; }

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    // --- BEGIN UNSAFE BLOCK ---
    auto x = 42;
    auto p = addr(x);
    cout << peek(p) << endl;
    // --- END UNSAFE BLOCK ---
    return 0;
}