// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#include <iomanip>
#include <cstdint>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

// --- nyx Standard Core Helpers ---
uintptr_t addr(void* ptr) { return (uintptr_t)ptr; }
template<typename T> uintptr_t addr(T& val) { return (uintptr_t)&val; }
void memdump(uintptr_t a, size_t len) {
    uint8_t* p = (uint8_t*)a;
    for (size_t i = 0; i < len; i += 16) {
        cout << "0x" << hex << uppercase << setw(16) << setfill('0') << (a + i) << ": ";
        for (size_t j = 0; j < 16; j++) { if (i+j < len) cout << hex << setw(2) << setfill('0') << (int)p[i+j] << " "; else cout << "   "; }
        cout << " | ";
        for (size_t j = 0; j < 16 && (i+j) < len; j++) cout << (isprint(p[i+j]) ? (char)p[i+j] : '.');
        cout << dec << endl;
    }
}

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    // --- BEGIN UNSAFE BLOCK ---
    auto x = 10;
    memdump(addr(x), 16);
    // --- END UNSAFE BLOCK ---
    cout << string("Memdump OK") << endl;
    return 0;
}