// Auto-generated by nyx Systems Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#include <thread>
#include <chrono>
#ifdef _WIN32
#include <windows.h>
#endif
using namespace std;

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    cout << boolalpha;
    thread([=]() {
        auto bg = 1;
    }).detach();
    cout << string("Spawn OK") << endl;
    return 0;
}