import os
import hashlib
from typing import Dict, Any, Optional

class Manifest:
    def __init__(
        self,
        name: str = "my_project",
        version: str = "0.1.0",
        edition: str = "2026",
        compiler_version: str = "4.0.0",
        target: str = "hecpp",
        entry: str = "src/main.he",
        opt_level: int = 2,
        debug: bool = False,
        dependencies: Optional[Dict[str, str]] = None
    ):
        self.name = name
        self.version = version
        self.edition = edition
        self.compiler_version = compiler_version
        self.target = target
        self.entry = entry
        self.opt_level = opt_level
        self.debug = debug
        self.dependencies = dependencies or {}

    @classmethod
    def load(cls, path: str = "he.toml") -> "Manifest":
        if not os.path.exists(path):
            return cls()
            
        m = cls()
        current_section = ""
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                raw_line = line.strip()
                if not raw_line or raw_line.startswith("#"):
                    continue
                if raw_line.startswith("[") and raw_line.endswith("]"):
                    current_section = raw_line[1:-1].strip().lower()
                    continue
                    
                if "=" in raw_line:
                    k, v = raw_line.split("=", 1)
                    key = k.strip()
                    val = v.strip().strip('"').strip("'")
                    
                    if current_section in ("package", ""):
                        if key == "name": m.name = val
                        elif key == "version": m.version = val
                        elif key == "edition": m.edition = val
                        elif key == "compiler_version": m.compiler_version = val
                        elif key in ("target", "default"): m.target = val
                        elif key == "entry": m.entry = val
                    elif current_section == "build":
                        if key == "opt_level":
                            try: m.opt_level = int(val)
                            except: pass
                        elif key == "debug":
                            m.debug = val.lower() in ("true", "1")
                    elif current_section == "dependencies":
                        m.dependencies[key] = val
        return m

    def save(self, path: str = "he.toml"):
        lines = [
            "# HolyEasyLang Package Manifest",
            "[package]",
            f'name = "{self.name}"',
            f'version = "{self.version}"',
            f'edition = "{self.edition}"',
            f'compiler_version = "{self.compiler_version}"',
            f'target = "{self.target}"',
            f'entry = "{self.entry}"',
            "",
            "[build]",
            f"opt_level = {self.opt_level}",
            f"debug = {'true' if self.debug else 'false'}",
            "",
            "[dependencies]"
        ]
        for k, v in self.dependencies.items():
            lines.append(f'{k} = "{v}"')
        lines.append("")
        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

    def write_lockfile(self, lock_path: str = "he.lock"):
        lines = [
            "# Auto-generated by HolyEasyLang Toolchain (Do Not Edit Manually)",
            "# Lockfile Version: 1",
            f'root_package = "{self.name}"',
            f'root_version = "{self.version}"',
            f'compiler = "{self.compiler_version}"',
            ""
        ]
        for pkg, ver in sorted(self.dependencies.items()):
            # Deterministic SHA256 checksum for dependency resolution
            h = hashlib.sha256(f"{pkg}:{ver}".encode("utf-8")).hexdigest()
            lines.append("[[package]]")
            lines.append(f'name = "{pkg}"')
            lines.append(f'version = "{ver}"')
            lines.append(f'checksum = "{h}"')
            lines.append("")
            
        with open(lock_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
