import sys
if sys.stdout.encoding != 'utf-8':
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except:
        pass
import sys
import os
from typing import List, Dict, Any, Optional

from he_core_ast import (
    ASTNode, ProgramNode, TypeNode, VarDeclNode, AssignNode, NumberNode,
    StringNode, BooleanNode, NullNode, IdentifierNode, BinaryOpNode, UnaryOpNode,
    FunctionParam, FunctionDefNode, LambdaNode, StructDefNode, TraitDefNode,
    ImplBlockNode, TypeAliasNode, EnumDefNode, UnsafeBlockNode, SpawnNode,
    TestBlockNode, AssertNode, MatchNode, TryCatchNode, MemberAccessNode,
    NullCoalesceNode, ArrayNode, IndexAccessNode, IfNode, WhileNode, ForNode,
    ReturnNode, BreakNode, ContinueNode, FunctionCallNode
)

class UniversalCodeGen:
    def __init__(self, ast: ProgramNode):
        self.ast = ast

    def generate(self) -> str:
        target = self.ast.target.lower()
        if target in ("hewasm", "wasm"):
            return self.gen_wasm()
        elif target == "hereact":
            return self.gen_react()
        elif target in ("hepy", "python"):
            return self.gen_python()
        elif target in ("hejs", "js"):
            return self.gen_js()
        else:
            return self.gen_cpp()

    # =====================================================
    # 1. C++20 CODE GENERATOR
    # =====================================================
    def gen_cpp(self) -> str:
        lines = [
            "// Auto-generated by HolyEasyLang Enterprise Compiler (hecpp - C++20)",
            "#include <iostream>",
            "#include <string>",
            "#include <vector>",
            "#include <map>",
            "#include <set>",
            "#include <optional>",
            "#include <variant>",
            "#include <thread>",
            "#include <chrono>",
            "#include <cmath>",
            "#include <algorithm>",
            "#include <cstdint>",
            "#include <iomanip>",
            "using namespace std;\n",
            "// --- HolyEasyLang Standard Core Helpers ---",
            "string input(string prompt = \"\") { if (!prompt.empty()) cout << prompt; string s; getline(cin, s); return s; }",
            "bool is_number(const string& s) { return !s.empty() && all_of(s.begin(), s.end(), ::isdigit); }",
            "int to_int(const string& s) { try { return stoi(s); } catch(...) { return 0; } }",
            "string to_string_val(int v) { return to_string(v); }",
            "bool contains(const string& s, const string& sub) { return s.find(sub) != string::npos; }",
            "uintptr_t addr(void* ptr) { return (uintptr_t)ptr; }",
            "template<typename T> uintptr_t addr(T& val) { return (uintptr_t)&val; }",
            "uintptr_t peek(uintptr_t a) { return *(uintptr_t*)a; }",
            "void delay_ms(int ms) { this_thread::sleep_for(chrono::milliseconds(ms)); }",
            "void memdump(uintptr_t a, size_t len) {",
            "    uint8_t* p = (uint8_t*)a;",
            "    for (size_t i = 0; i < len; i += 16) {",
            "        cout << \"0x\" << hex << uppercase << setw(16) << setfill('0') << (a + i) << \": \";",
            "        for (size_t j = 0; j < 16; j++) { if (i+j < len) cout << hex << setw(2) << setfill('0') << (int)p[i+j] << \" \"; else cout << \"   \"; }",
            "        cout << \" | \";",
            "        for (size_t j = 0; j < 16 && (i+j) < len; j++) cout << (isprint(p[i+j]) ? (char)p[i+j] : '.');",
            "        cout << dec << endl;",
            "    }",
            "}\n"
        ]

        def cpp_type(t: Optional[TypeNode]) -> str:
            if not t: return "auto"
            name_map = {"int": "int64_t", "float": "double", "string": "string", "bool": "bool", "void": "void", "Array": "vector"}
            base = name_map.get(t.name, t.name)
            if t.generic_args:
                args = ", ".join(cpp_type(a) for a in t.generic_args)
                base = f"{base}<{args}>"
            if t.is_pointer:
                base = f"{base}*"
            if t.is_optional:
                base = f"optional<{base}>"
            return base

        def emit_expr(node: ASTNode) -> str:
            if isinstance(node, NumberNode): return str(node.value)
            if isinstance(node, StringNode): return f'"{node.value}"'
            if isinstance(node, BooleanNode): return "true" if node.value else "false"
            if isinstance(node, NullNode): return "nullptr"
            if isinstance(node, IdentifierNode): return node.name
            if isinstance(node, BinaryOpNode):
                op_map = {"and": "&&", "or": "||"}
                op = op_map.get(node.op, node.op)
                return f"({emit_expr(node.left)} {op} {emit_expr(node.right)})"
            if isinstance(node, UnaryOpNode):
                op = "!" if node.op == "not" else node.op
                return f"({op}{emit_expr(node.expr)})"
            if isinstance(node, NullCoalesceNode):
                return f"({emit_expr(node.left)}.value_or({emit_expr(node.right)}))"
            if isinstance(node, MemberAccessNode):
                return f"{emit_expr(node.obj)}.{node.member}"
            if isinstance(node, IndexAccessNode):
                return f"{emit_expr(node.obj)}[{emit_expr(node.index_expr)}]"
            if isinstance(node, ArrayNode):
                elems = ", ".join([emit_expr(e) for e in node.elements])
                return f"vector{{{elems}}}"
            if isinstance(node, FunctionCallNode):
                if node.callee == "print":
                    args_cpp = ' << " " << '.join([emit_expr(a) for a in node.args]) if node.args else '""'
                    return f"cout << {args_cpp} << endl"
                args_cpp = ", ".join([emit_expr(a) for a in node.args])
                return f"{node.callee}({args_cpp})"
            if isinstance(node, LambdaNode):
                params_s = ", ".join([f"auto {p}" for p in node.params])
                return f"[=]({params_s}) {{ return {emit_expr(node.body)}; }}"
            return "/* expr */"

        declared_cpp_vars = set()

        def emit_stmt(node: ASTNode, indent: int = 1) -> List[str]:
            sp = "    " * indent
            res = []
            if isinstance(node, VarDeclNode):
                declared_cpp_vars.add(node.name)
                t_str = cpp_type(node.type_annot)
                const_prefix = "const " if node.is_const else ""
                res.append(f"{sp}{const_prefix}{t_str} {node.name} = {emit_expr(node.expr)};")
            elif isinstance(node, AssignNode):
                if isinstance(node.target, IdentifierNode) and node.target.name not in declared_cpp_vars:
                    declared_cpp_vars.add(node.target.name)
                    res.append(f"{sp}auto {node.target.name} = {emit_expr(node.expr)};")
                else:
                    res.append(f"{sp}{emit_expr(node.target)} = {emit_expr(node.expr)};")
            elif isinstance(node, TypeAliasNode):
                res.append(f"using {node.name} = {cpp_type(node.actual_type)};\n")
            elif isinstance(node, StructDefNode):
                gen_s = f"template<{', '.join('typename ' + g for g in node.generic_params)}>\n" if node.generic_params else ""
                fields = ";\n    ".join([f"{cpp_type(f.type_annot)} {f.name}" for f in node.fields]) + ";" if node.fields else ""
                res.append(f"{gen_s}struct {node.name} {{\n    {fields}\n}};\n")
            elif isinstance(node, TraitDefNode):
                methods = ";\n    virtual ".join([f"auto {m.name}() = 0" for m in node.methods])
                res.append(f"class {node.name} {{\npublic:\n    virtual {methods};\n}};\n")
            elif isinstance(node, ImplBlockNode):
                res.append(f"// Implementation for {node.target_type}")
                for m in node.methods:
                    res.extend(emit_stmt(m, 0))
            elif isinstance(node, EnumDefNode):
                members_s = ", ".join([f"{m[0]} = {emit_expr(m[1])}" if m[1] else m[0] for m in node.members])
                res.append(f"enum class {node.name} {{ {members_s} }};\n")
            elif isinstance(node, UnsafeBlockNode):
                res.append(f"{sp}// --- BEGIN UNSAFE BLOCK ---")
                for s in node.body: res.extend(emit_stmt(s, indent))
                res.append(f"{sp}// --- END UNSAFE BLOCK ---")
            elif isinstance(node, SpawnNode):
                res.append(f"{sp}thread([=]() {{")
                for s in node.body: res.extend(emit_stmt(s, indent + 1))
                res.append(f"{sp}}}).detach();")
            elif isinstance(node, TestBlockNode):
                res.append(f"{sp}// Test: {node.description}")
                for s in node.body: res.extend(emit_stmt(s, indent))
            elif isinstance(node, AssertNode):
                res.append(f"{sp}if (!({emit_expr(node.condition)})) {{ cerr << \"Assertion failed: {node.message or ''}\" << endl; exit(1); }}")
            elif isinstance(node, FunctionDefNode):
                gen_s = f"template<{', '.join('typename ' + g for g in node.generic_params)}>\n" if node.generic_params else ""
                params = ", ".join([f"{cpp_type(p.type_annot)} {p.name}" for p in node.params])
                ret_t = cpp_type(node.return_type)
                res.append(f"{gen_s}{ret_t} {node.name}({params}) {{")
                for s in node.body: res.extend(emit_stmt(s, indent + 1))
                res.append("}\n")
            elif isinstance(node, MatchNode):
                res.append(f"{sp}auto _match_val = {emit_expr(node.expr)};")
                for pat, stmt in node.cases:
                    res.append(f"{sp}if (_match_val == {emit_expr(pat)}) {{")
                    res.extend(emit_stmt(stmt, indent + 1))
                    res.append(f"{sp}}}")
            elif isinstance(node, TryCatchNode):
                res.append(f"{sp}try {{")
                for s in node.try_body: res.extend(emit_stmt(s, indent + 1))
                res.append(f"{sp}}} catch (const exception& {node.err_name}) {{")
                for s in node.catch_body: res.extend(emit_stmt(s, indent + 1))
                res.append(f"{sp}}}")
            elif isinstance(node, IfNode):
                res.append(f"{sp}if ({emit_expr(node.condition)}) {{")
                for s in node.then_branch: res.extend(emit_stmt(s, indent + 1))
                for cond, branch in node.elif_branches:
                    res.append(f"{sp}}} else if ({emit_expr(cond)}) {{")
                    for s in branch: res.extend(emit_stmt(s, indent + 1))
                if node.else_branch:
                    res.append(f"{sp}}} else {{")
                    for s in node.else_branch: res.extend(emit_stmt(s, indent + 1))
                res.append(f"{sp}}}")
            elif isinstance(node, WhileNode):
                res.append(f"{sp}while ({emit_expr(node.condition)}) {{")
                for s in node.body: res.extend(emit_stmt(s, indent + 1))
                res.append(f"{sp}}}")
            elif isinstance(node, ForNode):
                res.append(f"{sp}for (int {node.var_name} = {emit_expr(node.start_expr)}; {node.var_name} <= {emit_expr(node.end_expr)}; {node.var_name}++) {{")
                for s in node.body: res.extend(emit_stmt(s, indent + 1))
                res.append(f"{sp}}}")
            elif isinstance(node, ReturnNode): res.append(f"{sp}return {emit_expr(node.expr) if node.expr else ''};")
            elif isinstance(node, BreakNode): res.append(f"{sp}break;")
            elif isinstance(node, ContinueNode): res.append(f"{sp}continue;")
            else: res.append(f"{sp}{emit_expr(node)};")
            return res

        top_levels = []
        main_stmts = []
        for s in self.ast.statements:
            if isinstance(s, (StructDefNode, TraitDefNode, ImplBlockNode, EnumDefNode, FunctionDefNode, TypeAliasNode)):
                top_levels.extend(emit_stmt(s, 0))
            else:
                main_stmts.extend(emit_stmt(s, 1))

        lines.extend(top_levels)
        lines.append("int main() {")
        lines.extend(main_stmts)
        lines.append("    return 0;")
        lines.append("}")
        return "\n".join(lines)

    # =====================================================
    # 2. WASM (WebAssembly Text) GENERATOR
    # =====================================================
    def gen_wasm(self) -> str:
        wat_lines = [
            ";; Auto-generated by HolyEasyLang (hewasm - WebAssembly)",
            "(module",
            '  (import "env" "print" (func $print (param i32)))',
            '  (memory (export "memory") 1)',
        ]
        for s in self.ast.statements:
            if isinstance(s, FunctionDefNode):
                params_wat = " ".join([f"(param ${p.name} i32)" for p in node.params]) if hasattr(s, 'params') else ""
                wat_lines.append(f'  (func (export "{s.name}") {params_wat} (result i32)')
                wat_lines.append("    i32.const 42")
                wat_lines.append("  )")
        wat_lines.append(")")
        return "\n".join(wat_lines)

    # =====================================================
    # 3. REACT (TSX) GENERATOR
    # =====================================================
    def gen_react(self) -> str:
        lines = [
            "// Auto-generated by HolyEasyLang Enterprise Compiler (hereact - React 19 TSX)",
            "import React, { useState, useEffect } from 'react';",
            "",
            "export default function HolyEasyApp() {"
        ]
        for s in self.ast.statements:
            if isinstance(s, VarDeclNode):
                val_s = str(s.expr.value) if isinstance(s.expr, (NumberNode, StringNode, BooleanNode)) else "null"
                lines.append(f"  const [{s.name}, set{s.name.capitalize()}] = useState({val_s});")
        lines.extend([
            "",
            "  return (",
            "    <div style={{ padding: 24, background: '#03060A', color: '#00F0FF', fontFamily: 'monospace' }}>",
            "      <h1>⚡ HolyEasy Titan Reactive Engine</h1>",
            "    </div>",
            "  );",
            "}"
        ])
        return "\n".join(lines)

    # =====================================================
    # 4. PYTHON 3 GENERATOR
    # =====================================================
    def gen_python(self) -> str:
        lines = [
            "# Auto-generated by HolyEasyLang Titan Compiler (hepy)",
            "import sys, os, math, time, ctypes, threading, queue",
            "from he_runtime import get_runtime_env",
            "",
            "globals().update(get_runtime_env())",
            ""
        ]

        def emit_py_expr(node: ASTNode) -> str:
            if isinstance(node, NumberNode): return str(node.value)
            if isinstance(node, StringNode): return f'"{node.value}"'
            if isinstance(node, BooleanNode): return "True" if node.value else "False"
            if isinstance(node, NullNode): return "None"
            if isinstance(node, IdentifierNode): return node.name
            if isinstance(node, BinaryOpNode):
                if node.op == "|>":
                    return f"{emit_py_expr(node.right)}({emit_py_expr(node.left)})"
                return f"({emit_py_expr(node.left)} {node.op} {emit_py_expr(node.right)})"
            if isinstance(node, UnaryOpNode): return f"({node.op} {emit_py_expr(node.expr)})"
            if isinstance(node, NullCoalesceNode):
                return f"({emit_py_expr(node.left)} if {emit_py_expr(node.left)} is not None else {emit_py_expr(node.right)})"
            if isinstance(node, MemberAccessNode):
                if node.is_safe:
                    return f"(getattr({emit_py_expr(node.obj)}, '{node.member}', None) if {emit_py_expr(node.obj)} is not None else None)"
                return f"{emit_py_expr(node.obj)}.{node.member}"
            if isinstance(node, IndexAccessNode):
                return f"{emit_py_expr(node.obj)}[{emit_py_expr(node.index_expr)}]"
            if isinstance(node, ArrayNode):
                elems = ", ".join([emit_py_expr(e) for e in node.elements])
                return f"[{elems}]"
            if isinstance(node, LambdaNode):
                p_str = ", ".join(node.params)
                return f"(lambda {p_str}: {emit_py_expr(node.body)})"
            if isinstance(node, FunctionCallNode):
                args = ", ".join([emit_py_expr(a) for a in node.args])
                return f"{node.callee}({args})"
            return "None"

        def emit_py_stmt(node: ASTNode, indent: int = 0) -> List[str]:
            sp = "    " * indent
            if isinstance(node, VarDeclNode):
                return [f"{sp}{node.name} = {emit_py_expr(node.expr)}"]
            if isinstance(node, AssignNode):
                return [f"{sp}{emit_py_expr(node.target)} = {emit_py_expr(node.expr)}"]
            if isinstance(node, TypeAliasNode):
                return [f"{sp}{node.name} = type('{node.name}', (), {{}})"]
            if isinstance(node, StructDefNode):
                fields = ", ".join([f.name for f in node.fields])
                res = [f"{sp}class {node.name}:"]
                res.append(f"{sp}    def __init__(self, {fields}):" if fields else f"{sp}    pass")
                for f in node.fields:
                    res.append(f"{sp}        self.{f.name} = {f.name}")
                return res
            if isinstance(node, EnumDefNode):
                res = [f"{sp}class {node.name}:"]
                for m in node.members:
                    v_str = emit_py_expr(m[1]) if m[1] else f'"{m[0]}"'
                    res.append(f"{sp}    {m[0]} = {v_str}")
                return res
            if isinstance(node, FunctionDefNode):
                prefix = "async def " if node.is_async else "def "
                params = ", ".join([p.name for p in node.params])
                res = [f"{sp}{prefix}{node.name}({params}):"]
                if not node.body: res.append(f"{sp}    pass")
                else:
                    for s in node.body: res.extend(emit_py_stmt(s, indent + 1))
                return res
            if isinstance(node, UnsafeBlockNode):
                res = [f"{sp}# --- Unsafe Block ---"]
                for s in node.body: res.extend(emit_py_stmt(s, indent))
                return res
            if isinstance(node, SpawnNode):
                res = [f"{sp}def _bg():"]
                for s in node.body: res.extend(emit_py_stmt(s, indent + 1))
                res.append(f"{sp}threading.Thread(target=_bg, daemon=True).start()")
                return res
            if isinstance(node, TestBlockNode):
                res = [f"{sp}# Test: {node.description}"]
                for s in node.body: res.extend(emit_py_stmt(s, indent))
                return res
            if isinstance(node, AssertNode):
                msg = f', "{node.message}"' if node.message else ''
                return [f"{sp}assert {emit_py_expr(node.condition)}{msg}"]
            if isinstance(node, MatchNode):
                res = [f"{sp}_val = {emit_py_expr(node.expr)}"]
                for i, (pat, stmt) in enumerate(node.cases):
                    kw = "if" if i == 0 else "elif"
                    if isinstance(pat, FunctionCallNode) and pat.callee in ("Ok", "Err"):
                        is_ok_target = (pat.callee == "Ok")
                        var_payload = pat.args[0].name if (pat.args and isinstance(pat.args[0], IdentifierNode)) else "_payload"
                        res.append(f"{sp}{kw} isinstance(_val, Result) and _val.is_ok == {is_ok_target}:")
                        res.append(f"{sp}    {var_payload} = _val.value")
                        res.extend(emit_py_stmt(stmt, indent + 1))
                    else:
                        pat_s = emit_py_expr(pat)
                        if pat_s in ('"_" ', '"_"', '_'):
                            res.append(f"{sp}else:")
                        else:
                            res.append(f"{sp}{kw} _val == {pat_s}:")
                        res.extend(emit_py_stmt(stmt, indent + 1))
                return res
            if isinstance(node, TryCatchNode):
                res = [f"{sp}try:"]
                for s in node.try_body: res.extend(emit_py_stmt(s, indent + 1))
                res.append(f"{sp}except Exception as {node.err_name}:")
                for s in node.catch_body: res.extend(emit_py_stmt(s, indent + 1))
                return res
            if isinstance(node, IfNode):
                res = [f"{sp}if {emit_py_expr(node.condition)}:"]
                if not node.then_branch: res.append(f"{sp}    pass")
                else:
                    for s in node.then_branch: res.extend(emit_py_stmt(s, indent + 1))
                for cond, b in node.elif_branches:
                    res.append(f"{sp}elif {emit_py_expr(cond)}:")
                    for s in b: res.extend(emit_py_stmt(s, indent + 1))
                if node.else_branch:
                    res.append(f"{sp}else:")
                    for s in node.else_branch: res.extend(emit_py_stmt(s, indent + 1))
                return res
            if isinstance(node, WhileNode):
                res = [f"{sp}while {emit_py_expr(node.condition)}:"]
                for s in node.body: res.extend(emit_py_stmt(s, indent + 1))
                return res
            if isinstance(node, ForNode):
                res = [f"{sp}for {node.var_name} in range({emit_py_expr(node.start_expr)}, {emit_py_expr(node.end_expr)} + 1):"]
                for s in node.body: res.extend(emit_py_stmt(s, indent + 1))
                return res
            if isinstance(node, BreakNode): return [f"{sp}break"]
            if isinstance(node, ContinueNode): return [f"{sp}continue"]
            if isinstance(node, ReturnNode): return [f"{sp}return {emit_py_expr(node.expr) if node.expr else ''}"]
            return [f"{sp}{emit_py_expr(node)}"]

        for s in self.ast.statements:
            lines.extend(emit_py_stmt(s, 0))
        return "\n".join(lines)

    # =====================================================
    # 5. JAVASCRIPT (ES6) GENERATOR
    # =====================================================
    def gen_js(self) -> str:
        lines = ["// Auto-generated by HolyEasyLang (hejs)\n"]
        for s in self.ast.statements:
            if isinstance(s, VarDeclNode):
                val_s = str(s.expr.value) if isinstance(s.expr, (NumberNode, StringNode, BooleanNode)) else "null"
                lines.append(f"let {s.name} = {val_s};")
        return "\n".join(lines)
