// Auto-generated by HolyEasyLang Enterprise Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <set>
#include <optional>
#include <variant>
#include <thread>
#include <chrono>
#include <cmath>
#include <algorithm>
#include <cstdint>
#include <iomanip>
using namespace std;

// --- HolyEasyLang Standard Core Helpers ---
string input(string prompt = "") { if (!prompt.empty()) cout << prompt; string s; getline(cin, s); return s; }
bool is_number(const string& s) { return !s.empty() && all_of(s.begin(), s.end(), ::isdigit); }
int to_int(const string& s) { try { return stoi(s); } catch(...) { return 0; } }
string to_string_val(int v) { return to_string(v); }
bool contains(const string& s, const string& sub) { return s.find(sub) != string::npos; }
uintptr_t addr(void* ptr) { return (uintptr_t)ptr; }
template<typename T> uintptr_t addr(T& val) { return (uintptr_t)&val; }
uintptr_t peek(uintptr_t a) { return *(uintptr_t*)a; }
void delay_ms(int ms) { this_thread::sleep_for(chrono::milliseconds(ms)); }
void memdump(uintptr_t a, size_t len) {
    uint8_t* p = (uint8_t*)a;
    for (size_t i = 0; i < len; i += 16) {
        cout << "0x" << hex << uppercase << setw(16) << setfill('0') << (a + i) << ": ";
        for (size_t j = 0; j < 16; j++) { if (i+j < len) cout << hex << setw(2) << setfill('0') << (int)p[i+j] << " "; else cout << "   "; }
        cout << " | ";
        for (size_t j = 0; j < 16 && (i+j) < len; j++) cout << (isprint(p[i+j]) ? (char)p[i+j] : '.');
        cout << dec << endl;
    }
}

struct User {
    string name;
};

int main() {
    optional<User> user = nullptr;
    cout << "Kullanıcı:" << " " << (user.name.value_or("Bilinmeyen Kullanıcı")) << endl;
    return 0;
}