// Auto-generated by HolyEasyLang Enterprise Compiler (hecpp - C++20)
#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <set>
#include <optional>
#include <variant>
#include <thread>
#include <chrono>
#include <cmath>
#include <algorithm>
#include <cstdint>
#include <iomanip>
using namespace std;

// --- HolyEasyLang Standard Core Helpers ---
string input(string prompt = "") { if (!prompt.empty()) cout << prompt; string s; getline(cin, s); return s; }
bool is_number(const string& s) { return !s.empty() && all_of(s.begin(), s.end(), ::isdigit); }
int to_int(const string& s) { try { return stoi(s); } catch(...) { return 0; } }
string to_string_val(int v) { return to_string(v); }
bool contains(const string& s, const string& sub) { return s.find(sub) != string::npos; }
uintptr_t addr(void* ptr) { return (uintptr_t)ptr; }
template<typename T> uintptr_t addr(T& val) { return (uintptr_t)&val; }
uintptr_t peek(uintptr_t a) { return *(uintptr_t*)a; }
void delay_ms(int ms) { this_thread::sleep_for(chrono::milliseconds(ms)); }
void memdump(uintptr_t a, size_t len) {
    uint8_t* p = (uint8_t*)a;
    for (size_t i = 0; i < len; i += 16) {
        cout << "0x" << hex << uppercase << setw(16) << setfill('0') << (a + i) << ": ";
        for (size_t j = 0; j < 16; j++) { if (i+j < len) cout << hex << setw(2) << setfill('0') << (int)p[i+j] << " "; else cout << "   "; }
        cout << " | ";
        for (size_t j = 0; j < 16 && (i+j) < len; j++) cout << (isprint(p[i+j]) ? (char)p[i+j] : '.');
        cout << dec << endl;
    }
}

int64_t add(int64_t a, int64_t b);
string concat_str(string s1, string s2);

int64_t add(int64_t a, int64_t b) {
    return (a + b);
}

string concat_str(string s1, string s2) {
    return ((s1 + " ") + s2);
}

int main() {
    // Test: math addition
    auto res = add(10, 20);
    if (!((res == 30))) { cerr << "Assertion failed: 10 + 20 must be 30" << endl; exit(1); }
    cout << "  [PASS] add(10, 20) == 30" << endl;
    // Test: string formatting
    auto greeting = concat_str("Holy", "Easy");
    if (!((greeting == "Holy Easy"))) { cerr << "Assertion failed: string concatenation must match" << endl; exit(1); }
    cout << "  [PASS] concat_str("Holy", "Easy") == "Holy Easy"" << endl;
    // Test: array indexing
    auto numbers = vector{100, 200, 300};
    if (!((numbers[1] == 200))) { cerr << "Assertion failed: second element must be 200" << endl; exit(1); }
    cout << "  [PASS] numbers[1] == 200" << endl;
    return 0;
}