"""ES2022 runtime generation for Nyx WebAssembly bundles."""

from __future__ import annotations

from typing import Iterable, List

from src.ir.model import IRFunction


def emit_mjs(functions: Iterable[IRFunction], module_name: str) -> str:
    exported = list(functions)
    lines: List[str] = [
        f"// Auto-generated by nyx bundle ({module_name}.mjs) - ABI v1",
        "// Target: ES2022 / Node.js / Browser WebAssembly Runtime",
        "",
        "const instanceCache = new Map();",
        f"const defaultWasmSource = new URL('./{module_name}.wasm', import.meta.url);",
        "let defaultApi = null;",
        "",
        "export async function initNyxModule(source = defaultWasmSource) {",
        "  const cacheKey = source instanceof URL ? source.href : source;",
        "  let apiPromise = instanceCache.get(cacheKey);",
        "  if (!apiPromise) {",
        "    apiPromise = instantiateNyxModule(source).then(createPublicApi);",
        "    instanceCache.set(cacheKey, apiPromise);",
        "    apiPromise.catch(() => instanceCache.delete(cacheKey));",
        "  }",
        "  const api = await apiPromise;",
        "  defaultApi = api;",
        "  return api;",
        "}",
        "",
        "async function instantiateNyxModule(source) {",
        "  const importObject = {",
        "    env: {",
        "      print: (value) => console.log(value),",
        "      abort: () => { throw new WebAssembly.RuntimeError('Nyx Aborted'); },",
        "    },",
        "  };",
        "  const isNode = typeof process !== 'undefined' && Boolean(process.versions?.node);",
        "  let instance;",
        "",
        "  if (source instanceof WebAssembly.Module) {",
        "    instance = await WebAssembly.instantiate(source, importObject);",
        "  } else if (source instanceof ArrayBuffer || ArrayBuffer.isView(source)) {",
        "    const bytes = source instanceof ArrayBuffer",
        "      ? source",
        "      : new Uint8Array(source.buffer, source.byteOffset, source.byteLength);",
        "    ({ instance } = await WebAssembly.instantiate(bytes, importObject));",
        "  } else if (source instanceof URL && source.protocol === 'file:' && isNode) {",
        "    const fs = await import('node:fs/promises');",
        "    ({ instance } = await WebAssembly.instantiate(await fs.readFile(source), importObject));",
        "  } else if (typeof source === 'string' && isNode && !/^https?:\\/\\//i.test(source)) {",
        "    const fs = await import('node:fs/promises');",
        "    ({ instance } = await WebAssembly.instantiate(await fs.readFile(source), importObject));",
        "  } else {",
        "    const target = source instanceof URL ? source : new URL(String(source), import.meta.url);",
        "    const response = await fetch(target);",
        "    if (!response.ok) throw new Error(`Failed to load WASM from ${target}: HTTP ${response.status}`);",
        "    try {",
        "      ({ instance } = await WebAssembly.instantiateStreaming(response.clone(), importObject));",
        "    } catch {",
        "      ({ instance } = await WebAssembly.instantiate(await response.arrayBuffer(), importObject));",
        "    }",
        "  }",
        "",
        "  const abiVersion = instance.exports.__nyx_abi_version?.() ?? 0;",
        "  if (abiVersion !== 1) {",
        "    throw new Error(`Incompatible Nyx ABI version: expected 1, found ${abiVersion}`);",
        "  }",
        "  return instance;",
        "}",
        "",
        "function createPublicApi(instance) {",
        "  const wasm = instance.exports;",
        "  const memory = wasm.memory;",
        "  const alloc = wasm.__nyx_alloc;",
        "  const dealloc = wasm.__nyx_free;",
        "  if (!(memory instanceof WebAssembly.Memory) || typeof alloc !== 'function' || typeof dealloc !== 'function') {",
        "    throw new TypeError('Nyx ABI exports memory/__nyx_alloc/__nyx_free are required');",
        "  }",
        "",
        "  const memoryView = () => new Uint8Array(memory.buffer);",
        "",
        "  function passString(value) {",
        "    const encoded = new TextEncoder().encode(String(value ?? ''));",
        "    if (encoded.length === 0) return { ptr: 0, len: 0 };",
        "    const ptr = alloc(encoded.length) >>> 0;",
        "    if (ptr === 0) throw new RangeError(`Nyx WASM allocation failed for ${encoded.length} bytes`);",
        "    const view = memoryView();",
        "    if (ptr > view.byteLength || encoded.length > view.byteLength - ptr) {",
        "      dealloc(ptr, encoded.length);",
        "      throw new RangeError(`Nyx WASM allocation is outside linear memory: ptr=${ptr}, len=${encoded.length}`);",
        "    }",
        "    view.set(encoded, ptr);",
        "    return { ptr, len: encoded.length };",
        "  }",
        "",
        "  function readPackedString(packed) {",
        "    const value = BigInt(packed);",
        "    if (value === 0n) return '';",
        "    const ptr = Number(value & 0xffffffffn) >>> 0;",
        "    const len = Number((value >> 32n) & 0xffffffffn) >>> 0;",
        "    if (len === 0) return '';",
        "    const view = memoryView();",
        "    if (ptr === 0 || ptr > view.byteLength || len > view.byteLength - ptr) {",
        "      throw new RangeError(`WASM memory access out of bounds: ptr=${ptr}, len=${len}, max=${view.byteLength}`);",
        "    }",
        "    try {",
        "      return new TextDecoder('utf-8').decode(view.subarray(ptr, ptr + len));",
        "    } finally {",
        "      dealloc(ptr, len);",
        "    }",
        "  }",
        "",
        "  return Object.freeze({",
    ]

    for function in exported:
        lines.extend(_api_method(function))

    lines.extend([
        "  });",
        "}",
        "",
        "function requireDefaultApi() {",
        "  if (!defaultApi) throw new Error('Nyx module not initialized. Call await initNyxModule(...) first.');",
        "  return defaultApi;",
        "}",
        "",
    ])

    for function in exported:
        params = ", ".join(parameter.name for parameter in function.params)
        call = f"requireDefaultApi().{function.name}({params})"
        lines.append(f"export function {function.name}({params}) {{")
        if _return_type(function) == "void":
            lines.append(f"  {call};")
        else:
            lines.append(f"  return {call};")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def _api_method(function: IRFunction) -> List[str]:
    params = ", ".join(parameter.name for parameter in function.params)
    lines = [f"    {function.name}({params}) {{"]
    call_args: List[str] = []
    cleanups: List[str] = []
    for parameter in function.params:
        parameter_type = getattr(parameter.type_annot, "name", "int") if parameter.type_annot else "int"
        if parameter_type == "string":
            boxed = f"_{parameter.name}Boxed"
            lines.append(f"      const {boxed} = passString({parameter.name});")
            call_args.extend((f"{boxed}.ptr", f"{boxed}.len"))
            cleanups.append(f"if ({boxed}.ptr !== 0) dealloc({boxed}.ptr, {boxed}.len);")
        elif parameter_type == "float":
            call_args.append(f"Number({parameter.name})")
        else:
            call_args.append(f"({parameter.name} | 0)")

    call = f"wasm.{function.name}({', '.join(call_args)})"
    result_type = _return_type(function)
    if cleanups:
        lines.append("      try {")
        if result_type == "string":
            lines.append(f"        return readPackedString({call});")
        elif result_type == "void":
            lines.append(f"        {call};")
        else:
            lines.append(f"        return {call};")
        lines.append("      } finally {")
        for cleanup in reversed(cleanups):
            lines.append(f"        {cleanup}")
        lines.append("      }")
    elif result_type == "string":
        lines.append(f"      return readPackedString({call});")
    elif result_type == "void":
        lines.append(f"      {call};")
    else:
        lines.append(f"      return {call};")
    lines.append("    },")
    return lines


def _return_type(function: IRFunction) -> str:
    return getattr(function.return_type, "name", "void") if function.return_type else "void"
