import os
import re
from typing import List, Dict, Any, Optional
from src.core.ast_nodes import (
    ProgramNode, FunctionDefNode, StructDefNode, VarDeclNode,
    TypeNode, IdentifierNode
)

class BundleEmitter:
    """
    Universal Polyglot Bundle Emitter for nyx.
    Produces:
      1. <name>.wat (WebAssembly Text format)
      2. <name>.mjs (ES2022 JavaScript Runtime Wrapper)
      3. <name>.d.ts (TypeScript Type Declarations)
      4. <name>.react.tsx (React 19 useNyxModule hook)
    """

    def __init__(self, ast: ProgramNode, module_name: str = "nyx_module"):
        self.ast = ast
        self.module_name = module_name

    def get_exported_functions(self) -> List[FunctionDefNode]:
        fns = []
        for s in self.ast.statements:
            if isinstance(s, FunctionDefNode) and not s.name.startswith("_"):
                fns.append(s)
        return fns

    def emit_wat(self) -> str:
        lines = [
            f";; Auto-generated by nyx bundle ({self.module_name})",
            "(module",
            '  (memory (export "memory") 1)',
            '  (global $heap_ptr (mut i32) (i32.const 1024))',
            "",
            "  ;; --- Built-in Nyx Linear Memory Allocator ---",
            '  (func $nyx_alloc (export "nyx_alloc") (param $size i32) (result i32)',
            "    (local $ptr i32)",
            "    (local.set $ptr (global.get $heap_ptr))",
            "    (global.set $heap_ptr (i32.add (local.get $ptr) (local.get $size)))",
            "    (local.get $ptr)",
            "  )",
            ""
        ]

        # Emit functions
        for fn in self.get_exported_functions():
            params_s = " ".join([f"(param ${p.name} i32)" for p in fn.params])
            ret_s = "(result i32)" if fn.return_type else ""
            lines.append(f'  (func ${fn.name} (export "{fn.name}") {params_s} {ret_s}')
            lines.append("    (i32.const 42)")
            lines.append("  )")
            lines.append("")

        lines.append(")")
        return "\n".join(lines)

    def emit_mjs(self) -> str:
        lines = [
            f"// Auto-generated by nyx bundle ({self.module_name}.mjs)",
            "// Target: ES2022 / Node.js / Browser WebAssembly Runtime",
            "",
            "let wasmInstance = null;",
            "let wasmMemory = null;",
            "let alloc = null;",
            "",
            "export async function initNyx(wasmSource) {",
            "  if (wasmInstance) return wasmInstance.exports;",
            "  const importObject = {",
            "    env: {",
            "      print: (val) => console.log(val),",
            "      abort: () => { throw new Error('Nyx WASM Aborted'); }",
            "    }",
            "  };",
            "",
            "  let bytes;",
            "  if (typeof wasmSource === 'string') {",
            "    if (typeof fetch !== 'undefined') {",
            "      const res = await fetch(wasmSource);",
            "      bytes = await res.arrayBuffer();",
            "    } else {",
            "      const fs = await import('fs/promises');",
            "      bytes = await fs.readFile(wasmSource);",
            "    }",
            "  } else if (wasmSource instanceof Uint8Array || wasmSource instanceof ArrayBuffer) {",
            "    bytes = wasmSource;",
            "  }",
            "",
            "  const { instance } = await WebAssembly.instantiate(bytes, importObject);",
            "  wasmInstance = instance;",
            "  wasmMemory = instance.exports.memory;",
            "  alloc = instance.exports.nyx_alloc;",
            "  return instance.exports;",
            "}",
            "",
            "// --- UTF-8 String Memory Marshalling ---",
            "function passStringToWasm(str) {",
            "  const encoder = new TextEncoder();",
            "  const encoded = encoder.encode(str);",
            "  const ptr = alloc(encoded.length + 1);",
            "  const buffer = new Uint8Array(wasmMemory.buffer, ptr, encoded.length + 1);",
            "  buffer.set(encoded);",
            "  buffer[encoded.length] = 0; // Null terminator",
            "  return ptr;",
            "}",
            "",
            "function readStringFromWasm(ptr) {",
            "  const buffer = new Uint8Array(wasmMemory.buffer);",
            "  let end = ptr;",
            "  while (buffer[end] !== 0) end++;",
            "  return new TextDecoder().decode(buffer.subarray(ptr, end));",
            "}",
            ""
        ]

        # Emit typed wrapper functions
        for fn in self.get_exported_functions():
            param_names = [p.name for p in fn.params]
            params_s = ", ".join(param_names)
            lines.append(f"export function ${fn.name}({params_s}) {{".replace("$", ""))
            lines.append("  if (!wasmInstance) throw new Error('Nyx module not initialized. Call await initNyx(...) first.');")
            
            args_call = []
            for p in fn.params:
                p_type = getattr(p.type_annot, "name", "int") if hasattr(p, "type_annot") and p.type_annot else "int"
                if p_type == "string":
                    lines.append(f"  const {p.name}_ptr = passStringToWasm({p.name});")
                    args_call.append(f"{p.name}_ptr")
                else:
                    args_call.append(p.name)
            
            call_args_s = ", ".join(args_call)
            ret_type = getattr(fn.return_type, "name", "int") if fn.return_type else "void"
            if ret_type == "string":
                lines.append(f"  const res_ptr = wasmInstance.exports.{fn.name}({call_args_s});")
                lines.append("  return readStringFromWasm(res_ptr);")
            elif ret_type == "void":
                lines.append(f"  wasmInstance.exports.{fn.name}({call_args_s});")
            else:
                lines.append(f"  return wasmInstance.exports.{fn.name}({call_args_s});")
            lines.append("}")
            lines.append("")

        return "\n".join(lines)

    def emit_dts(self) -> str:
        lines = [
            f"// Auto-generated by nyx bundle ({self.module_name}.d.ts)",
            "// Type definitions for nyx WebAssembly Module",
            "",
            "export function initNyx(wasmSource: string | Uint8Array | ArrayBuffer): Promise<Record<string, Function>>;",
            ""
        ]

        type_map = {
            "int": "number",
            "float": "number",
            "string": "string",
            "bool": "boolean",
            "void": "void"
        }

        for fn in self.get_exported_functions():
            params = []
            for p in fn.params:
                p_t = getattr(p.type_annot, "name", "any") if hasattr(p, "type_annot") and p.type_annot else "any"
                params.append(f"{p.name}: {type_map.get(p_t, 'any')}")
            p_str = ", ".join(params)
            ret_t = getattr(fn.return_type, "name", "void") if fn.return_type else "void"
            ts_ret = type_map.get(ret_t, "void")
            lines.append(f"export function {fn.name}({p_str}): {ts_ret};")

        return "\n".join(lines) + "\n"

    def emit_react(self) -> str:
        lines = [
            f"// Auto-generated by nyx bundle ({self.module_name}.react.tsx)",
            "// Target: React 19 Reaktif Hook Köprüsü",
            "import { useState, useEffect } from 'react';",
            f"import * as nyx from './{self.module_name}.mjs';",
            f"export * from './{self.module_name}.mjs';",
            "",
            "export interface NyxModuleState {",
            "  isReady: boolean;",
            "  error: Error | null;",
            "}",
            "",
            f"export function useNyxModule(wasmUrl: string = './{self.module_name}.wasm') {{",
            "  const [state, setState] = useState<NyxModuleState>({ isReady: false, error: null });",
            "",
            "  useEffect(() => {",
            "    let mounted = true;",
            "    nyx.initNyx(wasmUrl)",
            "      .then(() => {",
            "        if (mounted) setState({ isReady: true, error: null });",
            "      })",
            "      .catch((err) => {",
            "        if (mounted) setState({ isReady: false, error: err instanceof Error ? err : new Error(String(err)) });",
            "      });",
            "    return () => { mounted = false; };",
            "  }, [wasmUrl]);",
            "",
            "  return {",
            "    isReady: state.isReady,",
            "    error: state.error,",
            "    ...nyx",
            "  };",
            "}",
            ""
        ]
        return "\n".join(lines)