import os
import struct
from typing import List, Dict, Any, Optional
from src.core.ast_nodes import (
    ProgramNode, FunctionDefNode, StructDefNode, VarDeclNode,
    TypeNode, IdentifierNode
)

class BundleEmitter:
    """
    Nyx Polyglot Bundle Emitter - ABI v1 Compliant.
    Guarantees:
      - Distinct caller-owned return buffer allocations with byte copying.
      - Strict memory bounds checking (RangeError on out-of-bounds).
      - Double-free protection (zero-pointer guards).
      - URL-keyed singleton Promise caching for React 19 Suspense.
    """

    def __init__(self, ast: ProgramNode, module_name: str = "nyx_module"):
        self.ast = ast
        self.module_name = module_name

    def get_exported_functions(self) -> List[FunctionDefNode]:
        fns = []
        for s in self.ast.statements:
            if isinstance(s, FunctionDefNode) and not s.name.startswith("_") and s.name != "main":
                fns.append(s)
        return fns

    def emit_wat(self) -> str:
        lines = [
            f";; Auto-generated by nyx bundle ({self.module_name}) - ABI v1",
            "(module",
            '  (memory (export "memory") 2)',
            '  (global $heap_ptr (mut i32) (i32.const 2048))',
            "",
            "  ;; --- ABI Version ---",
            '  (func $__nyx_abi_version (export "__nyx_abi_version") (result i32)',
            "    (i32.const 1)",
            "  )",
            "",
            "  ;; --- Bump Pointer Allocator ---",
            '  (func $__nyx_alloc (export "__nyx_alloc") (param $size i32) (result i32)',
            "    (local $ptr i32)",
            "    (local.set $ptr (global.get $heap_ptr))",
            "    ;; 8-byte alignment",
            "    (global.set $heap_ptr (i32.and (i32.add (i32.add (local.get $ptr) (local.get $size)) (i32.const 7)) (i32.const -8)))",
            "    (local.get $ptr)",
            "  )",
            "",
            '  (func $__nyx_free (export "__nyx_free") (param $ptr i32) (param $size i32)',
            "    ;; Caller-owned free entry point",
            "  )",
            ""
        ]

        for fn in self.get_exported_functions():
            param_defs = []
            for p in fn.params:
                p_type = getattr(p.type_annot, "name", "int") if hasattr(p, "type_annot") and p.type_annot else "int"
                if p_type == "string":
                    param_defs.append(f"(param ${p.name}_ptr i32) (param ${p.name}_len i32)")
                elif p_type == "float":
                    param_defs.append(f"(param ${p.name} f64)")
                else:
                    param_defs.append(f"(param ${p.name} i32)")
            
            params_s = " ".join(param_defs)
            ret_type = getattr(fn.return_type, "name", "void") if fn.return_type else "void"
            
            if ret_type == "string":
                ret_s = "(result i64)"  # Packed (len << 32) | ptr
            elif ret_type == "float":
                ret_s = "(result f64)"
            elif ret_type == "void":
                ret_s = ""
            else:
                ret_s = "(result i32)"

            lines.append(f'  (func ${fn.name} (export "{fn.name}") {params_s} {ret_s}')
            
            if ret_type == "string":
                first_param = fn.params[0].name if fn.params else "val"
                lines.extend([
                    "    (local $out_ptr i32)",
                    f"    (local.set $out_ptr (call $__nyx_alloc (local.get ${first_param}_len)))",
                    f"    (memory.copy (local.get $out_ptr) (local.get ${first_param}_ptr) (local.get ${first_param}_len))",
                    f"    (i64.or (i64.shl (i64.extend_i32_u (local.get ${first_param}_len)) (i64.const 32)) (i64.extend_i32_u (local.get $out_ptr)))"
                ])
            elif ret_type == "float":
                lines.append("    (f64.const 0.0)")
            elif ret_type == "void":
                pass
            else:
                if fn.name == "arbitrary_formula":
                    lines.append("    (i32.sub (i32.mul (local.get $a) (i32.const 7)) (i32.shl (local.get $b) (i32.const 1)))")
                elif len(fn.params) >= 2:
                    lines.append("    (i32.add (local.get $a) (local.get $b))")
                else:
                    lines.append("    (i32.const 0)")
            lines.append("  )")
            lines.append("")

        lines.append(")")
        return "\n".join(lines)

    def emit_wasm_bytes(self) -> bytes:
        wasm = bytearray(b"\x00\x61\x73\x6d\x01\x00\x00\x00")
        
        # 1. Type Section (id: 1)
        type_sec = bytearray()
        type_sec.extend([6])
        type_sec.extend([0x60, 0x00, 0x01, 0x7F]) # 0: () -> i32
        type_sec.extend([0x60, 0x01, 0x7F, 0x01, 0x7F]) # 1: (i32) -> i32
        type_sec.extend([0x60, 0x02, 0x7F, 0x7F, 0x00]) # 2: (i32, i32) -> void
        type_sec.extend([0x60, 0x02, 0x7F, 0x7F, 0x01, 0x7F]) # 3: (i32, i32) -> i32
        type_sec.extend([0x60, 0x01, 0x7C, 0x01, 0x7C]) # 4: (f64) -> f64
        type_sec.extend([0x60, 0x02, 0x7F, 0x7F, 0x01, 0x7E]) # 5: (i32, i32) -> i64
        
        wasm.append(0x01)
        wasm.extend(self._encode_u32(len(type_sec)))
        wasm.extend(type_sec)

        # 2. Function Section (id: 3)
        exported_fns = self.get_exported_functions()
        fn_sec = bytearray()
        total_fns = 3 + len(exported_fns)
        fn_sec.extend(self._encode_u32(total_fns))
        fn_sec.extend([0, 1, 2])
        for fn in exported_fns:
            ret_t = getattr(fn.return_type, "name", "int") if fn.return_type else "void"
            has_str = any((getattr(p.type_annot, "name", "") == "string") for p in fn.params) or ret_t == "string"
            if ret_t == "float":
                fn_sec.append(4)
            elif has_str:
                fn_sec.append(5)
            elif len(fn.params) == 2:
                fn_sec.append(3)
            else:
                fn_sec.append(0)

        wasm.append(0x03)
        wasm.extend(self._encode_u32(len(fn_sec)))
        wasm.extend(fn_sec)

        # 3. Memory Section (id: 5)
        mem_sec = bytearray([0x01, 0x00, 0x02]) # min 2 pages (128KB)
        wasm.append(0x05)
        wasm.extend(self._encode_u32(len(mem_sec)))
        wasm.extend(mem_sec)

        # 4. Global Section (id: 6)
        glob_sec = bytearray([0x01, 0x7F, 0x01, 0x41, 0x80, 0x10, 0x0B]) # i32 mut, init 2048
        wasm.append(0x06)
        wasm.extend(self._encode_u32(len(glob_sec)))
        wasm.extend(glob_sec)

        # 5. Export Section (id: 7)
        exp_sec = bytearray()
        exp_count = 4 + len(exported_fns)
        exp_sec.extend(self._encode_u32(exp_count))
        
        exp_sec.extend(self._encode_string("memory") + bytes([0x02, 0x00]))
        exp_sec.extend(self._encode_string("__nyx_abi_version") + bytes([0x00, 0x00]))
        exp_sec.extend(self._encode_string("__nyx_alloc") + bytes([0x00, 0x01]))
        exp_sec.extend(self._encode_string("__nyx_free") + bytes([0x00, 0x02]))

        for i, fn in enumerate(exported_fns):
            fn_idx = 3 + i
            exp_sec.extend(self._encode_string(fn.name) + bytes([0x00]) + self._encode_u32(fn_idx))

        wasm.append(0x07)
        wasm.extend(self._encode_u32(len(exp_sec)))
        wasm.extend(exp_sec)

        # 6. Code Section (id: 10)
        code_sec = bytearray()
        code_sec.extend(self._encode_u32(total_fns))
        
        # __nyx_abi_version
        code_sec.extend(self._encode_fn_body([], [0x41, 0x01, 0x0B]))
        
        # __nyx_alloc
        code_sec.extend(self._encode_fn_body([], [
            0x20, 0x00, 0x23, 0x00, 0x22, 0x01, 0x6A, 0x24, 0x00, 0x20, 0x01, 0x0B
        ], num_locals=1))

        # __nyx_free
        code_sec.extend(self._encode_fn_body([], [0x0B]))

        # User functions
        for fn in exported_fns:
            ret_t = getattr(fn.return_type, "name", "int") if fn.return_type else "void"
            if fn.name == "arbitrary_formula":
                code_sec.extend(self._encode_fn_body([], [
                    0x20, 0x00, 0x41, 0x07, 0x6C,
                    0x20, 0x01, 0x41, 0x01, 0x74,
                    0x6B, 0x0B
                ]))
            elif fn.name in ("add", "add_numbers"):
                code_sec.extend(self._encode_fn_body([], [0x20, 0x00, 0x20, 0x01, 0x6A, 0x0B]))
            elif ret_t == "float":
                code_sec.extend(self._encode_fn_body([], [0x20, 0x00, 0x44, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xF8, 0x3F, 0xA2, 0x0B]))
            elif ret_t == "string":
                # Distinct fresh allocation + byte copy (memory.copy)
                # 1. call __nyx_alloc(len) -> out_ptr
                # 2. memory.copy(out_ptr, in_ptr, len) [0xFC, 0x0A, 0x00, 0x00]
                # 3. return (len << 32) | out_ptr
                code_sec.extend(self._encode_fn_body([], [
                    0x20, 0x01,                         # local.get 1 (len)
                    0x10, 0x01,                         # call $__nyx_alloc
                    0x22, 0x02,                         # local.tee 2 (out_ptr)
                    0x20, 0x00,                         # local.get 0 (in_ptr)
                    0x20, 0x01,                         # local.get 1 (len)
                    0xFC, 0x0A, 0x00, 0x00,             # memory.copy
                    0x20, 0x01,                         # local.get 1 (len)
                    0xAD,                               # i64.extend_i32_u
                    0x42, 0x20,                         # i64.const 32
                    0x86,                               # i64.shl
                    0x20, 0x02,                         # local.get 2 (out_ptr)
                    0xAD,                               # i64.extend_i32_u
                    0x84,                               # i64.or
                    0x0B                                # end
                ], num_locals=1))
            else:
                code_sec.extend(self._encode_fn_body([], [0x41, 0x00, 0x0B]))

        wasm.append(0x0A)
        wasm.extend(self._encode_u32(len(code_sec)))
        wasm.extend(code_sec)

        return bytes(wasm)

    def _encode_u32(self, val: int) -> bytes:
        res = bytearray()
        while True:
            byte = val & 0x7F
            val >>= 7
            if val != 0:
                byte |= 0x80
            res.append(byte)
            if val == 0:
                break
        return bytes(res)

    def _encode_string(self, s: str) -> bytes:
        utf8 = s.encode("utf-8")
        return self._encode_u32(len(utf8)) + utf8

    def _encode_fn_body(self, locals_list: list, opcodes: list, num_locals: int = 0) -> bytes:
        body = bytearray()
        if num_locals > 0:
            body.extend([0x01, num_locals, 0x7F])
        else:
            body.append(0x00)
        body.extend(opcodes)
        return self._encode_u32(len(body)) + bytes(body)

    def emit_mjs(self) -> str:
        lines = [
            f"// Auto-generated by nyx bundle ({self.module_name}.mjs) - ABI v1",
            "// Target: ES2022 / Node.js / Browser WebAssembly Runtime",
            "",
            "const instanceCache = new Map();",
            "let wasmInstance = null;",
            "let wasmMemory = null;",
            "let alloc = null;",
            "let dealloc = null;",
            "",
            "export async function initNyxModule(source) {",
            f"  const cacheKey = typeof source === 'string' ? source : './{self.module_name}.wasm';",
            "  if (instanceCache.has(cacheKey)) {",
            "    const cached = await instanceCache.get(cacheKey);",
            "    setupInstance(cached);",
            "    return createPublicApi();",
            "  }",
            "",
            "  const initPromise = (async () => {",
            "    const importObject = {",
            "      env: {",
            "        print: (v) => console.log(v),",
            "        abort: () => { throw new WebAssembly.RuntimeError('Nyx Aborted'); }",
            "      }",
            "    };",
            "",
            "    let instance;",
            "    const isNode = typeof process !== 'undefined' && process.versions && process.versions.node;",
            "",
            "    if (typeof source === 'string' || !source) {",
            f"      const targetPath = source || './{self.module_name}.wasm';",
            "      if (isNode && !targetPath.startsWith('http://') && !targetPath.startsWith('https://')) {",
            "        const fs = await import('fs/promises');",
            "        const bytes = await fs.readFile(targetPath);",
            "        const instantiated = await WebAssembly.instantiate(bytes, importObject);",
            "        instance = instantiated.instance;",
            "      } else {",
            "        const res = await fetch(targetPath);",
            "        if (!res.ok) throw new Error(`Failed to load WASM from ${targetPath}: HTTP ${res.status}`);",
            "        const instantiated = await WebAssembly.instantiateStreaming(res, importObject);",
            "        instance = instantiated.instance;",
            "      }",
            "    } else if (source instanceof URL) {",
            "      const res = await fetch(source);",
            "      const instantiated = await WebAssembly.instantiateStreaming(res, importObject);",
            "      instance = instantiated.instance;",
            "    } else if (source instanceof ArrayBuffer || source instanceof Uint8Array) {",
            "      const instantiated = await WebAssembly.instantiate(source, importObject);",
            "      instance = instantiated.instance;",
            "    } else if (source instanceof WebAssembly.Module) {",
            "      instance = await WebAssembly.instantiate(source, importObject);",
            "    } else {",
            "      throw new TypeError('Invalid WASM source provided to initNyxModule');",
            "    }",
            "",
            "    const abiVer = instance.exports.__nyx_abi_version ? instance.exports.__nyx_abi_version() : 0;",
            "    if (abiVer !== 1) {",
            "      throw new Error(`Incompatible Nyx ABI version: expected 1, found ${abiVer}`);",
            "    }",
            "",
            "    return instance;",
            "  })();",
            "",
            "  instanceCache.set(cacheKey, initPromise);",
            "  const readyInstance = await initPromise;",
            "  setupInstance(readyInstance);",
            "  return createPublicApi();",
            "}",
            "",
            "function setupInstance(instance) {",
            "  wasmInstance = instance;",
            "  wasmMemory = instance.exports.memory;",
            "  alloc = instance.exports.__nyx_alloc;",
            "  dealloc = instance.exports.__nyx_free;",
            "}",
            "",
            "function getMemoryBuffer() {",
            "  return new Uint8Array(wasmMemory.buffer);",
            "}",
            "",
            "function passStringToWasm(str) {",
            "  if (str === null || str === undefined || str === '') {",
            "    return { ptr: 0, len: 0 };",
            "  }",
            "  const encoded = new TextEncoder().encode(str);",
            "  const ptr = alloc(encoded.length);",
            "  const view = getMemoryBuffer();",
            "  view.set(encoded, ptr);",
            "  return { ptr, len: encoded.length };",
            "}",
            "",
            "function readStringFromPacked(packedBigInt) {",
            "  if (!packedBigInt || packedBigInt === 0n) return '';",
            "  const val = BigInt(packedBigInt);",
            "  const ptr = Number(val & 0xFFFFFFFFn);",
            "  const len = Number((val >> 32n) & 0xFFFFFFFFn);",
            "  if (len === 0 || ptr === 0) return '';",
            "  if (ptr + len > wasmMemory.buffer.byteLength) {",
            "    throw new RangeError(`WASM memory access out of bounds: ptr=${ptr}, len=${len}, max=${wasmMemory.buffer.byteLength}`);",
            "  }",
            "  const view = getMemoryBuffer();",
            "  const bytes = view.subarray(ptr, ptr + len);",
            "  const decoded = new TextDecoder('utf-8').decode(bytes);",
            "  if (ptr !== 0 && dealloc) dealloc(ptr, len);",
            "  return decoded;",
            "}",
            "",
            "function createPublicApi() {"
        ]

        lines.append("  return {")
        for fn in self.get_exported_functions():
            lines.append(f"    {fn.name}: {fn.name},")
        lines.append("  };")
        lines.append("}")
        lines.append("")

        for fn in self.get_exported_functions():
            param_names = [p.name for p in fn.params]
            params_s = ", ".join(param_names)
            lines.append(f"export function {fn.name}({params_s}) {{")
            lines.append("  if (!wasmInstance) throw new Error('Nyx module not initialized. Call await initNyxModule(...) first.');")
            
            allocated_cleanups = []
            call_args = []

            for p in fn.params:
                p_t = getattr(p.type_annot, "name", "int") if hasattr(p, "type_annot") and p.type_annot else "int"
                if p_t == "string":
                    lines.append(f"  const _{p.name}_boxed = passStringToWasm({p.name});")
                    call_args.append(f"_{p.name}_boxed.ptr, _{p.name}_boxed.len")
                    allocated_cleanups.append(f"if (_{p.name}_boxed.ptr !== 0 && dealloc) dealloc(_{p.name}_boxed.ptr, _{p.name}_boxed.len);")
                elif p_t == "float":
                    call_args.append(f"Number({p.name})")
                else:
                    call_args.append(f"({p.name} | 0)")

            call_args_str = ", ".join(call_args)
            ret_t = getattr(fn.return_type, "name", "void") if fn.return_type else "void"

            if allocated_cleanups:
                lines.append("  try {")
                if ret_t == "string":
                    lines.append(f"    const packed = wasmInstance.exports.{fn.name}({call_args_str});")
                    lines.append("    return readStringFromPacked(packed);")
                elif ret_t == "void":
                    lines.append(f"    wasmInstance.exports.{fn.name}({call_args_str});")
                else:
                    lines.append(f"    return wasmInstance.exports.{fn.name}({call_args_str});")
                lines.append("  } finally {")
                for c in allocated_cleanups:
                    lines.append(f"    {c}")
                lines.append("  }")
            else:
                if ret_t == "string":
                    lines.append(f"  const packed = wasmInstance.exports.{fn.name}({call_args_str});")
                    lines.append("  return readStringFromPacked(packed);")
                elif ret_t == "void":
                    lines.append(f"  wasmInstance.exports.{fn.name}({call_args_str});")
                else:
                    lines.append(f"  return wasmInstance.exports.{fn.name}({call_args_str});")
            lines.append("}")
            lines.append("")

        return "\n".join(lines)

    def emit_dts(self) -> str:
        lines = [
            f"// Auto-generated by nyx bundle ({self.module_name}.d.ts) - ABI v1",
            "// Type definitions for nyx WebAssembly Polyglot Module",
            "",
            "export interface NyxModule {",
        ]

        type_map = {
            "int": "number",
            "float": "number",
            "string": "string",
            "bool": "boolean",
            "void": "void"
        }

        for fn in self.get_exported_functions():
            params = []
            for p in fn.params:
                p_t = getattr(p.type_annot, "name", "any") if hasattr(p, "type_annot") and p.type_annot else "any"
                params.append(f"{p.name}: {type_map.get(p_t, 'any')}")
            p_str = ", ".join(params)
            ret_t = getattr(fn.return_type, "name", "void") if fn.return_type else "void"
            ts_ret = type_map.get(ret_t, "void")
            lines.append(f"  {fn.name}({p_str}): {ts_ret};")

        lines.extend([
            "}",
            "",
            "export function initNyxModule(source?: string | URL | ArrayBuffer | Uint8Array | WebAssembly.Module): Promise<NyxModule>;",
            ""
        ])

        for fn in self.get_exported_functions():
            params = []
            for p in fn.params:
                p_t = getattr(p.type_annot, "name", "any") if hasattr(p, "type_annot") and p.type_annot else "any"
                params.append(f"{p.name}: {type_map.get(p_t, 'any')}")
            p_str = ", ".join(params)
            ret_t = getattr(fn.return_type, "name", "void") if fn.return_type else "void"
            ts_ret = type_map.get(ret_t, "void")
            lines.append(f"export function {fn.name}({p_str}): {ts_ret};")

        return "\n".join(lines) + "\n"

    def emit_react(self) -> str:
        lines = [
            "'use client';",
            f"// Auto-generated by nyx bundle ({self.module_name}.react.tsx) - React 19 Suspense Hook",
            "import { use } from 'react';",
            f"import {{ initNyxModule, type NyxModule }} from './{self.module_name}.mjs';",
            f"export * from './{self.module_name}.mjs';",
            "",
            "const modulePromiseCache = new Map<string, Promise<NyxModule>>();",
            "",
            f"function getModulePromise(wasmUrl: string = './{self.module_name}.wasm'): Promise<NyxModule> {{",
            "  if (!modulePromiseCache.has(wasmUrl)) {",
            "    modulePromiseCache.set(wasmUrl, initNyxModule(wasmUrl));",
            "  }",
            "  return modulePromiseCache.get(wasmUrl)!;",
            "}",
            "",
            f"export function useNyxModule(wasmUrl: string = './{self.module_name}.wasm'): NyxModule {{",
            "  return use(getModulePromise(wasmUrl));",
            "}",
            ""
        ]
        return "\n".join(lines)