"""ES2022 runtime generation for Nyx WebAssembly bundles."""

from __future__ import annotations

from typing import Iterable, List

from src.ir.model import IRFunction, IRStruct, IRTypeAlias
from src.codegen.wasm_ir import BundleCompileError


def emit_mjs(
    functions: Iterable[IRFunction],
    module_name: str,
    structs: Iterable[IRStruct] = (),
    aliases: Iterable[IRTypeAlias] = (),
    wasi: bool = False,
) -> str:
    exported = list(functions)
    struct_map = {item.name: item for item in structs}
    alias_map = {
        item.name: getattr(item.actual_type, "name", str(item.actual_type))
        for item in aliases
    }
    lines: List[str] = [
        f"// Auto-generated by nyx bundle ({module_name}.mjs) - ABI v1",
        "// Target: ES2022 / Node.js / Browser WebAssembly Runtime",
        "",
        "const instanceCache = new Map();",
        f"const defaultWasmSource = new URL('./{module_name}.wasm', import.meta.url);",
        "let defaultApi = null;",
        "",
        "function createDefaultImports(getInstance) {",
        "  const handles = new Map();",
        "  let nextHandle = 1;",
        "  const store = (value) => { if (value == null) return 0; const id = nextHandle++; handles.set(id, value); return id; };",
        "  const load = (id, kind = 'web value') => { const value = handles.get(id >>> 0); if (value == null) throw new RangeError(`Unknown Nyx ${kind} handle: ${id}`); return value; };",
        "  const memory = () => { const value = getInstance()?.exports?.memory; if (!(value instanceof WebAssembly.Memory)) throw new TypeError('Nyx WASM memory is not initialized'); return value; };",
        "  const text = (ptr, len) => {",
        "    const view = new Uint8Array(memory().buffer);",
        "    ptr >>>= 0; len >>>= 0;",
        "    if (ptr > view.byteLength || len > view.byteLength - ptr) throw new RangeError(`Nyx host string is outside linear memory: ptr=${ptr}, len=${len}`);",
        "    return new TextDecoder('utf-8').decode(view.subarray(ptr, ptr + len));",
        "  };",
        "  const browserDocument = () => { if (typeof document === 'undefined') throw new Error('std/web requires a browser DOM host'); return document; };",
        "  const dispatch = (callbackId, eventId) => {",
        "    const fn = getInstance()?.exports?.nyx_dispatch;",
        "    if (typeof fn !== 'function') throw new TypeError('std/web event use requires exported fn nyx_dispatch(callback_id: int, event: WebEvent)');",
        "    return fn(callbackId | 0, eventId | 0);",
        "  };",
        "  const wasiFdWrite = (fd, iovsPtr, iovsLen, nwrittenPtr) => {",
        "    if (fd !== 1 && fd !== 2) return 8; // WASI errno BADF",
        "    const bytes = new Uint8Array(memory().buffer); const view = new DataView(bytes.buffer);",
        "    let written = 0; const chunks = []; iovsPtr >>>= 0; iovsLen >>>= 0; nwrittenPtr >>>= 0;",
        "    if (iovsPtr > bytes.byteLength || iovsLen > Math.floor((bytes.byteLength - iovsPtr) / 8)) return 21;",
        "    for (let index = 0; index < iovsLen; index++) {",
        "      const entry = iovsPtr + index * 8; const ptr = view.getUint32(entry, true); const len = view.getUint32(entry + 4, true);",
        "      if (ptr > bytes.byteLength || len > bytes.byteLength - ptr) return 21;",
        "      chunks.push(bytes.slice(ptr, ptr + len)); written += len;",
        "    }",
        "    if (nwrittenPtr > bytes.byteLength || 4 > bytes.byteLength - nwrittenPtr) return 21;",
        "    view.setUint32(nwrittenPtr, written >>> 0, true);",
        "    const output = new TextDecoder('utf-8').decode(Uint8Array.from(chunks.flatMap((chunk) => [...chunk])));",
        "    if (typeof process !== 'undefined' && process.stdout?.write) (fd === 2 ? process.stderr : process.stdout).write(output); else console.log(output.replace(/\\n$/, ''));",
        "    return 0;",
        "  };",
        "  return {",
        "    env: {",
        "      print: (value) => console.log(value),",
        "      abort: () => { throw new WebAssembly.RuntimeError('Nyx Aborted'); },",
        "    },",
        "    wasi_snapshot_preview1: { fd_write: wasiFdWrite },",
        "    nyx_host_v1: {",
        "      _nyx_host_abi_version: () => 1,",
        "      _nyx_web_document: () => store(browserDocument()),",
        "      _nyx_web_query: (ptr, len) => store(browserDocument().querySelector(text(ptr, len))),",
        "      _nyx_web_create: (ptr, len) => store(browserDocument().createElement(text(ptr, len))),",
        "      _nyx_web_set_text: (handle, ptr, len) => { load(handle, 'element').textContent = text(ptr, len); },",
        "      _nyx_web_set_attribute: (handle, np, nl, vp, vl) => load(handle, 'element').setAttribute(text(np, nl), text(vp, vl)),",
        "      _nyx_web_append: (parent, child) => load(parent, 'element').append(load(child, 'element')),",
        "      _nyx_web_remove: (handle) => load(handle, 'element').remove(),",
        "      _nyx_web_release: (handle) => { handles.delete(handle >>> 0); },",
        "      _nyx_web_listen: (handle, ptr, len, callbackId) => {",
        "        const target = load(handle, 'element'); const type = text(ptr, len);",
        "        const listener = (event) => { const eventId = store(event); try { dispatch(callbackId, eventId); } finally { handles.delete(eventId); } };",
        "        target.addEventListener(type, listener); return store({ target, type, listener });",
        "      },",
        "      _nyx_web_unlisten: (handle) => { const item = load(handle, 'listener'); item.target.removeEventListener(item.type, item.listener); handles.delete(handle >>> 0); },",
        "      _nyx_web_request_animation_frame: (callbackId) => {",
        "        const raf = globalThis.requestAnimationFrame; if (typeof raf !== 'function') throw new Error('requestAnimationFrame is unavailable');",
        "        raf(() => dispatch(callbackId, 0));",
        "      },",
        "      _nyx_web_event_key: (handle) => { const key = String(load(handle, 'event').key ?? ''); return key.length ? key.codePointAt(0) : 0; },",
        "      _nyx_web_canvas_clear: (handle) => { const canvas = load(handle, 'canvas'); const ctx = canvas.getContext('2d'); if (!ctx) throw new Error('Canvas 2D context unavailable'); ctx.clearRect(0, 0, canvas.width, canvas.height); },",
        "      _nyx_web_canvas_set_fill_style: (handle, ptr, len) => { const ctx = load(handle, 'canvas').getContext('2d'); if (!ctx) throw new Error('Canvas 2D context unavailable'); ctx.fillStyle = text(ptr, len); },",
        "      _nyx_web_canvas_fill_rect: (handle, x, y, width, height) => { const ctx = load(handle, 'canvas').getContext('2d'); if (!ctx) throw new Error('Canvas 2D context unavailable'); ctx.fillRect(x, y, width, height); },",
        "      _nyx_web_canvas_draw_line: (handle, x1, y1, x2, y2, cp, cl, width) => {",
        "        const ctx = load(handle, 'canvas').getContext('2d'); if (!ctx) throw new Error('Canvas 2D context unavailable');",
        "        ctx.strokeStyle = text(cp, cl); ctx.lineWidth = width; ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke();",
        "      },",
        "      _nyx_web_canvas_draw_circle: (handle, x, y, radius, cp, cl) => {",
        "        const ctx = load(handle, 'canvas').getContext('2d'); if (!ctx) throw new Error('Canvas 2D context unavailable');",
        "        ctx.fillStyle = text(cp, cl); ctx.beginPath(); ctx.arc(x, y, Math.max(0, radius), 0, 6.283185307179586); ctx.fill();",
        "      },",
        "      _nyx_web_canvas_draw_glow_circle: (handle, x, y, radius, ip, il, op, ol) => {",
        "        const ctx = load(handle, 'canvas').getContext('2d'); if (!ctx) throw new Error('Canvas 2D context unavailable');",
        "        const r = Math.max(0.1, radius); const grad = ctx.createRadialGradient(x, y, 0, x, y, r);",
        "        grad.addColorStop(0, text(ip, il)); grad.addColorStop(1, text(op, ol)); ctx.fillStyle = grad;",
        "        ctx.beginPath(); ctx.arc(x, y, r, 0, 6.283185307179586); ctx.fill();",
        "      },",
        "      _nyx_web_canvas_set_global_alpha: (handle, alpha) => {",
        "        const ctx = load(handle, 'canvas').getContext('2d'); if (!ctx) throw new Error('Canvas 2D context unavailable');",
        "        ctx.globalAlpha = Math.max(0, Math.min(1, alpha));",
        "      },",
        "      _nyx_web_canvas_set_blend_mode: (handle, ptr, len) => {",
        "        const ctx = load(handle, 'canvas').getContext('2d'); if (!ctx) throw new Error('Canvas 2D context unavailable');",
        "        ctx.globalCompositeOperation = text(ptr, len);",
        "      },",
        "    },",
        "  };",
        "}",
        "",
        "export async function initNyxModule(source = defaultWasmSource) {",
        "  const cacheKey = source instanceof URL ? source.href : source;",
        "  let apiPromise = instanceCache.get(cacheKey);",
        "  if (!apiPromise) {",
        "    apiPromise = instantiateNyxModule(source).then(createPublicApi);",
        "    instanceCache.set(cacheKey, apiPromise);",
        "    apiPromise.catch(() => instanceCache.delete(cacheKey));",
        "  }",
        "  const api = await apiPromise;",
        "  defaultApi = api;",
        "  return api;",
        "}",
        "",
        "export async function createNyxModule(source = defaultWasmSource, options = {}) {",
        "  return createPublicApi(await instantiateNyxModule(source, options.imports));",
        "}",
        "",
        "async function instantiateNyxModule(source, customImports = undefined) {",
        "  let instance;",
        "  const defaultImports = createDefaultImports(() => instance);",
        "  const importObject = customImports ? {",
        "    ...defaultImports, ...customImports,",
        "    env: { ...defaultImports.env, ...(customImports.env ?? {}) },",
        "    wasi_snapshot_preview1: { ...defaultImports.wasi_snapshot_preview1, ...(customImports.wasi_snapshot_preview1 ?? {}) },",
        "    nyx_host_v1: { ...defaultImports.nyx_host_v1, ...(customImports.nyx_host_v1 ?? {}) },",
        "  } : defaultImports;",
        "  const isNode = typeof process !== 'undefined' && Boolean(process.versions?.node);",
        "",
        "  if (source instanceof WebAssembly.Module) {",
        "    instance = await WebAssembly.instantiate(source, importObject);",
        "  } else if (source instanceof ArrayBuffer || ArrayBuffer.isView(source)) {",
        "    const bytes = source instanceof ArrayBuffer",
        "      ? source",
        "      : new Uint8Array(source.buffer, source.byteOffset, source.byteLength);",
        "    ({ instance } = await WebAssembly.instantiate(bytes, importObject));",
        "  } else if (source instanceof URL && source.protocol === 'file:' && isNode) {",
        "    const fs = await import('node:fs/promises');",
        "    ({ instance } = await WebAssembly.instantiate(await fs.readFile(source), importObject));",
        "  } else if (typeof source === 'string' && isNode && !/^https?:\\/\\//i.test(source)) {",
        "    const fs = await import('node:fs/promises');",
        "    ({ instance } = await WebAssembly.instantiate(await fs.readFile(source), importObject));",
        "  } else {",
        "    const target = source instanceof URL ? source : new URL(String(source), import.meta.url);",
        "    const response = await fetch(target);",
        "    if (!response.ok) throw new Error(`Failed to load WASM from ${target}: HTTP ${response.status}`);",
        "    try {",
        "      ({ instance } = await WebAssembly.instantiateStreaming(response.clone(), importObject));",
        "    } catch {",
        "      ({ instance } = await WebAssembly.instantiate(await response.arrayBuffer(), importObject));",
        "    }",
        "  }",
        "",
        "  const abiVersion = instance.exports.__nyx_abi_version?.() ?? 0;",
        "  if (abiVersion !== 1) {",
        "    throw new Error(`Incompatible Nyx ABI version: expected 1, found ${abiVersion}`);",
        "  }",
        "  return instance;",
        "}",
        "",
        "function createPublicApi(instance) {",
        "  const wasm = instance.exports;",
        "  const memory = wasm.memory;",
        "  const alloc = wasm.__nyx_alloc;",
        "  const dealloc = wasm.__nyx_free;",
        "  const hostAbiVersion = typeof wasm.web_host_abi_version === 'function' ? wasm.web_host_abi_version() : 1;",
        "  if (hostAbiVersion !== 1) throw new Error(`Incompatible Nyx host ABI version: expected 1, found ${hostAbiVersion}`);",
        "  if (!(memory instanceof WebAssembly.Memory) || typeof alloc !== 'function' || typeof dealloc !== 'function') {",
        "    throw new TypeError('Nyx ABI exports memory/__nyx_alloc/__nyx_free are required');",
        "  }",
        "",
        "  const memoryView = () => new Uint8Array(memory.buffer);",
        "",
        "  function passString(value) {",
        "    const encoded = new TextEncoder().encode(String(value ?? ''));",
        "    if (encoded.length === 0) return { ptr: 0, len: 0 };",
        "    const ptr = alloc(encoded.length) >>> 0;",
        "    if (ptr === 0) throw new RangeError(`Nyx WASM allocation failed for ${encoded.length} bytes`);",
        "    const view = memoryView();",
        "    if (ptr > view.byteLength || encoded.length > view.byteLength - ptr) {",
        "      dealloc(ptr, encoded.length);",
        "      throw new RangeError(`Nyx WASM allocation is outside linear memory: ptr=${ptr}, len=${encoded.length}`);",
        "    }",
        "    view.set(encoded, ptr);",
        "    return { ptr, len: encoded.length };",
        "  }",
        "",
        "  function passNumericArray(value, kind) {",
        "    if (!Array.isArray(value) && !ArrayBuffer.isView(value)) throw new TypeError('Nyx WASM array arguments require an Array or typed array');",
        "    const length = value.length >>> 0;",
        "    const stride = kind === 'f64' ? 8 : 4;",
        "    const size = length * stride;",
        "    if (length !== 0 && Math.floor(size / stride) !== length) throw new RangeError('Nyx WASM array is too large');",
        "    if (size === 0) return { ptr: 0, len: 0, size: 0 };",
        "    const ptr = alloc(size) >>> 0;",
        "    if (ptr === 0) throw new RangeError(`Nyx WASM allocation failed for ${size} bytes`);",
        "    const view = memoryView();",
        "    if (ptr > view.byteLength || size > view.byteLength - ptr) { dealloc(ptr, size); throw new RangeError('Nyx WASM array allocation is outside linear memory'); }",
        "    const data = new DataView(view.buffer, view.byteOffset + ptr, size);",
        "    for (let index = 0; index < length; index++) {",
        "      if (kind === 'f64') data.setFloat64(index * stride, Number(value[index]), true);",
        "      else data.setInt32(index * stride, Number(value[index]) | 0, true);",
        "    }",
        "    return { ptr, len: length, size };",
        "  }",
        "",
        "  function passScalarStruct(value, size, fields) {",
        "    if (value === null || typeof value !== 'object' || Array.isArray(value)) throw new TypeError('Nyx WASM struct arguments require an object');",
        "    const ptr = alloc(size) >>> 0;",
        "    if (ptr === 0) throw new RangeError(`Nyx WASM allocation failed for ${size} bytes`);",
        "    const bytes = memoryView();",
        "    if (ptr > bytes.byteLength || size > bytes.byteLength - ptr) { dealloc(ptr, size); throw new RangeError('Nyx WASM struct allocation is outside linear memory'); }",
        "    const data = new DataView(bytes.buffer, bytes.byteOffset + ptr, size);",
        "    for (const field of fields) {",
        "      if (!(field.name in value)) { dealloc(ptr, size); throw new TypeError(`Missing Nyx struct field: ${field.name}`); }",
        "      if (field.kind === 'f64') data.setFloat64(field.offset, Number(value[field.name]), true);",
        "      else data.setInt32(field.offset, field.kind === 'bool' ? (value[field.name] ? 1 : 0) : (Number(value[field.name]) | 0), true);",
        "    }",
        "    return { ptr, size };",
        "  }",
        "",
        "  function readPackedString(packed) {",
        "    const value = BigInt(packed);",
        "    if (value === 0n) return '';",
        "    const ptr = Number(value & 0xffffffffn) >>> 0;",
        "    const len = Number((value >> 32n) & 0xffffffffn) >>> 0;",
        "    if (len === 0) return '';",
        "    const view = memoryView();",
        "    if (ptr === 0 || ptr > view.byteLength || len > view.byteLength - ptr) {",
        "      throw new RangeError(`WASM memory access out of bounds: ptr=${ptr}, len=${len}, max=${view.byteLength}`);",
        "    }",
        "    try {",
        "      return new TextDecoder('utf-8').decode(view.subarray(ptr, ptr + len));",
        "    } finally {",
        "      dealloc(ptr, len);",
        "    }",
        "  }",
        "",
        "  return Object.freeze({",
    ]

    if wasi:
        lines.extend((
            "    run() {",
            "      if (typeof wasm._start !== 'function') throw new TypeError('Nyx WASI _start export is missing');",
            "      wasm._start();",
            "    },",
        ))

    for function in exported:
        lines.extend(_api_method(function, struct_map, alias_map))

    lines.extend([
        "  });",
        "}",
        "",
        "function requireDefaultApi() {",
        "  if (!defaultApi) throw new Error('Nyx module not initialized. Call await initNyxModule(...) first.');",
        "  return defaultApi;",
        "}",
        "",
    ])

    for function in exported:
        params = ", ".join(parameter.name for parameter in function.params)
        call = f"requireDefaultApi().{function.name}({params})"
        lines.append(f"export function {function.name}({params}) {{")
        if _return_type(function) == "void":
            lines.append(f"  {call};")
        else:
            lines.append(f"  return {call};")
        lines.append("}")
        lines.append("")

    if wasi:
        lines.extend((
            "export function run() {",
            "  requireDefaultApi().run();",
            "}",
            "",
        ))

    return "\n".join(lines)


def _api_method(
    function: IRFunction,
    struct_map: dict[str, IRStruct],
    alias_map: dict[str, str],
) -> List[str]:
    params = ", ".join(parameter.name for parameter in function.params)
    lines = [f"    {function.name}({params}) {{"]
    call_args: List[str] = []
    cleanups: List[str] = []
    for parameter in function.params:
        parameter_type = getattr(parameter.type_annot, "name", "int") if parameter.type_annot else "int"
        if parameter_type == "string":
            boxed = f"_{parameter.name}Boxed"
            lines.append(f"      const {boxed} = passString({parameter.name});")
            call_args.extend((f"{boxed}.ptr", f"{boxed}.len"))
            cleanups.append(f"if ({boxed}.ptr !== 0) dealloc({boxed}.ptr, {boxed}.len);")
        elif parameter_type == "Array":
            arguments = getattr(parameter.type_annot, "arguments", ())
            element_name = getattr(arguments[0], "name", "int") if arguments else "int"
            kind = "f64" if element_name == "float" else "i32"
            boxed = f"_{parameter.name}Boxed"
            lines.append(f"      const {boxed} = passNumericArray({parameter.name}, '{kind}');")
            call_args.extend((f"{boxed}.ptr", f"{boxed}.len"))
            cleanups.append(f"if ({boxed}.ptr !== 0) dealloc({boxed}.ptr, {boxed}.size);")
        elif parameter_type in struct_map:
            size, fields = _struct_layout(struct_map[parameter_type], alias_map)
            schema = ", ".join(
                "{" + f"name: {field_name!r}, kind: {kind!r}, offset: {offset}" + "}"
                for field_name, kind, offset in fields
            )
            boxed = f"_{parameter.name}Boxed"
            lines.append(
                f"      const {boxed} = passScalarStruct({parameter.name}, {size}, [{schema}]);"
            )
            call_args.append(f"{boxed}.ptr")
            cleanups.append(f"if ({boxed}.ptr !== 0) dealloc({boxed}.ptr, {boxed}.size);")
        elif parameter_type == "float":
            call_args.append(f"Number({parameter.name})")
        elif parameter_type == "bool":
            call_args.append(f"({parameter.name} ? 1 : 0)")
        else:
            call_args.append(f"({parameter.name} | 0)")

    call = f"wasm.{function.name}({', '.join(call_args)})"
    result_type = _return_type(function)
    if cleanups:
        lines.append("      try {")
        if result_type == "string":
            lines.append(f"        return readPackedString({call});")
        elif result_type == "void":
            lines.append(f"        {call};")
        elif result_type == "bool":
            lines.append(f"        return Boolean({call});")
        else:
            lines.append(f"        return {call};")
        lines.append("      } finally {")
        for cleanup in reversed(cleanups):
            lines.append(f"        {cleanup}")
        lines.append("      }")
    elif result_type == "string":
        lines.append(f"      return readPackedString({call});")
    elif result_type == "void":
        lines.append(f"      {call};")
    elif result_type == "bool":
        lines.append(f"      return Boolean({call});")
    else:
        lines.append(f"      return {call};")
    lines.append("    },")
    return lines


def _return_type(function: IRFunction) -> str:
    return getattr(function.return_type, "name", "void") if function.return_type else "void"


def _struct_layout(
    struct: IRStruct,
    aliases: dict[str, str],
) -> tuple[int, tuple[tuple[str, str, int], ...]]:
    offset = 0
    max_alignment = 1
    fields = []
    for field in struct.fields:
        name = getattr(field.type, "name", "")
        seen = set()
        while name in aliases and name not in seen:
            seen.add(name)
            name = aliases[name]
        if name not in ("int", "float", "bool"):
            raise BundleCompileError(
                f"WASM struct ABI supports only int/float/bool fields; "
                f"'{struct.name}.{field.name}' is '{name}'"
            )
        kind = "f64" if name == "float" else ("bool" if name == "bool" else "i32")
        alignment = 8 if kind == "f64" else 4
        offset = (offset + alignment - 1) & -alignment
        fields.append((field.name, kind, offset))
        offset += alignment
        max_alignment = max(max_alignment, alignment)
    total = (offset + max_alignment - 1) & -max_alignment
    return total, tuple(fields)
