import sys
if sys.stdout.encoding != 'utf-8':
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except:
        pass
import sys
import os
import json
from typing import List, Dict, Any, Optional

_root_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.core.ast_nodes import (
    ASTNode, ProgramNode, TypeNode, VarDeclNode, AssignNode, NumberNode,
    StringNode, BooleanNode, NullNode, IdentifierNode, BinaryOpNode, UnaryOpNode,
    FunctionParam, FunctionDefNode, LambdaNode, StructDefNode, TraitDefNode,
    ImplBlockNode, TypeAliasNode, EnumDefNode, UnsafeBlockNode, SpawnNode,
    TestBlockNode, AssertNode, MatchNode, TryCatchNode, MemberAccessNode,
    NullCoalesceNode, ArrayNode, IndexAccessNode, IfNode, WhileNode, ForNode,
    ReturnNode, BreakNode, ContinueNode, FunctionCallNode,
    NativeIncludeNode, NativeLinkNode, NativeRawNode, NativeUseNode, ExternFnDeclNode
)

class UniversalCodeGen:
    def __init__(self, ast: ProgramNode):
        self.ast = ast

    def generate(self) -> str:
        target = self.ast.target.lower()
        if target in ("hewasm", "wasm"):
            return self.gen_wasm()
        elif target == "hereact":
            return self.gen_react()
        elif target in ("hepy", "python"):
            return self.gen_python()
        elif target in ("hejs", "js"):
            return self.gen_js()
        else:
            return self.gen_cpp()

    def get_link_libraries(self) -> List[str]:
        libs = []
        for s in self.ast.statements:
            if isinstance(s, NativeLinkNode):
                if s.library not in libs:
                    libs.append(s.library)
        return libs

    # =====================================================
    # 1. C++20 CODE GENERATOR (NATIVE FFI & ZERO-OVERHEAD)
    # =====================================================
    def gen_cpp(self) -> str:
        # Collect native directives and extern declarations
        native_includes = [s.header for s in self.ast.statements if isinstance(s, NativeIncludeNode)]
        native_raws = [s.raw for s in self.ast.statements if isinstance(s, NativeRawNode)]
        native_uses = [s.target for s in self.ast.statements if isinstance(s, NativeUseNode)]
        extern_c_funcs: Dict[str, ExternFnDeclNode] = {}
        for s in self.ast.statements:
            if isinstance(s, ExternFnDeclNode):
                extern_c_funcs[s.name] = s

        # Scan AST to detect which runtime helpers & headers are actually required
        used_syms = set()
        has_arrays = False
        has_spawn = False

        def scan_ast(n):
            nonlocal has_arrays, has_spawn
            if not n: return
            if isinstance(n, FunctionCallNode):
                if isinstance(n.callee, str):
                    used_syms.add(n.callee)
                for a in n.args: scan_ast(a)
            elif isinstance(n, IdentifierNode):
                used_syms.add(n.name)
            elif isinstance(n, ArrayNode) or isinstance(n, IndexAccessNode):
                has_arrays = True
                if isinstance(n, ArrayNode):
                    for el in n.elements: scan_ast(el)
                else:
                    scan_ast(n.obj)
                    scan_ast(n.index_expr)
            elif isinstance(n, SpawnNode):
                has_spawn = True
                for s in n.body: scan_ast(s)
            elif hasattr(n, '__dict__'):
                for v in n.__dict__.values():
                    if isinstance(v, list):
                        for item in v:
                            if isinstance(item, ASTNode): scan_ast(item)
                    elif isinstance(v, ASTNode):
                        scan_ast(v)

        for stmt in self.ast.statements:
            scan_ast(stmt)

        lines = [
            "// Auto-generated by nyx Systems Compiler (hecpp - C++20)",
            "#include <iostream>",
            "#include <string>"
        ]

        if has_arrays or "push" in used_syms or "len" in used_syms or "length" in used_syms:
            lines.append("#include <vector>")
        if has_spawn or "delay_ms" in used_syms:
            lines.append("#include <thread>")
            lines.append("#include <chrono>")
        if "memdump" in used_syms:
            lines.append("#include <iomanip>")
        if "addr" in used_syms or "peek" in used_syms or "memdump" in used_syms:
            lines.append("#include <cstdint>")
        if "is_number" in used_syms:
            lines.append("#include <algorithm>")

        lines.extend([
            "#ifdef _WIN32",
            "#include <windows.h>",
            "#endif"
        ])

        # Add user-specified native includes
        for inc in native_includes:
            if inc.startswith("<") or inc.startswith('"'):
                lines.append(f"#include {inc}")
            else:
                lines.append(f"#include <{inc}>")

        # Add user-specified raw native snippets
        for raw in native_raws:
            lines.append(raw)

        # Add user-specified native uses (#native use ...)
        for u in native_uses:
            u_clean = u.strip().rstrip(';')
            if u_clean.startswith("namespace ") or u_clean.startswith("using "):
                lines.append(f"using {u_clean};" if not u_clean.startswith("using ") else f"{u_clean};")
            elif "::" in u_clean or u_clean in ("vector", "string", "map", "set", "unique_ptr", "shared_ptr", "function"):
                lines.append(f"using {u_clean};")
            else:
                lines.append(f"using namespace {u_clean};")

        lines.append("using namespace std;\n")

        # Emit helpers ONLY if used
        helper_lines = []
        if "input" in used_syms:
            helper_lines.append("string input(string prompt = \"\") { if (!prompt.empty()) cout << prompt; string s; getline(cin, s); return s; }")
        if "is_number" in used_syms:
            helper_lines.append("bool is_number(const string& s) { return !s.empty() && all_of(s.begin(), s.end(), ::isdigit); }")
        if "to_int" in used_syms:
            helper_lines.append("int to_int(const string& s) { try { return stoi(s); } catch(...) { return 0; } }")
        if "to_string_val" in used_syms or "to_string" in used_syms or "to_str" in used_syms:
            helper_lines.append("string to_string_val(int v) { return to_string(v); }")
        if "contains" in used_syms:
            helper_lines.append("bool contains(const string& s, const string& sub) { return s.find(sub) != string::npos; }")
        if "addr" in used_syms:
            helper_lines.append("uintptr_t addr(void* ptr) { return (uintptr_t)ptr; }")
            helper_lines.append("template<typename T> uintptr_t addr(T& val) { return (uintptr_t)&val; }")
        if "peek" in used_syms:
            helper_lines.append("uintptr_t peek(uintptr_t a) { return *(uintptr_t*)a; }")
        if "delay_ms" in used_syms:
            helper_lines.append("void delay_ms(int ms) { this_thread::sleep_for(chrono::milliseconds(ms)); }")
        if has_arrays or "len" in used_syms or "length" in used_syms:
            helper_lines.append("template<typename T> int64_t len(const T& c) { return (int64_t)c.size(); }")
            helper_lines.append("template<typename T> int64_t length(const T& c) { return (int64_t)c.size(); }")
        if has_arrays or "push" in used_syms:
            helper_lines.append("template<typename T, typename V> void push(vector<T>& v, const V& val) { v.push_back(val); }")
        if has_arrays or "_nyx_at" in used_syms:
            helper_lines.append("template<typename T> auto& _nyx_at(vector<T>& v, int64_t i) { return v[i]; }")
            helper_lines.append("template<typename T> const auto& _nyx_at(const vector<T>& v, int64_t i) { return v[i]; }")
            helper_lines.append("inline string _nyx_at(const string& s, int64_t i) { if (i < 0 || (size_t)i >= s.size()) return \"\"; return string(1, s[i]); }")
        if "Result" in used_syms or "Ok" in used_syms or "Err" in used_syms:
            helper_lines.append("template<typename T, typename E = string>")
            helper_lines.append("struct Result { bool is_ok; T value; E error; Result(bool ok, T val, E err) : is_ok(ok), value(val), error(err) {} template<typename U> Result(const Result<U, E>& o) : is_ok(o.is_ok), value((T)o.value), error(o.error) {} };")
            helper_lines.append("template<typename T> Result<T, string> Ok(T val) { return Result<T, string>(true, val, \"\"); }")
            helper_lines.append("template<typename T = int64_t> Result<T, string> Err(string err) { return Result<T, string>(false, T{}, err); }")
        if "memdump" in used_syms:
            helper_lines.extend([
                "void memdump(uintptr_t a, size_t len) {",
                "    uint8_t* p = (uint8_t*)a;",
                "    for (size_t i = 0; i < len; i += 16) {",
                "        cout << \"0x\" << hex << uppercase << setw(16) << setfill('0') << (a + i) << \": \";",
                "        for (size_t j = 0; j < 16; j++) { if (i+j < len) cout << hex << setw(2) << setfill('0') << (int)p[i+j] << \" \"; else cout << \"   \"; }",
                "        cout << \" | \";",
                "        for (size_t j = 0; j < 16 && (i+j) < len; j++) cout << (isprint(p[i+j]) ? (char)p[i+j] : '.');",
                "        cout << dec << endl;",
                "    }",
                "}"
            ])

        if helper_lines:
            lines.append("// --- nyx Standard Core Helpers ---")
            lines.extend(helper_lines)
            lines.append("")

        def cpp_type(t: Optional[TypeNode]) -> str:
            if not t: return "auto"
            if getattr(t, 'is_fn_type', False):
                args_s = ", ".join(cpp_type(a) for a in t.param_types)
                ret_s = cpp_type(t.return_type) if t.return_type else "void"
                return f"function<{ret_s}({args_s})>"
            name_map = {"int": "int64_t", "float": "double", "string": "string", "bool": "bool", "void": "void", "Array": "vector", "uintptr": "uintptr_t", "char": "char"}
            base = name_map.get(t.name, t.name)
            if t.generic_args:
                args = ", ".join(cpp_type(a) for a in t.generic_args)
                base = f"{base}<{args}>"
            if t.is_pointer:
                base = f"{base}*"
            if t.is_optional:
                base = f"optional<{base}>"
            return base

        def c_ffi_type(t: Optional[TypeNode]) -> str:
            if not t: return "auto"
            if getattr(t, 'is_fn_type', False):
                args_s = ", ".join(c_ffi_type(a) for a in t.param_types)
                ret_s = c_ffi_type(t.return_type) if t.return_type else "void"
                return f"{ret_s}(*)({args_s})"
            name_map = {
                "int": "int64_t", "int64": "int64_t", "i64": "int64_t", "int32": "int32_t", "i32": "int32_t",
                "size_t": "size_t", "float": "double", "double": "double", "string": "const char*",
                "bool": "bool", "void": "void", "uintptr": "uintptr_t", "char": "char"
            }
            base = name_map.get(t.name, t.name)
            if t.is_pointer:
                base = f"{base}*"
            return base

        # Extern C declarations (only emitted when needed, using standard C FFI signatures)
        KNOWN_CRT_FUNCS = {
            "getenv", "system", "exit", "_exit", "abort", "malloc", "calloc", "realloc", "free",
            "abs", "labs", "llabs", "puts", "putchar", "getchar", "printf", "scanf", "sprintf",
            "snprintf", "strlen", "wcslen", "sqrt", "pow", "sin", "cos", "tan", "memset", "memcpy",
            "memmove", "strcpy", "strncpy", "strcmp", "strncmp", "strcat", "strncat", "fopen",
            "fclose", "fread", "fwrite", "fseek", "ftell", "rewind", "clock", "time"
        }
        if extern_c_funcs:
            custom_externs = [ef for ef in extern_c_funcs.values() if ef.name not in KNOWN_CRT_FUNCS]
            if custom_externs:
                lines.append("// --- nyx Extern FFI Declarations ---")
                lines.append("extern \"C\" {")
                for ef in custom_externs:
                    ret = c_ffi_type(ef.return_type)
                    if ef.name in ("strlen", "wcslen", "fread", "fwrite") and ret in ("int", "int64_t"):
                        ret = "size_t"
                    params = []
                    for p in ef.params:
                        p_t = p.type_annot
                        if p_t and getattr(p_t, 'is_fn_type', False):
                            args_s = ", ".join(c_ffi_type(a) for a in p_t.param_types)
                            ret_s = c_ffi_type(p_t.return_type) if p_t.return_type else "void"
                            params.append(f"{ret_s}(*{p.name})({args_s})")
                        else:
                            t_str = c_ffi_type(p_t)
                            if p.name in ("size", "len", "length", "count") and t_str in ("int", "int64_t"):
                                t_str = "size_t"
                            params.append(f"{t_str} {p.name}")
                    if ef.is_varargs:
                        params.append("...")
                    lines.append(f"    {ret} {ef.name}({', '.join(params)});")
                lines.append("}\n")

        def emit_expr(node: ASTNode) -> str:
            if isinstance(node, NumberNode): return str(node.value)
            if isinstance(node, StringNode): return f"string({json.dumps(node.value, ensure_ascii=False)})"
            if isinstance(node, BooleanNode): return "true" if node.value else "false"
            if isinstance(node, NullNode): return "nullptr"
            if isinstance(node, IdentifierNode): return node.name
            if isinstance(node, BinaryOpNode):
                op_map = {"and": "&&", "or": "||"}
                op = op_map.get(node.op, node.op)
                return f"({emit_expr(node.left)} {op} {emit_expr(node.right)})"
            if isinstance(node, UnaryOpNode):
                op = "!" if node.op == "not" else node.op
                return f"({op}{emit_expr(node.expr)})"
            if isinstance(node, NullCoalesceNode):
                return f"({emit_expr(node.left)}.value_or({emit_expr(node.right)}))"
            if isinstance(node, MemberAccessNode):
                if isinstance(node.obj, IdentifierNode) and node.obj.name in ("self", "this"):
                    return f"this->{node.member}"
                return f"{emit_expr(node.obj)}.{node.member}"
            if isinstance(node, IndexAccessNode):
                return f"_nyx_at({emit_expr(node.obj)}, {emit_expr(node.index_expr)})"
            if isinstance(node, ArrayNode):
                if not node.elements:
                    return "{}"
                elems = ", ".join([emit_expr(e) for e in node.elements])
                return f"vector{{{elems}}}"
            if isinstance(node, FunctionCallNode):
                if node.callee == "print":
                    args_cpp = ' << " " << '.join([emit_expr(a) for a in node.args]) if node.args else '""'
                    return f"cout << {args_cpp} << endl"
                
                # Check if calling member access node: obj.method(args)
                if isinstance(node.callee, MemberAccessNode):
                    target_expr = emit_expr(node.callee.obj)
                    if target_expr in ("self", "this"):
                        args_cpp = ", ".join([emit_expr(a) for a in node.args])
                        return f"this->{node.callee.member}({args_cpp})"
                    if node.callee.member == "push":
                        return f"{target_expr}.push_back({emit_expr(node.args[0])})"
                    elif node.callee.member in ("len", "length", "size"):
                        return f"(int64_t){target_expr}.size()"
                    elif node.callee.member == "pop":
                        return f"{target_expr}.pop_back()"
                    else:
                        args_cpp = ", ".join([emit_expr(a) for a in node.args])
                        return f"{target_expr}.{node.callee.member}({args_cpp})"

                # Check if calling vector / collection / object methods as string
                if isinstance(node.callee, str) and "." in node.callee:
                    obj_part, method_part = node.callee.rsplit(".", 1)
                    if obj_part in ("self", "this"):
                        args_cpp = ", ".join([emit_expr(a) for a in node.args])
                        return f"this->{method_part}({args_cpp})"
                    if method_part == "push":
                        return f"{obj_part}.push_back({emit_expr(node.args[0])})"
                    elif method_part in ("len", "length", "size"):
                        return f"(int64_t){obj_part}.size()"
                    elif method_part == "pop":
                        return f"{obj_part}.pop_back()"
                    else:
                        args_cpp = ", ".join([emit_expr(a) for a in node.args])
                        return f"{obj_part}.{method_part}({args_cpp})"
                
                # Check if calling an extern C function
                if node.callee in extern_c_funcs:
                    ef = extern_c_funcs[node.callee]
                    args_list = []
                    for idx, a in enumerate(node.args):
                        a_expr = emit_expr(a)
                        if idx < len(ef.params):
                            p_type = ef.params[idx].type_annot.name if ef.params[idx].type_annot else ""
                            if p_type in ("string", "const *char", "*char") or isinstance(a, StringNode):
                                if isinstance(a, StringNode):
                                    a_expr = json.dumps(a.value, ensure_ascii=False)
                                elif not (a_expr.endswith(".c_str()") or a_expr.startswith('"')):
                                    a_expr = f"{a_expr}.c_str()"
                        args_list.append(a_expr)
                    return f"{node.callee}({', '.join(args_list)})"

                callee_name = "_nyx_user_main" if node.callee == "main" else node.callee
                args_cpp = ", ".join([emit_expr(a) for a in node.args])
                return f"{callee_name}({args_cpp})"
            if isinstance(node, LambdaNode):
                params_s = ", ".join([f"auto {p}" for p in node.params])
                return f"[=]({params_s}) {{ return {emit_expr(node.body)}; }}"
            return "/* expr */"

        declared_cpp_vars = set()

        def emit_stmt(node: ASTNode, indent: int = 1) -> List[str]:
            sp = "    " * indent
            res = []
            if isinstance(node, VarDeclNode):
                declared_cpp_vars.add(node.name)
                t_str = cpp_type(node.type_annot)
                const_prefix = "const " if node.is_const else ""
                res.append(f"{sp}{const_prefix}{t_str} {node.name} = {emit_expr(node.expr)};")
            elif isinstance(node, AssignNode):
                if isinstance(node.target, IdentifierNode) and node.target.name not in declared_cpp_vars:
                    declared_cpp_vars.add(node.target.name)
                    res.append(f"{sp}auto {node.target.name} = {emit_expr(node.expr)};")
                else:
                    res.append(f"{sp}{emit_expr(node.target)} = {emit_expr(node.expr)};")
            elif isinstance(node, TypeAliasNode):
                res.append(f"using {node.name} = {cpp_type(node.actual_type)};\n")
            elif isinstance(node, StructDefNode):
                gen_s = f"template<{', '.join('typename ' + g for g in node.generic_params)}>\n" if node.generic_params else ""
                def struct_field_type(f):
                    if f.type_annot: return cpp_type(f.type_annot)
                    fn_l = f.name.lower()
                    if any(w in fn_l for w in ("name", "text", "msg", "str", "title", "email")): return "string"
                    if any(w in fn_l for w in ("age", "id", "count", "num", "freq", "signal", "score", "total")): return "int64_t"
                    if any(w in fn_l for w in ("speed", "rate", "ratio", "pi")): return "double"
                    if any(w in fn_l for w in ("is_", "active", "flag", "enabled", "done")): return "bool"
                    return "string"
                fields_decls = ";\n    ".join([f"{struct_field_type(f)} {f.name}" for f in node.fields])
                ctor_params = ", ".join([f"{struct_field_type(f)} {f.name}" for f in node.fields])
                ctor_inits = ", ".join([f"{f.name}({f.name})" for f in node.fields])
                default_inits = ", ".join([f"{f.name}()" for f in node.fields])
                ctor_body = f"    {node.name}() : {default_inits} {{}}\n    {node.name}({ctor_params}) : {ctor_inits} {{}}\n" if node.fields else ""
                
                # Check for RAII destructor and methods declared in ImplBlockNode
                impl_methods_decls = []
                for imp in [s for s in self.ast.statements if isinstance(s, ImplBlockNode) and s.target_type == node.name]:
                    for m in imp.methods:
                        m_params = [p for p in m.params if p.name not in ("self", "this")]
                        m_params_s = ", ".join([f"{cpp_type(p.type_annot)} {p.name}" for p in m_params])
                        m_ret_t = cpp_type(m.return_type)
                        if m_ret_t == "auto": m_ret_t = "void"
                        impl_methods_decls.append(f"    {m_ret_t} {m.name}({m_params_s});")
                        if m.name in ("drop", "destroy", "cleanup", "dispose"):
                            impl_methods_decls.append(f"    ~{node.name}() {{ this->{m.name}(); }}")

                methods_block = "\n".join(impl_methods_decls)
                if methods_block:
                    methods_block = "\n" + methods_block
                res.append(f"{gen_s}struct {node.name} {{\n    {fields_decls};\n{ctor_body}{methods_block}\n}};\n")
            elif isinstance(node, TraitDefNode):
                methods = ";\n    virtual ".join([f"auto {m.name}() = 0" for m in node.methods])
                res.append(f"class {node.name} {{\npublic:\n    virtual {methods};\n}};\n")
            elif isinstance(node, ImplBlockNode):
                res.append(f"// Implementation for {node.target_type}")
                for m in node.methods:
                    gen_s = f"template<{', '.join('typename ' + g for g in m.generic_params)}>\n" if m.generic_params else ""
                    m_params = [p for p in m.params if p.name not in ("self", "this")]
                    params_s = ", ".join([f"{cpp_type(p.type_annot)} {p.name}" for p in m_params])
                    ret_t = cpp_type(m.return_type)
                    if ret_t == "auto": ret_t = "void"
                    res.append(f"{gen_s}{ret_t} {node.target_type}::{m.name}({params_s}) {{")
                    for s in m.body: res.extend(emit_stmt(s, indent + 1))
                    res.append("}\n")
            elif isinstance(node, EnumDefNode):
                members_s = ", ".join([f"{m[0]} = {emit_expr(m[1])}" if m[1] else m[0] for m in node.members])
                res.append(f"enum class {node.name} {{ {members_s} }};\n")
            elif isinstance(node, UnsafeBlockNode):
                res.append(f"{sp}// --- BEGIN UNSAFE BLOCK ---")
                for s in node.body: res.extend(emit_stmt(s, indent))
                res.append(f"{sp}// --- END UNSAFE BLOCK ---")
            elif isinstance(node, SpawnNode):
                res.append(f"{sp}thread([=]() {{")
                for s in node.body: res.extend(emit_stmt(s, indent + 1))
                res.append(f"{sp}}}).detach();")
            elif isinstance(node, TestBlockNode):
                res.append(f"{sp}// Test: {node.description}")
                for s in node.body: res.extend(emit_stmt(s, indent))
            elif isinstance(node, AssertNode):
                res.append(f"{sp}if (!({emit_expr(node.condition)})) {{ cerr << \"Assertion failed: {node.message or ''}\" << endl; exit(1); }}")
            elif isinstance(node, FunctionDefNode):
                gen_s = f"template<{', '.join('typename ' + g for g in node.generic_params)}>\n" if node.generic_params else ""
                params = ", ".join([f"{cpp_type(p.type_annot)} {p.name}" for p in node.params])
                ret_t = cpp_type(node.return_type)
                fn_name = "_nyx_user_main" if node.name == "main" else node.name
                res.append(f"{gen_s}{ret_t} {fn_name}({params}) {{")
                for s in node.body: res.extend(emit_stmt(s, indent + 1))
                res.append("}\n")
            elif isinstance(node, MatchNode):
                res.append(f"{sp}auto _match_val = {emit_expr(node.expr)};")
                for pat, stmt in node.cases:
                    if isinstance(pat, FunctionCallNode) and pat.callee in ("Ok", "Err"):
                        is_ok_target = "true" if pat.callee == "Ok" else "false"
                        var_payload = pat.args[0].name if (pat.args and isinstance(pat.args[0], IdentifierNode)) else "_payload"
                        res.append(f"{sp}if (_match_val.is_ok == {is_ok_target}) {{")
                        res.append(f"{sp}    auto {var_payload} = _match_val.{'value' if is_ok_target == 'true' else 'error'};")
                        res.extend(emit_stmt(stmt, indent + 1))
                        res.append(f"{sp}}}")
                    else:
                        res.append(f"{sp}if (_match_val == {emit_expr(pat)}) {{")
                        res.extend(emit_stmt(stmt, indent + 1))
                        res.append(f"{sp}}}")
            elif isinstance(node, TryCatchNode):
                res.append(f"{sp}try {{")
                for s in node.try_body: res.extend(emit_stmt(s, indent + 1))
                res.append(f"{sp}}} catch (const exception& {node.err_name}) {{")
                for s in node.catch_body: res.extend(emit_stmt(s, indent + 1))
                res.append(f"{sp}}}")
            elif isinstance(node, IfNode):
                res.append(f"{sp}if ({emit_expr(node.condition)}) {{")
                for s in node.then_branch: res.extend(emit_stmt(s, indent + 1))
                for cond, branch in node.elif_branches:
                    res.append(f"{sp}}} else if ({emit_expr(cond)}) {{")
                    for s in branch: res.extend(emit_stmt(s, indent + 1))
                if node.else_branch:
                    res.append(f"{sp}}} else {{")
                    for s in node.else_branch: res.extend(emit_stmt(s, indent + 1))
                res.append(f"{sp}}}")
            elif isinstance(node, WhileNode):
                res.append(f"{sp}while ({emit_expr(node.condition)}) {{")
                for s in node.body: res.extend(emit_stmt(s, indent + 1))
                res.append(f"{sp}}}")
            elif isinstance(node, ForNode):
                if node.collection_expr:
                    res.append(f"{sp}for (auto& {node.var_name} : {emit_expr(node.collection_expr)}) {{")
                else:
                    res.append(f"{sp}for (int64_t {node.var_name} = {emit_expr(node.start_expr)}; {node.var_name} <= (int64_t)({emit_expr(node.end_expr)}); {node.var_name}++) {{")
                for s in node.body: res.extend(emit_stmt(s, indent + 1))
                res.append(f"{sp}}}")
            elif isinstance(node, ReturnNode): res.append(f"{sp}return {emit_expr(node.expr) if node.expr else ''};")
            elif isinstance(node, BreakNode): res.append(f"{sp}break;")
            elif isinstance(node, ContinueNode): res.append(f"{sp}continue;")
            else: res.append(f"{sp}{emit_expr(node)};")
            return res

        # Forward declarations for functions with explicit return types
        fwd_decls = []
        for s in self.ast.statements:
            if isinstance(s, FunctionDefNode) and s.return_type is not None:
                gen_s = f"template<{', '.join('typename ' + g for g in s.generic_params)}>\n" if s.generic_params else ""
                params = ", ".join([f"{cpp_type(p.type_annot)} {p.name}" for p in s.params])
                ret_t = cpp_type(s.return_type)
                fn_name = "_nyx_user_main" if s.name == "main" else s.name
                fwd_decls.append(f"{gen_s}{ret_t} {fn_name}({params});")
        if fwd_decls:
            lines.extend(fwd_decls)
            lines.append("")

        top_levels = []
        main_stmts = []
        for s in self.ast.statements:
            if isinstance(s, (StructDefNode, TraitDefNode, ImplBlockNode, EnumDefNode, FunctionDefNode, TypeAliasNode)):
                top_levels.extend(emit_stmt(s, 0))
            elif isinstance(s, VarDeclNode) and (s.is_const or getattr(s, '_is_global', False)):
                top_levels.extend(emit_stmt(s, 0))
            else:
                main_stmts.extend(emit_stmt(s, 1))

        has_user_main = any(isinstance(s, FunctionDefNode) and s.name == "main" for s in self.ast.statements)
        if has_user_main and "_nyx_user_main();" not in "\n".join(main_stmts):
            main_stmts.append("    _nyx_user_main();")

        lines.extend(top_levels)
        lines.append("int main() {")
        lines.append("#ifdef _WIN32")
        lines.append("    SetConsoleOutputCP(65001);")
        lines.append("    SetConsoleCP(65001);")
        lines.append("#endif")
        lines.append("    cout << boolalpha;")
        lines.extend(main_stmts)
        lines.append("    return 0;")
        lines.append("}")
        return "\n".join(lines)

    # =====================================================
    # 2. WASM (WebAssembly Text) GENERATOR
    # =====================================================
    def gen_wasm(self) -> str:
        wat_lines = [
            ";; Auto-generated by Nyx (hewasm - WebAssembly)",
            "(module",
            '  (import "env" "print" (func $print (param i32)))',
            '  (memory (export "memory") 1)',
        ]
        for s in self.ast.statements:
            if isinstance(s, FunctionDefNode):
                params_wat = " ".join([f"(param ${p.name} i32)" for p in node.params]) if hasattr(s, 'params') else ""
                wat_lines.append(f'  (func (export "{s.name}") {params_wat} (result i32)')
                wat_lines.append("    i32.const 42")
                wat_lines.append("  )")
        wat_lines.append(")")
        return "\n".join(wat_lines)

    # =====================================================
    # 3. REACT (TSX) GENERATOR
    # =====================================================
    def gen_react(self) -> str:
        lines = [
            "// Auto-generated by nyx Reactive Systems Compiler (hereact - React 19 TSX)",
            "import React, { useState, useEffect } from 'react';",
            "",
            "export default function NyxApp() {",
            "  const [logs, setLogs] = useState<string[]>([]);"
        ]
        
        state_vars = []
        fn_names = []
        body_effects = []

        def emit_tsx_expr(expr):
            if isinstance(expr, NumberNode): return str(expr.value)
            if isinstance(expr, StringNode): return json.dumps(expr.value)
            if isinstance(expr, BooleanNode): return "true" if expr.value else "false"
            if isinstance(expr, IdentifierNode): return expr.name
            if isinstance(expr, BinaryOpNode):
                return f"({emit_tsx_expr(expr.left)} {expr.op} {emit_tsx_expr(expr.right)})"
            return "null"

        for s in self.ast.statements:
            if isinstance(s, VarDeclNode):
                state_vars.append(s.name)
                val_s = emit_tsx_expr(s.expr)
                setter = f"set{s.name[0].upper() + s.name[1:] if len(s.name) > 0 else 'Val'}"
                lines.append(f"  const [{s.name}, {setter}] = useState<any>({val_s});")
            elif isinstance(s, FunctionCallNode) and s.callee in ("print", "println"):
                args_s = ", ".join(json.dumps(a.value) if isinstance(a, (StringNode, NumberNode, BooleanNode)) else a.name if isinstance(a, IdentifierNode) else "null" for a in s.args)
                body_effects.append(f"    setLogs(prev => [...prev, String({args_s})]);")
                body_effects.append(f"    console.log({args_s});")
            elif isinstance(s, FunctionDefNode) and s.name != "main":
                fn_names.append(s.name)
                params_s = ", ".join(f"{p.name}: any" for p in s.params)
                lines.append(f"  const {s.name} = ({params_s}) => {{")
                for bs in s.body:
                    if isinstance(bs, AssignNode):
                        t_name = bs.target.name if isinstance(bs.target, IdentifierNode) else str(bs.target)
                        setter = f"set{t_name[0].upper() + t_name[1:] if len(t_name) > 0 else 'Val'}"
                        lines.append(f"    {setter}(prev => ({emit_tsx_expr(bs.expr)}));")
                        lines.append(f"    setLogs(prev => [...prev, `[Event] {s.name}() triggered -> {t_name} updated`]);")
                    elif isinstance(bs, FunctionCallNode) and bs.callee in ("print", "println"):
                        args_s = ", ".join(json.dumps(a.value) if isinstance(a, (StringNode, NumberNode, BooleanNode)) else a.name if isinstance(a, IdentifierNode) else "null" for a in bs.args)
                        lines.append(f"    setLogs(prev => [...prev, String({args_s})]);")
                    elif isinstance(bs, ReturnNode):
                        lines.append(f"    return {emit_tsx_expr(bs.expr)};")
                lines.append("  };")

        lines.append("")
        lines.append("  useEffect(() => {")
        lines.append("    setLogs(prev => [...prev, '[System] Nyx Reactive Component Initialized.']);")
        if body_effects:
            lines.extend(body_effects)
        lines.append("  }, []);")

        lines.extend([
            "",
            "  return (",
            "    <div style={{ padding: '32px 24px', background: '#05070a', color: '#00f0ff', fontFamily: 'JetBrains Mono, monospace', minHeight: '100vh' }}>",
            "      <header style={{ borderBottom: '1px solid #1e293b', paddingBottom: 16, marginBottom: 24, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>",
            "        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>",
            "          <span style={{ fontSize: 24 }}>⚡</span>",
            "          <div>",
            "            <h1 style={{ margin: 0, fontSize: 20, color: '#f8fafc', letterSpacing: '-0.025em' }}>nyx Reactive Application</h1>",
            "            <span style={{ fontSize: 12, color: '#64748b' }}>Target: React 19 (TSX) • High-Performance Virtual DOM</span>",
            "          </div>",
            "        </div>",
            "      </header>",
            "",
            "      <main style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 20 }}>"
        ])

        if state_vars:
            lines.append("        <section style={{ background: '#0c131d', padding: 20, borderRadius: 8, border: '1px solid #1e293b' }}>")
            lines.append("          <h3 style={{ color: '#38bdf8', marginTop: 0, marginBottom: 16, fontSize: 14 }}>📊 Reactive States</h3>")
            lines.append("          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>")
            for v in state_vars:
                lines.append(f"            <div style={{{{ display: 'flex', justifyContent: 'space-between', padding: '8px 12px', background: '#070b12', borderRadius: 4, border: '1px solid #1e293b' }}}}>")
                lines.append(f"              <span style={{{{ color: '#94a3b8' }}}}>{v}:</span>")
                lines.append(f"              <strong style={{{{ color: '#4ade80' }}}}>{{{v} !== undefined ? JSON.stringify({v}) : 'null'}}</strong>")
                lines.append("            </div>")
            lines.append("          </div>")
            lines.append("        </section>")

        if fn_names:
            lines.append("        <section style={{ background: '#0c131d', padding: 20, borderRadius: 8, border: '1px solid #1e293b' }}>")
            lines.append("          <h3 style={{ color: '#38bdf8', marginTop: 0, marginBottom: 16, fontSize: 14 }}>⚡ Interactive Actions</h3>")
            lines.append("          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 10 }}>")
            for f in fn_names:
                lines.append(f"            <button onClick={{() => {f}()}} style={{{{ background: '#0284c7', color: '#ffffff', border: 'none', padding: '10px 16px', borderRadius: 6, fontWeight: 600, cursor: 'pointer', fontFamily: 'inherit' }}}}>")
                lines.append(f"              Run {f}()")
                lines.append("            </button>")
            lines.append("          </div>")
            lines.append("        </section>")

        lines.extend([
            "        <section style={{ gridColumn: '1 / -1', background: '#0c131d', padding: 20, borderRadius: 8, border: '1px solid #1e293b' }}>",
            "          <h3 style={{ color: '#38bdf8', marginTop: 0, marginBottom: 12, fontSize: 14 }}>📜 Live Output Stream</h3>",
            "          <div style={{ background: '#020408', padding: 16, borderRadius: 6, maxHeight: 250, overflowY: 'auto', border: '1px solid #0f172a' }}>",
            "            {logs.map((log, idx) => (",
            "              <div key={idx} style={{ color: '#a5f3fc', fontSize: 13, lineHeight: 1.6 }}>&gt; {log}</div>",
            "            ))}",
            "          </div>",
            "        </section>",
            "      </main>",
            "    </div>",
            "  );",
            "}"
        ])
        return "\n".join(lines)

    # =====================================================
    # 4. PYTHON 3 GENERATOR
    # =====================================================
    def gen_python(self) -> str:
        lines = [
            "# Auto-generated by Nyx Compiler (hepy)",
            "import sys, os, math, time, ctypes, threading, queue",
            f"if r'{_root_dir}' not in sys.path: sys.path.insert(0, r'{_root_dir}')",
            "try:",
            "    from src.runtime import get_runtime_env",
            "    globals().update(get_runtime_env())",
            "except Exception:",
            "    def print_fn(*args): sys.stdout.write(' '.join(str(a) for a in args) + '\\n')",
            "    def to_string(v): return str(v)",
            "    def contains(s, sub): return str(sub) in str(s)",
            "    def Ok(v): return type('Result', (), {'is_ok': True, 'value': v, 'error': None})()",
            "    def Err(e): return type('Result', (), {'is_ok': False, 'value': None, 'error': e})()",
            ""
        ]

        def emit_py_expr(node: ASTNode) -> str:
            if isinstance(node, NumberNode): return str(node.value)
            if isinstance(node, StringNode): return repr(node.value)
            if isinstance(node, BooleanNode): return "True" if node.value else "False"
            if isinstance(node, NullNode): return "None"
            if isinstance(node, IdentifierNode): return node.name
            if isinstance(node, BinaryOpNode):
                if node.op == "|>":
                    return f"{emit_py_expr(node.right)}({emit_py_expr(node.left)})"
                if node.op == "/" and (getattr(node, 'inferred_type', None) == 'int' or (isinstance(node.left, NumberNode) and isinstance(node.left.value, int) and isinstance(node.right, NumberNode) and isinstance(node.right.value, int))):
                    return f"({emit_py_expr(node.left)} // {emit_py_expr(node.right)})"
                py_op_map = {"&&": "and", "||": "or"}
                py_op = py_op_map.get(node.op, node.op)
                return f"({emit_py_expr(node.left)} {py_op} {emit_py_expr(node.right)})"
            if isinstance(node, UnaryOpNode):
                op_s = "not " if node.op in ("!", "not") else node.op
                return f"({op_s}{emit_py_expr(node.expr)})"
            if isinstance(node, NullCoalesceNode):
                return f"({emit_py_expr(node.left)} if {emit_py_expr(node.left)} is not None else {emit_py_expr(node.right)})"
            if isinstance(node, MemberAccessNode):
                if node.is_safe:
                    return f"(getattr({emit_py_expr(node.obj)}, '{node.member}', None) if {emit_py_expr(node.obj)} is not None else None)"
                return f"{emit_py_expr(node.obj)}.{node.member}"
            if isinstance(node, IndexAccessNode):
                return f"{emit_py_expr(node.obj)}[{emit_py_expr(node.index_expr)}]"
            if isinstance(node, ArrayNode):
                elems = ", ".join([emit_py_expr(e) for e in node.elements])
                return f"[{elems}]"
            if isinstance(node, LambdaNode):
                p_str = ", ".join(node.params)
                return f"(lambda {p_str}: {emit_py_expr(node.body)})"
            if isinstance(node, FunctionCallNode):
                args = ", ".join([emit_py_expr(a) for a in node.args])
                return f"{node.callee}({args})"
            return "None"

        def emit_py_stmt(node: ASTNode, indent: int = 0) -> List[str]:
            sp = "    " * indent
            if isinstance(node, VarDeclNode):
                return [f"{sp}{node.name} = {emit_py_expr(node.expr)}"]
            if isinstance(node, AssignNode):
                return [f"{sp}{emit_py_expr(node.target)} = {emit_py_expr(node.expr)}"]
            if isinstance(node, TypeAliasNode):
                return [f"{sp}{node.name} = type('{node.name}', (), {{}})"]
            if isinstance(node, StructDefNode):
                fields = ", ".join([f.name for f in node.fields])
                res = [f"{sp}class {node.name}:"]
                res.append(f"{sp}    def __init__(self, {fields}):" if fields else f"{sp}    pass")
                for f in node.fields:
                    res.append(f"{sp}        self.{f.name} = {f.name}")
                return res
            if isinstance(node, EnumDefNode):
                res = [f"{sp}class {node.name}:"]
                for m in node.members:
                    v_str = emit_py_expr(m[1]) if m[1] else f'"{m[0]}"'
                    res.append(f"{sp}    {m[0]} = {v_str}")
                return res
            if isinstance(node, FunctionDefNode):
                prefix = "async def " if node.is_async else "def "
                params = ", ".join([p.name for p in node.params])
                res = [f"{sp}{prefix}{node.name}({params}):"]
                if not node.body: res.append(f"{sp}    pass")
                else:
                    for s in node.body: res.extend(emit_py_stmt(s, indent + 1))
                return res
            if isinstance(node, UnsafeBlockNode):
                res = [f"{sp}# --- Unsafe Block ---"]
                for s in node.body: res.extend(emit_py_stmt(s, indent))
                return res
            if isinstance(node, SpawnNode):
                res = [f"{sp}def _bg():"]
                for s in node.body: res.extend(emit_py_stmt(s, indent + 1))
                res.append(f"{sp}threading.Thread(target=_bg, daemon=True).start()")
                return res
            if isinstance(node, TestBlockNode):
                res = [f"{sp}# Test: {node.description}"]
                for s in node.body: res.extend(emit_py_stmt(s, indent))
                return res
            if isinstance(node, AssertNode):
                msg = f', "{node.message}"' if node.message else ''
                return [f"{sp}assert {emit_py_expr(node.condition)}{msg}"]
            if isinstance(node, MatchNode):
                res = [f"{sp}_val = {emit_py_expr(node.expr)}"]
                for i, (pat, stmt) in enumerate(node.cases):
                    kw = "if" if i == 0 else "elif"
                    is_wildcard = (isinstance(pat, StringNode) and pat.value == "_") or (isinstance(pat, IdentifierNode) and pat.name == "_")
                    if is_wildcard:
                        res.append(f"{sp}else:")
                        res.extend(emit_py_stmt(stmt, indent + 1))
                    elif isinstance(pat, FunctionCallNode) and pat.callee in ("Ok", "Err"):
                        is_ok_target = (pat.callee == "Ok")
                        var_payload = pat.args[0].name if (pat.args and isinstance(pat.args[0], IdentifierNode)) else "_payload"
                        res.append(f"{sp}{kw} isinstance(_val, Result) and _val.is_ok == {is_ok_target}:")
                        res.append(f"{sp}    {var_payload} = _val.value")
                        res.extend(emit_py_stmt(stmt, indent + 1))
                    else:
                        pat_s = emit_py_expr(pat)
                        res.append(f"{sp}{kw} _val == {pat_s}:")
                        res.extend(emit_py_stmt(stmt, indent + 1))
                return res
            if isinstance(node, TryCatchNode):
                res = [f"{sp}try:"]
                for s in node.try_body: res.extend(emit_py_stmt(s, indent + 1))
                res.append(f"{sp}except Exception as {node.err_name}:")
                for s in node.catch_body: res.extend(emit_py_stmt(s, indent + 1))
                return res
            if isinstance(node, IfNode):
                res = [f"{sp}if {emit_py_expr(node.condition)}:"]
                if not node.then_branch: res.append(f"{sp}    pass")
                else:
                    for s in node.then_branch: res.extend(emit_py_stmt(s, indent + 1))
                for cond, b in node.elif_branches:
                    res.append(f"{sp}elif {emit_py_expr(cond)}:")
                    if not b: res.append(f"{sp}    pass")
                    else:
                        for s in b: res.extend(emit_py_stmt(s, indent + 1))
                if node.else_branch is not None:
                    res.append(f"{sp}else:")
                    if not node.else_branch: res.append(f"{sp}    pass")
                    else:
                        for s in node.else_branch: res.extend(emit_py_stmt(s, indent + 1))
                return res
            if isinstance(node, WhileNode):
                res = [f"{sp}while {emit_py_expr(node.condition)}:"]
                if not node.body: res.append(f"{sp}    pass")
                else:
                    for s in node.body: res.extend(emit_py_stmt(s, indent + 1))
                return res
            if isinstance(node, ForNode):
                if node.collection_expr:
                    res = [f"{sp}for {node.var_name} in {emit_py_expr(node.collection_expr)}:"]
                else:
                    res = [f"{sp}for {node.var_name} in range({emit_py_expr(node.start_expr)}, {emit_py_expr(node.end_expr)} + 1):"]
                if not node.body: res.append(f"{sp}    pass")
                else:
                    for s in node.body: res.extend(emit_py_stmt(s, indent + 1))
                return res
            if isinstance(node, BreakNode): return [f"{sp}break"]
            if isinstance(node, ContinueNode): return [f"{sp}continue"]
            if isinstance(node, ReturnNode): return [f"{sp}return {emit_py_expr(node.expr) if node.expr else ''}"]
            return [f"{sp}{emit_py_expr(node)}"]

        for s in self.ast.statements:
            lines.extend(emit_py_stmt(s, 0))
        return "\n".join(lines)

    # =====================================================
    # 5. JAVASCRIPT (ES2022 / Node.js) GENERATOR
    # =====================================================
    def gen_js(self) -> str:
        lines = [
            "// Auto-generated by Nyx (hejs)",
            "// Target: JavaScript ES2022 / Node.js\n"
        ]
        
        # Runtime helper functions for JS target
        lines.append("""class Result {
    constructor(is_ok, val, err) {
        this.is_ok = is_ok;
        this.value = val;
        this.error = err;
    }
}
function Ok(val) { return new Result(true, val, null); }
function Err(e) { return new Result(false, null, e); }
function print(...args) { console.log(...args); }
function contains(haystack, needle) { return haystack && haystack.includes ? haystack.includes(needle) : false; }
function to_string(v) { return String(v); }
function to_int(v) { return parseInt(v, 10); }
function len(v) { return v ? v.length : 0; }
""")

        def emit_js_expr(node: Optional[ASTNode]) -> str:
            if not node: return "undefined"
            if isinstance(node, NumberNode): return str(node.value)
            if isinstance(node, StringNode): return repr(node.value)
            if isinstance(node, BooleanNode): return "true" if node.value else "false"
            if isinstance(node, NullNode): return "null"
            if isinstance(node, IdentifierNode): return node.name
            if isinstance(node, ArrayNode):
                return f"[{', '.join(emit_js_expr(e) for e in node.elements)}]"
            if isinstance(node, BinaryOpNode):
                op_map = {'and': '&&', 'or': '||', '&&': '&&', '||': '||', '==': '===', '!=': '!=='}
                op = op_map.get(node.op, node.op)
                return f"({emit_js_expr(node.left)} {op} {emit_js_expr(node.right)})"
            if isinstance(node, UnaryOpNode):
                op = '!' if node.op in ('!', 'not') else node.op
                return f"{op}({emit_js_expr(node.expr)})"
            if isinstance(node, NullCoalesceNode):
                return f"({emit_js_expr(node.left)} ?? {emit_js_expr(node.right)})"
            if isinstance(node, MemberAccessNode):
                nav = "?." if node.is_safe else "."
                return f"{emit_js_expr(node.obj)}{nav}{node.member}"
            if isinstance(node, IndexAccessNode):
                return f"{emit_js_expr(node.obj)}[{emit_js_expr(node.index_expr)}]"
            if isinstance(node, FunctionCallNode):
                args_s = ", ".join(emit_js_expr(a) for a in node.args)
                return f"{node.callee}({args_s})"
            return "undefined"

        def emit_js_stmt(node: Optional[ASTNode], indent: int = 0) -> List[str]:
            if not node: return []
            sp = "    " * indent
            
            if isinstance(node, VarDeclNode):
                kw = "const" if node.is_const else "let"
                val_s = emit_js_expr(node.expr)
                return [f"{sp}{kw} {node.name} = {val_s};"]
                
            if isinstance(node, AssignNode):
                return [f"{sp}{emit_js_expr(node.target)} = {emit_js_expr(node.expr)};"]

            if isinstance(node, FunctionDefNode):
                params_s = ", ".join(p.name for p in node.params)
                res = [f"{sp}function {node.name}({params_s}) {{"]
                if not node.body: res.append(f"{sp}    // empty body")
                else:
                    for s in node.body: res.extend(emit_js_stmt(s, indent + 1))
                res.append(f"{sp}}}\n")
                return res

            if isinstance(node, StructDefNode):
                fields_params = ", ".join(f.name for f in node.fields)
                res = [f"{sp}function {node.name}({fields_params}) {{", f"{sp}    if (!(this instanceof {node.name})) return new {node.name}({fields_params});"]
                for f in node.fields:
                    res.append(f"{sp}    this.{f.name} = {f.name};")
                res.append(f"{sp}}}\n")
                return res

            if isinstance(node, IfNode):
                res = [f"{sp}if ({emit_js_expr(node.condition)}) {{"]
                for s in node.then_branch: res.extend(emit_js_stmt(s, indent + 1))
                for cond, branch in node.elif_branches:
                    res.append(f"{sp}}} else if ({emit_js_expr(cond)}) {{")
                    for s in branch: res.extend(emit_js_stmt(s, indent + 1))
                if node.else_branch:
                    res.append(f"{sp}}} else {{")
                    for s in node.else_branch: res.extend(emit_js_stmt(s, indent + 1))
                res.append(f"{sp}}}")
                return res

            if isinstance(node, WhileNode):
                res = [f"{sp}while ({emit_js_expr(node.condition)}) {{"]
                for s in node.body: res.extend(emit_js_stmt(s, indent + 1))
                res.append(f"{sp}}}")
                return res

            if isinstance(node, ForNode):
                if node.collection_expr:
                    res = [f"{sp}for (const {node.var_name} of {emit_js_expr(node.collection_expr)}) {{"]
                else:
                    res = [f"{sp}for (let {node.var_name} = {emit_js_expr(node.start_expr)}; {node.var_name} <= {emit_js_expr(node.end_expr)}; {node.var_name}++) {{"]
                for s in node.body: res.extend(emit_js_stmt(s, indent + 1))
                res.append(f"{sp}}}")
                return res

            if isinstance(node, ReturnNode):
                val = f" {emit_js_expr(node.expr)}" if node.expr else ""
                return [f"{sp}return{val};"]
                
            if isinstance(node, BreakNode): return [f"{sp}break;"]
            if isinstance(node, ContinueNode): return [f"{sp}continue;"]

            if isinstance(node, TestBlockNode):
                res = [f"{sp}// Test: {node.description}"]
                for s in node.body: res.extend(emit_js_stmt(s, indent))
                return res

            if isinstance(node, AssertNode):
                msg = f', "{node.message}"' if node.message else ''
                return [f'{sp}if (!({emit_js_expr(node.condition)})) throw new Error("Assertion failed"{msg});']

            if isinstance(node, MatchNode):
                res = [f"{sp}const _val = {emit_js_expr(node.expr)};"]
                for i, (pat, stmt) in enumerate(node.cases):
                    kw = "if" if i == 0 else "else if"
                    is_wildcard = (isinstance(pat, StringNode) and pat.value == "_") or (isinstance(pat, IdentifierNode) and pat.name == "_")
                    if is_wildcard:
                        res.append(f"{sp}else {{")
                        res.extend(emit_js_stmt(stmt, indent + 1))
                        res.append(f"{sp}}}")
                    elif isinstance(pat, FunctionCallNode) and pat.callee in ("Ok", "Err"):
                        is_ok_target = "true" if pat.callee == "Ok" else "false"
                        var_payload = pat.args[0].name if (pat.args and isinstance(pat.args[0], IdentifierNode)) else "_payload"
                        res.append(f"{sp}{kw} (_val instanceof Result && _val.is_ok === {is_ok_target}) {{")
                        res.append(f"{sp}    const {var_payload} = _val.value;")
                        res.extend(emit_js_stmt(stmt, indent + 1))
                        res.append(f"{sp}}}")
                    else:
                        res.append(f"{sp}{kw} (_val === {emit_js_expr(pat)}) {{")
                        res.extend(emit_js_stmt(stmt, indent + 1))
                        res.append(f"{sp}}}")
                return res

            if isinstance(node, TryCatchNode):
                res = [f"{sp}try {{"]
                for s in node.try_body: res.extend(emit_js_stmt(s, indent + 1))
                res.append(f"{sp}}} catch ({node.err_name}) {{")
                for s in node.catch_body: res.extend(emit_js_stmt(s, indent + 1))
                res.append(f"{sp}}}")
                return res

            if isinstance(node, UnsafeBlockNode):
                res = [f"{sp}// --- Unsafe Block (JS Emulation) ---"]
                for s in node.body: res.extend(emit_js_stmt(s, indent))
                return res

            return [f"{sp}{emit_js_expr(node)};"]

        for s in self.ast.statements:
            lines.extend(emit_js_stmt(s, 0))

        return "\n".join(lines)

    # =====================================================
    # 6. RUST (hers - 2021 Edition) GENERATOR
    # =====================================================
    def gen_rust(self) -> str:
        header = [
            "// Auto-generated by Nyx (hers)",
            "// Target: Rust 2021 Edition (rustc)",
            "#![allow(unused_variables, dead_code, unused_mut, non_snake_case, unused_parens, unused_doc_comments)]\n",
            "fn contains(haystack: &str, needle: &str) -> bool { haystack.contains(needle) }",
            "fn to_string<T: std::fmt::Display>(v: T) -> String { v.to_string() }",
            "fn to_int(s: &str) -> i64 { s.parse::<i64>().unwrap_or(0) }",
            "fn len<T>(v: &[T]) -> i64 { v.len() as i64 }\n"
        ]

        def rust_type(t_annot: Optional[TypeNode]) -> str:
            if not t_annot: return "i64"
            m = {"int": "i64", "float": "f64", "string": "String", "bool": "bool", "void": "()"}
            name = t_annot.name
            base = m.get(name, name)
            if "Array<" in name:
                inner = name.replace("Array<", "").replace(">", "")
                base = f"Vec<{m.get(inner, inner)}>"
            if t_annot.is_optional:
                base = f"Option<{base}>"
            return base

        def emit_rs_expr(node: Optional[ASTNode]) -> str:
            if not node: return "()"
            if isinstance(node, NumberNode):
                return f"{node.value}_f64" if isinstance(node.value, float) else f"{node.value}_i64"
            if isinstance(node, StringNode):
                return f"{json.dumps(node.value, ensure_ascii=False)}.to_string()"
            if isinstance(node, BooleanNode):
                return "true" if node.value else "false"
            if isinstance(node, NullNode):
                return "None"
            if isinstance(node, IdentifierNode):
                return node.name
            if isinstance(node, ArrayNode):
                elems = ", ".join(emit_rs_expr(e) for e in node.elements)
                return f"vec![{elems}]"
            if isinstance(node, BinaryOpNode):
                is_str = getattr(node, 'inferred_type', None) == 'string' or isinstance(node.left, StringNode) or isinstance(node.right, StringNode) or getattr(node.left, 'inferred_type', None) == 'string' or getattr(node.right, 'inferred_type', None) == 'string'
                if not is_str and isinstance(node.left, BinaryOpNode) and (isinstance(node.left.left, StringNode) or isinstance(node.left.right, StringNode)):
                    is_str = True
                if node.op == "+" and is_str:
                    return f'format!("{{}}{{}}", {emit_rs_expr(node.left)}, {emit_rs_expr(node.right)})'
                if node.op == "+":
                    return f"({emit_rs_expr(node.left)} + {emit_rs_expr(node.right)})"
                op_map = {'and': '&&', 'or': '||', '&&': '&&', '||': '||', '==': '==', '!=': '!='}
                op = op_map.get(node.op, node.op)
                return f"({emit_rs_expr(node.left)} {op} {emit_rs_expr(node.right)})"
            if isinstance(node, UnaryOpNode):
                op = '!' if node.op in ('!', 'not') else node.op
                return f"{op}({emit_rs_expr(node.operand)})"
            if isinstance(node, NullCoalesceNode):
                return f"({emit_rs_expr(node.left)}.unwrap_or({emit_rs_expr(node.right)}))"
            if isinstance(node, MemberAccessNode):
                return f"{emit_rs_expr(node.obj)}.{node.member}"
            if isinstance(node, IndexAccessNode):
                return f"{emit_rs_expr(node.obj)}[{emit_rs_expr(node.index_expr)} as usize]"
            if isinstance(node, FunctionCallNode):
                if node.callee == "Ok":
                    arg = emit_rs_expr(node.args[0]) if node.args else "()"
                    return f"Ok::<_, String>({arg})"
                if node.callee == "Err":
                    arg = emit_rs_expr(node.args[0]) if node.args else 'String::from("Error")'
                    return f"Err::<i64, _>({arg})"
                if node.callee == "print":
                    fmt = " ".join(["{}"] * len(node.args))
                    args_s = ", ".join(emit_rs_expr(a) for a in node.args)
                    return f'println!("{fmt}", {args_s})' if args_s else 'println!()'
                if node.callee == "addr":
                    return f"(&{emit_rs_expr(node.args[0])} as *const _ as usize)"
                if node.callee == "peek":
                    return f"unsafe {{ *({emit_rs_expr(node.args[0])} as *const i64) }}"
                args_s = ", ".join(emit_rs_expr(a) for a in node.args)
                return f"{node.callee}({args_s})"
            return "()"

        def emit_rs_stmt(node: Optional[ASTNode], indent: int = 1) -> List[str]:
            if not node: return []
            sp = "    " * indent

            if isinstance(node, VarDeclNode):
                t_str = f": {rust_type(node.type_annot)}" if node.type_annot else ""
                val_s = emit_rs_expr(node.expr)
                return [f"{sp}let mut {node.name}{t_str} = {val_s};"]

            if isinstance(node, AssignNode):
                return [f"{sp}{emit_rs_expr(node.target)} = {emit_rs_expr(node.expr)};"]

            if isinstance(node, IfNode):
                res = [f"{sp}if {emit_rs_expr(node.condition)} {{"]
                for s in node.then_branch: res.extend(emit_rs_stmt(s, indent + 1))
                for cond, branch in node.elif_branches:
                    res.append(f"{sp}}} else if {emit_rs_expr(cond)} {{")
                    for s in branch: res.extend(emit_rs_stmt(s, indent + 1))
                if node.else_branch:
                    res.append(f"{sp}}} else {{")
                    for s in node.else_branch: res.extend(emit_rs_stmt(s, indent + 1))
                res.append(f"{sp}}}")
                return res

            if isinstance(node, WhileNode):
                res = [f"{sp}while {emit_rs_expr(node.condition)} {{"]
                for s in node.body: res.extend(emit_rs_stmt(s, indent + 1))
                res.append(f"{sp}}}")
                return res

            if isinstance(node, ForNode):
                if node.collection_expr:
                    res = [f"{sp}for {node.var_name} in ({emit_rs_expr(node.collection_expr)}).clone() {{"]
                else:
                    res = [f"{sp}for {node.var_name} in {emit_rs_expr(node.start_expr)}..={emit_rs_expr(node.end_expr)} {{"]
                for s in node.body: res.extend(emit_rs_stmt(s, indent + 1))
                res.append(f"{sp}}}")
                return res

            if isinstance(node, ReturnNode):
                val = f" {emit_rs_expr(node.expr)}" if node.expr else ""
                return [f"{sp}return{val};"]

            if isinstance(node, BreakNode): return [f"{sp}break;"]
            if isinstance(node, ContinueNode): return [f"{sp}continue;"]

            if isinstance(node, MatchNode):
                res = [f"{sp}match {emit_rs_expr(node.expr)} {{"]
                for pat, stmt in node.cases:
                    pat_s = "_" if (isinstance(pat, (StringNode, IdentifierNode)) and getattr(pat, 'value', getattr(pat, 'name', '')) == "_") else emit_rs_expr(pat)
                    if isinstance(pat, FunctionCallNode) and pat.callee in ("Ok", "Err"):
                        p_var = pat.args[0].name if (pat.args and isinstance(pat.args[0], IdentifierNode)) else "_v"
                        pat_s = f"{pat.callee}({p_var})"
                    res.append(f"{sp}    {pat_s} => {{")
                    res.extend(emit_rs_stmt(stmt, indent + 2))
                    res.append(f"{sp}    }}")
                res.append(f"{sp}}}")
                return res

            if isinstance(node, UnsafeBlockNode):
                res = [f"{sp}unsafe {{"]
                for s in node.body: res.extend(emit_rs_stmt(s, indent + 1))
                res.append(f"{sp}}}")
                return res

            expr_s = emit_rs_expr(node)
            return [f"{sp}{expr_s};"] if not expr_s.startswith("println!") else [f"{sp}{expr_s};"]

        # Top-level declarations vs Main Body
        top_decls = []
        main_stmts = []

        for s in self.ast.statements:
            if isinstance(s, StructDefNode):
                fields = ", ".join([f"pub {f.name}: {rust_type(f.type_annot)}" for f in s.fields])
                ctor_params = ", ".join([f"{f.name}: {rust_type(f.type_annot)}" for f in s.fields])
                ctor_inits = ", ".join([f.name for f in s.fields])
                top_decls.append(f"#[derive(Debug, Clone, PartialEq)]\npub struct {s.name} {{\n    {', '.join([f'pub {f.name}: {rust_type(f.type_annot)}' for f in s.fields])}\n}}\n")
                top_decls.append(f"impl {s.name} {{\n    pub fn new({ctor_params}) -> Self {{\n        Self {{ {ctor_inits} }}\n    }}\n}}\n")
                top_decls.append(f"#[allow(non_snake_case)]\npub fn {s.name}({ctor_params}) -> {s.name} {{\n    {s.name}::new({ctor_inits})\n}}\n")
            elif isinstance(s, FunctionDefNode):
                params_s = ", ".join([f"{p.name}: {rust_type(p.type_annot)}" for p in s.params])
                ret_s = f" -> {rust_type(s.return_type)}" if s.return_type else ""
                fn_lines = [f"pub fn {s.name}({params_s}){ret_s} {{"]
                for stmt in s.body:
                    fn_lines.extend(emit_rs_stmt(stmt, 1))
                fn_lines.append("}\n")
                top_decls.append("\n".join(fn_lines))
            else:
                main_stmts.append(s)

        out = []
        out.extend(header)
        out.extend(top_decls)
        out.append("fn main() {")
        for s in main_stmts:
            out.extend(emit_rs_stmt(s, 1))
        out.append("}\n")

        return "\n".join(out)
