"""ECMAScript 2022 / Node.js emission from verified Nyx HIR."""

from __future__ import annotations

import json
import re
from typing import Dict, List, Sequence

from src.ir.model import (
    IRAssign,
    IRArray,
    IRAssert,
    IRAwait,
    IRResultPropagate,
    IRBinary,
    IRBreak,
    IRCall,
    IRContinue,
    IRConditional,
    IRDefer,
    IREnum,
    IRExpr,
    IRExprStatement,
    IRExternFunction,
    IRForeignImport,
    IRFor,
    IRFunction,
    IRGuard,
    IRIf,
    IRImpl,
    IRIndexAccess,
    IRLambda,
    IRLiteral,
    IRMatch,
    IRMatchExpression,
    IRMemberAccess,
    IRModule,
    IRNativeDirective,
    IRNode,
    IRNullCoalesce,
    IRReference,
    IRReturn,
    IRSpawn,
    IRStatement,
    IRStruct,
    IRTestBlock,
    IRThrow,
    IRYield,
    IRTrait,
    IRTryCatch,
    IRTypeAlias,
    IRUnary,
    IRUnsafeBlock,
    IRVarDecl,
    IRWhile,
)
from src.ir.builtins import BUILTINS, INTRINSICS
from src.ir.types import FLOAT, IRType


class JavaScriptEmissionError(ValueError):
    """Raised when verified HIR has no faithful ES2022 representation."""


_IDENTIFIER_CHARS = re.compile(r"[^0-9A-Za-z_$]")
_RESERVED = frozenset(
    "await break case catch class const continue debugger default delete do else enum export "
    "extends false finally for function if implements import in instanceof interface let new "
    "null package private protected public return static super switch this throw true try "
    "typeof var void while with yield".split()
)


_JAVASCRIPT_RUNTIME = r'''// Auto-generated by Nyx Compiler (js HIR backend)
// Target: ECMAScript 2022 / Node.js
"use strict";

const _nyxFs = require("node:fs");
const _nyxChildProcess = require("node:child_process");

class Result {
    constructor(isOk, value) {
        this.is_ok = Boolean(isOk);
        this.value = value;
        this.error = this.is_ok ? null : value;
    }

    unwrap() {
        if (!this.is_ok) throw new Error(`Called unwrap on an Err: ${this.error}`);
        return this.value;
    }
}

class _NyxResultPropagation {
    constructor(error) { this.error = error; }
}

function _nyxPropagate(result) {
    if (!(result instanceof Result)) throw new TypeError("Nyx '?' operand is not a Result");
    if (!result.is_ok) throw new _NyxResultPropagation(result.error);
    return result.value;
}

class NyxEnumValue {
    constructor(enumName, variantName, payload) {
        this.enum_name = enumName;
        this.variant_name = variantName;
        this.payload = payload;
    }
}

function _nyxCloneValue(value, seen = new Map()) {
    if (value === null || typeof value !== "object") return value;
    if (seen.has(value)) return seen.get(value);
    const clone = Array.isArray(value) ? [] : Object.create(Object.getPrototypeOf(value));
    seen.set(value, clone);
    for (const key of Object.keys(value)) clone[key] = _nyxCloneValue(value[key], seen);
    return clone;
}

function _nyxStringLength(value) { return _nyxI64(BigInt(Array.from(value).length)); }
function _nyxStringIndex(value, index) { return Array.from(value)[Number(index)] ?? ""; }

function Ok(value) { return new Result(true, value); }
function Err(error) { return new Result(false, error); }
function _nyxMap(items, transform) { return items.map(transform); }
function _nyxFilter(items, predicate) { return items.filter(predicate); }
function _nyxFold(items, initial, reducer) { return items.reduce(reducer, initial); }
function _nyxI64(value) { return BigInt.asIntN(64, typeof value === "bigint" ? value : BigInt(value)); }
function _nyxI64Add(left, right) { return _nyxI64(left + right); }
function _nyxI64Sub(left, right) { return _nyxI64(left - right); }
function _nyxI64Mul(left, right) { return _nyxI64(left * right); }
function _nyxI64Neg(value) { return _nyxI64(-value); }
function _nyxI64Not(value) { return _nyxI64(~value); }
function _nyxI64And(left, right) { return _nyxI64(left & right); }
function _nyxI64Xor(left, right) { return _nyxI64(left ^ right); }
function _nyxI64Or(left, right) { return _nyxI64(left | right); }
function _nyxI64Shl(value, amount) { return _nyxI64(value << (amount & 63n)); }
function _nyxI64Shr(value, amount) { return _nyxI64(_nyxI64(value) >> (amount & 63n)); }
function _nyxIntDiv(left, right) {
    if (right === 0n) throw new RangeError("integer division by zero");
    return _nyxI64(left / right);
}
function _nyxIntMod(left, right) {
    if (right === 0n) throw new RangeError("integer division by zero");
    return _nyxI64(left % right);
}
function _nyxF64Div(left, right) { return left / right; }
function _nyxF64Mod(left, right) { return left % right; }
function _nyxNormalizeDecimal(text) {
    text = text.toLowerCase();
    if (text === "nan" || text === "infinity" || text === "-infinity") {
        return text.replace("infinity", "inf");
    }
    const negative = text.startsWith("-");
    if (text.startsWith("+") || text.startsWith("-")) text = text.slice(1);
    const parts = text.split("e");
    const mantissa = parts[0];
    const exponent = parts.length > 1 ? Number(parts[1]) : 0;
    const dot = mantissa.indexOf(".");
    let decimalPosition = (dot < 0 ? mantissa.length : dot) + exponent;
    let digits = mantissa.replace(".", "");
    let first = 0;
    while (first < digits.length && digits[first] === "0") first++;
    if (first === digits.length) return "0";
    decimalPosition -= first;
    digits = digits.slice(first).replace(/0+$/, "") || "0";
    let result;
    if (decimalPosition > -6 && decimalPosition <= 21) {
        if (decimalPosition <= 0) {
            result = "0." + "0".repeat(-decimalPosition) + digits;
        } else if (decimalPosition >= digits.length) {
            result = digits + "0".repeat(decimalPosition - digits.length);
        } else {
            result = digits.slice(0, decimalPosition) + "." + digits.slice(decimalPosition);
        }
    } else {
        result = digits[0] + (digits.length > 1 ? "." + digits.slice(1) : "");
        const scientificExponent = decimalPosition - 1;
        result += "e" + (scientificExponent >= 0 ? "+" : "") + String(scientificExponent);
    }
    return (negative ? "-" : "") + result;
}
function _nyxF64ToString(value) { return _nyxNormalizeDecimal(String(value)); }
function _nyxDisplay(value) {
    if (typeof value === "bigint") return value.toString();
    if (typeof value === "number") return _nyxF64ToString(value);
    return value;
}
function print(...args) { console.log(...args.map(_nyxDisplay)); }
function to_string(value) {
    return typeof value === "number" ? _nyxF64ToString(value) : String(value);
}
const to_str = to_string;
function to_int(value) {
    const text = String(value).trim();
    if (!/^[+-]?[0-9]+$/.test(text)) return 0n;
    try { return _nyxI64(BigInt(text)); } catch { return 0n; }
}
function _nyx_require_bool(value) {
    if (typeof value !== "boolean") throw new TypeError("Nyx condition must have type bool");
    return value;
}

function _nyx_destructure_check(value, minimum, message) {
    if (value.length < Number(minimum)) throw new Error(String(message));
    return value;
}

function _nyx_utf8_from_codepoint(value) {
    let codepoint = Number(value);
    if (!Number.isInteger(codepoint) || codepoint < 0 || codepoint > 0x10FFFF ||
        (codepoint >= 0xD800 && codepoint <= 0xDFFF)) {
        codepoint = 0xFFFD;
    }
    return String.fromCodePoint(codepoint);
}
function _nyx_bootstrap_read_file(path) {
    try { return _nyxFs.readFileSync(path, "utf8"); } catch { return ""; }
}
function _nyx_bootstrap_write_file(path, content) {
    try { _nyxFs.writeFileSync(path, content, "utf8"); return true; } catch { return false; }
}
function _nyx_bootstrap_file_exists(path) { return _nyxFs.existsSync(path); }
function _nyx_bootstrap_remove_file(path) {
    try { _nyxFs.unlinkSync(path); return true; } catch { return false; }
}
function _nyx_process_exit(code) { process.exit(Number(code)); }
let _nyxToolchainError = "";
function _nyx_toolchain_compile_cpp(source, output) {
    const candidates = [process.env.NYX_CXX, "clang++", "g++", "c++"].filter(Boolean);
    for (const compiler of candidates) {
        const result = _nyxChildProcess.spawnSync(
            compiler, ["-std=c++20", "-O2", source, "-o", output], { stdio: "inherit" }
        );
        if (result.error && result.error.code === "ENOENT") continue;
        const code = Number(result.status ?? 1);
        if (code === 0) { _nyxToolchainError = ""; return 0n; }
        _nyxToolchainError = `${compiler} exited with code ${code}`;
        return _nyxI64(BigInt(code));
    }
    _nyxToolchainError = "No C++20 compiler found (set NYX_CXX or install clang++/g++)";
    return 127n;
}
function _nyx_toolchain_last_error() { return _nyxToolchainError; }
function contains(value, part) { return String(value).includes(String(part)); }
function is_number(value) { return String(value).trim() !== "" && Number.isFinite(Number(value)); }
function len(value) {
    if (value == null) return 0n;
    return typeof value === "string" ? _nyxStringLength(value) : _nyxI64(BigInt(value.length));
}
function args() { return process.argv.slice(); }
function input(prompt = "") {
    if (prompt) process.stdout.write(String(prompt));
    if (input._lines === undefined) {
        input._lines = _nyxFs.readFileSync(0, "utf8").split(/\r?\n/);
    }
    return input._lines.shift() ?? "";
}

let _nyxAddress = 0n;
function addr(_value) { _nyxAddress = _nyxI64Add(_nyxAddress, 1n); return _nyxAddress; }
function peek(_address) { return 1337n; }
function memdump(address, _length = 16) {
    const rendered = Number(address).toString(16).toUpperCase().padStart(16, "0");
    print(`0x${rendered}: 48 6F 6C 79 45 61 73 79 4C 61 6E 67 20 54 69 74  | Nyx Tit`);
}
function delay_ms(milliseconds) {
    const deadline = Date.now() + Number(milliseconds);
    while (Date.now() < deadline) {}
}

class _NyxChannel {
    constructor() { this.values = []; }
    send(value) { this.values.push(value); }
    receive() {
        if (this.values.length === 0) throw new Error("receive from empty Nyx channel");
        return this.values.shift();
    }
}
function channel(..._typeArguments) { return new _NyxChannel(); }

function _nyxRunDefers(stack) {
    while (stack.length > 0) stack.pop()();
}

const _nyx_math_sin = Math.sin;
const _nyx_math_cos = Math.cos;
const _nyx_math_tan = Math.tan;
const _nyx_math_sqrt = Math.sqrt;
const _nyx_math_pow = Math.pow;
const _nyx_math_abs = Math.abs;
const _nyx_math_floor = Math.floor;
const _nyx_math_ceil = Math.ceil;
const _nyx_math_round = Math.round;
const _nyx_math_clamp = (value, low, high) => Math.min(Math.max(value, low), high);

const _nyx_time_now_ms = () => _nyxI64(BigInt(Date.now()));
const _nyx_time_now_us = () => _nyxI64(BigInt(Math.trunc(performance.now() * 1000)));
const _nyx_time_sleep_ms = delay_ms;

const _nyx_base64_encode = value => Buffer.from(value, "utf8").toString("base64");
const _nyx_base64_decode = value => Buffer.from(value, "base64").toString("utf8");
const _nyx_base64_decode_result = value => {
    if (typeof value !== "string" || value.length % 4 !== 0 || !/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(value)) return Err("invalid base64 encoding");
    try { return Ok(Buffer.from(value, "base64").toString("utf8")); }
    catch (error) { return Err(`invalid base64 encoding: ${error.message}`); }
};
const _nyx_hash_fnv1a_64_hex = value => {
    let hash = 0xcbf29ce484222325n;
    for (const byte of Buffer.from(value, "utf8")) {
        hash = BigInt.asUintN(64, (hash ^ BigInt(byte)) * 0x100000001b3n);
    }
    return hash.toString(16).padStart(16, "0");
};

const _nyx_fs_write_string = (path, content) => {
    try { _nyxFs.writeFileSync(path, content, "utf8"); return true; } catch { return false; }
};
const _nyx_fs_read_to_string = path => {
    try { return _nyxFs.readFileSync(path, "utf8"); } catch { return ""; }
};
const _nyx_fs_append_string = (path, content) => {
    try { _nyxFs.appendFileSync(path, content, "utf8"); return true; } catch { return false; }
};
const _nyx_fs_exists = path => {
    try { return _nyxFs.existsSync(path); } catch { return false; }
};
const _nyx_fs_remove_file = path => {
    try { _nyxFs.unlinkSync(path); return true; } catch { return false; }
};
const _nyx_fs_read_to_string_result = path => {
    try { return Ok(_nyxFs.readFileSync(path, "utf8")); }
    catch (error) { return Err(`cannot read file '${path}': ${error.message}`); }
};
const _nyx_fs_write_string_result = (path, content) => {
    try { _nyxFs.writeFileSync(path, content, "utf8"); return Ok(true); }
    catch (error) { return Err(`cannot write file '${path}': ${error.message}`); }
};
const _nyx_fs_append_string_result = (path, content) => {
    try { _nyxFs.appendFileSync(path, content, "utf8"); return Ok(true); }
    catch (error) { return Err(`cannot append file '${path}': ${error.message}`); }
};
const _nyx_fs_remove_file_result = path => {
    try { _nyxFs.unlinkSync(path); return Ok(true); }
    catch (error) { return Err(`cannot remove file '${path}': ${error.message}`); }
};

const _nyx_json_get_string = (document, key) => {
    const marker = `"${key}":`;
    let start = document.indexOf(marker);
    if (start < 0) return "";
    start += marker.length;
    while (start < document.length && (document[start] === " " || document[start] === "\t")) start++;
    if (document[start] !== '"') return "";
    start++;
    const end = document.indexOf('"', start);
    return end < 0 ? "" : document.slice(start, end);
};
const _nyx_json_get_int = (document, key) => {
    const marker = `"${key}":`;
    let start = document.indexOf(marker);
    if (start < 0) return 0n;
    start += marker.length;
    while (start < document.length && (document[start] === " " || document[start] === "\t")) start++;
    let end = start + (document[start] === "-" ? 1 : 0);
    while (end < document.length && /[0-9]/.test(document[end])) end++;
    return to_int(document.slice(start, end));
};
const _nyx_json_get_string_result = (document, key) => {
    const marker = `"${key}":`; let start = document.indexOf(marker);
    if (start < 0) return Err(`JSON field not found: ${key}`);
    start += marker.length; while (start < document.length && (document[start] === " " || document[start] === "\t")) start++;
    if (document[start] !== '"') return Err(`JSON field is not a string: ${key}`);
    const end = document.indexOf('"', start + 1);
    return end < 0 ? Err(`unterminated JSON string field: ${key}`) : Ok(document.slice(start + 1, end));
};
const _nyx_json_get_int_result = (document, key) => {
    const marker = `"${key}":`; let start = document.indexOf(marker);
    if (start < 0) return Err(`JSON field not found: ${key}`);
    start += marker.length; while (start < document.length && (document[start] === " " || document[start] === "\t")) start++;
    const match = document.slice(start).match(/^-?[0-9]+/);
    if (!match) return Err(`JSON field is not an integer: ${key}`);
    try { const value = BigInt(match[0]); if (value < -(1n << 63n) || value > (1n << 63n) - 1n) return Err(`JSON integer is out of range: ${key}`); return Ok(_nyxI64(value)); }
    catch { return Err(`JSON field is not an integer: ${key}`); }
};
'''


class HIRJavaScriptEmitter:
    """Emit either a standalone script or an importable ES2022 module from HIR."""

    def __init__(self, module: IRModule, esm: bool = False):
        self.module = module
        self.esm = esm
        self.symbol_names: Dict[str, str] = {}
        self.impls: Dict[str, List[IRImpl]] = {}
        self.functions = {
            item.symbol: item for item in module.items if isinstance(item, IRFunction)
        }
        self.structs = {
            item.name: item for item in module.items if isinstance(item, IRStruct)
        }
        self.methods = {}
        self.enum_variants = {
            f"enum::{item.name}::variant::{member.name}": (item, member)
            for item in module.items if isinstance(item, IREnum)
            for member in item.members if member.is_variant
        }
        self.current_return_type: IRType | None = None
        self.counter = 0
        for item in module.items:
            if isinstance(item, IRImpl):
                self.impls.setdefault(item.target_type, []).append(item)
                for method in item.methods:
                    self.methods[(item.target_type, method.name)] = method
        self._register_declarations()

    def emit(self) -> str:
        lines = []
        if self.esm:
            lines.extend((
                "import { createRequire as _nyxCreateRequire } from 'node:module';",
                "const require = _nyxCreateRequire(import.meta.url);",
                "",
            ))
        lines.extend(_JAVASCRIPT_RUNTIME.splitlines())
        lines.append("")
        for item in self.module.items:
            if isinstance(item, IRForeignImport):
                if item.ecosystem != "js":
                    raise JavaScriptEmissionError(
                        f"JavaScript target cannot consume '{item.ecosystem}' foreign import '{item.module}'"
                    )
                if self.esm:
                    lines.append(
                        f"import * as {self._symbol(item.symbol, item.alias)} from {self._string(item.module)};"
                    )
                else:
                    lines.append(
                        f"const {self._symbol(item.symbol, item.alias)} = require({self._string(item.module)});"
                    )
        if any(isinstance(item, IRForeignImport) for item in self.module.items):
            lines.append("")
        declarations: List[IRNode] = []
        statements: List[IRStatement] = []
        for item in self.module.items:
            if isinstance(item, IRStatement):
                statements.append(item)
            elif isinstance(item, (IRImpl, IRNativeDirective, IRForeignImport)):
                continue
            else:
                declarations.append(item)

        declaration_order = (
            IRTypeAlias,
            IREnum,
            IRTrait,
            IRStruct,
            IRExternFunction,
            IRFunction,
        )
        for declaration_type in declaration_order:
            for item in declarations:
                if isinstance(item, declaration_type):
                    lines.extend(self._emit_declaration(item))
                    lines.append("")
        unknown = [
            type(item).__name__
            for item in declarations
            if not isinstance(item, declaration_order)
        ]
        if unknown:
            raise JavaScriptEmissionError(f"Unsupported HIR declaration(s): {', '.join(unknown)}")

        if statements:
            lines.extend(self._emit_block(statements, 0, top_level=True))
            lines.append("")

        main = next(
            (item for item in self.module.items if isinstance(item, IRFunction) and item.name == "main"),
            None,
        )
        explicitly_called = any(
            isinstance(item, IRExprStatement)
            and isinstance(item.expr, IRCall)
            and item.expr.receiver is None
            and item.expr.callee == "main"
            for item in statements
        )
        if main is not None and not explicitly_called and not self.esm:
            call = f"{self._symbol(main.symbol, main.name)}()"
            if main.is_async:
                lines.append(f"{call}.catch(error => {{ console.error(error); process.exitCode = 1; }});")
            else:
                lines.append(f"{call};")
        if self.esm:
            exports = [
                self._symbol(item.symbol, item.name)
                for item in self.module.items
                if isinstance(item, IRFunction) and not item.name.startswith("_")
            ]
            if exports:
                lines.append("")
                lines.append(f"export {{ {', '.join(exports)} }};")
        return "\n".join(lines).rstrip() + "\n"

    def _register_declarations(self) -> None:
        for item in self.module.items:
            if isinstance(
                item,
                (IRFunction, IRStruct, IRTrait, IRTypeAlias, IREnum, IRExternFunction, IRVarDecl, IRForeignImport),
            ):
                preferred = item.alias if isinstance(item, IRForeignImport) else item.name
                self.symbol_names[item.symbol] = self._identifier(preferred)
            if isinstance(item, IREnum):
                for member in item.members:
                    if member.is_variant:
                        self.symbol_names[f"enum::{item.name}::variant::{member.name}"] = self._identifier(member.name)

    def _emit_declaration(self, node: IRNode) -> List[str]:
        if isinstance(node, IRTypeAlias):
            return [f"const {self._symbol(node.symbol, node.name)} = Object;"]
        if isinstance(node, IREnum):
            if any(member.is_variant for member in node.members):
                lines = [f"const {self._symbol(node.symbol, node.name)} = NyxEnumValue;"]
                for member in node.members:
                    if not member.is_variant:
                        raise JavaScriptEmissionError(
                            f"Payload enum '{node.name}' cannot mix discriminant member '{member.name}'"
                        )
                    params = [f"_nyxPayload{index}" for index in range(len(member.payload_types))]
                    constructor = self._symbol(
                        f"enum::{node.name}::variant::{member.name}", member.name
                    )
                    lines.append(
                        f"function {constructor}({', '.join(params)}) {{ return new NyxEnumValue("
                        f"{self._string(node.name)}, {self._string(member.name)}, [{', '.join(params)}]); }}"
                    )
                return lines
            members = []
            for member in node.members:
                value = self._expr(member.value) if member.value is not None else self._string(member.name)
                members.append(f"{self._identifier(member.name)}: {value}")
            return [
                f"const {self._symbol(node.symbol, node.name)} = Object.freeze({{{', '.join(members)}}});"
            ]
        if isinstance(node, IRTrait):
            lines = [f"class {self._symbol(node.symbol, node.name)} {{"]
            for method in node.methods:
                lines.extend(self._emit_method(method, 1, abstract=True))
            lines.append("}")
            return lines
        if isinstance(node, IRStruct):
            return self._emit_struct(node)
        if isinstance(node, IRExternFunction):
            parameters = [self._parameter_name(param.symbol, param.name) for param in node.params]
            if node.varargs:
                parameters.append("..._nyxVarargs")
            return [
                f"function {self._symbol(node.symbol, node.name)}({', '.join(parameters)}) {{",
                f"    throw new Error({self._string(f'extern {node.abi} function {node.name} is unavailable on js')});",
                "}",
            ]
        if isinstance(node, IRFunction):
            return self._emit_function(node, 0)
        raise JavaScriptEmissionError(f"Unsupported HIR declaration: {type(node).__name__}")

    def _emit_struct(self, node: IRStruct) -> List[str]:
        name = self._symbol(node.symbol, node.name)
        parameters = []
        for field in node.fields:
            field_name = self._identifier(field.name)
            if field.default is None:
                parameters.append(field_name)
            else:
                parameters.append(f"{field_name} = {self._expr_as(field.default, field.type)}")
        lines = [f"class {name} {{", f"    constructor({', '.join(parameters)}) {{"]
        for field in node.fields:
            field_name = self._identifier(field.name)
            lines.append(f"        this.{field_name} = {field_name};")
        lines.append("    }")
        for impl in self.impls.get(node.name, ()):
            for method in impl.methods:
                lines.extend(self._emit_method(method, 1))
        lines.append("}")
        return lines

    def _emit_method(self, node: IRFunction, indent: int, *, abstract: bool = False) -> List[str]:
        prefix = "    " * indent
        parameters = []
        for index, parameter in enumerate(node.params):
            if index == 0 and parameter.name in ("self", "this"):
                self.symbol_names[parameter.symbol] = "this"
                continue
            name = self._parameter_name(parameter.symbol, parameter.name)
            if parameter.default is not None:
                name += f" = {self._expr_as(parameter.default, parameter.type)}"
            parameters.append(name)
        async_prefix = "async " if node.is_async else ""
        lines = [f"{prefix}{async_prefix}{self._identifier(node.name)}({', '.join(parameters)}) {{"]
        previous_return = self.current_return_type
        self.current_return_type = node.return_type
        try:
            if abstract:
                lines.append(f"{prefix}    throw new Error({self._string('unimplemented trait method ' + node.name)});")
            else:
                lines.extend(self._emit_block(node.body, indent + 1))
        finally:
            self.current_return_type = previous_return
        lines.append(f"{prefix}}}")
        return lines

    def _emit_function(self, node: IRFunction, indent: int) -> List[str]:
        prefix = "    " * indent
        parameters = []
        for parameter in node.params:
            name = self._parameter_name(parameter.symbol, parameter.name)
            if parameter.default is not None:
                name += f" = {self._expr_as(parameter.default, parameter.type)}"
            parameters.append(name)
        generator = node.return_type.name == "Iterator"
        async_prefix = "async " if node.is_async else ""
        star = "*" if generator else ""
        lines = [
            f"{prefix}{async_prefix}function{star} {self._symbol(node.symbol, node.name)}({', '.join(parameters)}) {{"
        ]
        previous_return = self.current_return_type
        self.current_return_type = node.return_type
        try:
            if node.return_type.name == "Result" and len(node.return_type.arguments) == 2:
                caught = self._temporary("propagated")
                lines.append(f"{prefix}    try {{")
                lines.extend(self._emit_block(node.body, indent + 2))
                lines.append(f"{prefix}    }} catch ({caught}) {{")
                lines.append(
                    f"{prefix}        if ({caught} instanceof _NyxResultPropagation) "
                    f"return Err({caught}.error);"
                )
                lines.append(f"{prefix}        throw {caught};")
                lines.append(f"{prefix}    }}")
            else:
                lines.extend(self._emit_block(node.body, indent + 1))
        finally:
            self.current_return_type = previous_return
        lines.append(f"{prefix}}}")
        return lines

    def _emit_block(
        self,
        statements: Sequence[IRStatement],
        indent: int,
        *,
        top_level: bool = False,
    ) -> List[str]:
        prefix = "    " * indent
        if not statements:
            return [f"{prefix}// empty"]
        if any(isinstance(statement, IRDefer) for statement in statements):
            stack = self._temporary("defer")
            lines = [f"{prefix}const {stack} = [];", f"{prefix}try {{"]
            for statement in statements:
                if isinstance(statement, IRDefer):
                    lines.append(f"{prefix}    {stack}.push(() => {self._expr(statement.expr)});")
                else:
                    lines.extend(self._emit_statement(statement, indent + 1, top_level=top_level))
            lines.append(f"{prefix}}} finally {{")
            lines.append(f"{prefix}    _nyxRunDefers({stack});")
            lines.append(f"{prefix}}}")
            return lines
        lines: List[str] = []
        for statement in statements:
            lines.extend(self._emit_statement(statement, indent, top_level=top_level))
        return lines or [f"{prefix}// empty"]

    def _condition(self, node: IRExpr) -> str:
        rendered = self._expr(node)
        return f"_nyx_require_bool({rendered})" if node.type.is_unknown else rendered

    def _emit_statement(
        self,
        node: IRStatement,
        indent: int,
        *,
        top_level: bool = False,
    ) -> List[str]:
        prefix = "    " * indent
        if isinstance(node, IRVarDecl):
            keyword_text = "const" if node.is_const else ("var" if top_level and indent > 0 else "let")
            value = self._copy_value(self._expr_as(node.expr, node.type), node.type)
            return [
                f"{prefix}{keyword_text} {self._symbol(node.symbol, node.name)} = {value};"
            ]
        if isinstance(node, IRAssign):
            value = self._copy_value(self._expr_as(node.expr, node.target.type), node.target.type)
            return [
                f"{prefix}{self._expr(node.target)} = {value};"
            ]
        if isinstance(node, IRExprStatement):
            return [f"{prefix}{self._expr(node.expr)};"]
        if isinstance(node, IRReturn):
            return [
                f"{prefix}return;"
                if node.expr is None
                else f"{prefix}return {self._expr_as(node.expr, self.current_return_type)};"
            ]
        if isinstance(node, IRThrow):
            return [f"{prefix}throw new Error(to_string({self._expr(node.expr)}));"]
        if isinstance(node, IRYield):
            return [f"{prefix}yield {self._expr(node.expr)};"]
        if isinstance(node, IRIf):
            lines = [f"{prefix}if ({self._condition(node.condition)}) {{"]
            lines.extend(self._emit_block(node.then_branch, indent + 1))
            for condition, body in node.elif_branches:
                lines.append(f"{prefix}}} else if ({self._condition(condition)}) {{")
                lines.extend(self._emit_block(body, indent + 1))
            if node.else_branch is not None:
                lines.append(f"{prefix}}} else {{")
                lines.extend(self._emit_block(node.else_branch, indent + 1))
            lines.append(f"{prefix}}}")
            return lines
        if isinstance(node, IRWhile):
            lines = [f"{prefix}while ({self._condition(node.condition)}) {{"]
            lines.extend(self._emit_block(node.body, indent + 1))
            lines.append(f"{prefix}}}")
            return lines
        if isinstance(node, IRFor):
            variable = self._symbol(node.symbol, node.var_name)
            if node.collection_expr is not None:
                opening = f"for (const {variable} of {self._expr(node.collection_expr)}) {{"
            elif node.start_expr is not None and node.end_expr is not None:
                opening = (
                    f"for (let {variable} = {self._expr(node.start_expr)}; "
                    f"{variable} <= {self._expr(node.end_expr)}; {variable}++) {{"
                )
            else:
                raise JavaScriptEmissionError("HIR for-loop has neither a collection nor a range")
            lines = [f"{prefix}{opening}"]
            lines.extend(self._emit_block(node.body, indent + 1))
            lines.append(f"{prefix}}}")
            return lines
        if isinstance(node, IRBreak):
            return [f"{prefix}break;"]
        if isinstance(node, IRContinue):
            return [f"{prefix}continue;"]
        if isinstance(node, IRDefer):
            raise JavaScriptEmissionError("defer must be emitted by its lexical block")
        if isinstance(node, IRGuard):
            lines = [f"{prefix}if (!({self._condition(node.condition)})) {{"]
            lines.extend(self._emit_block(node.else_body, indent + 1))
            lines.append(f"{prefix}}}")
            return lines
        if isinstance(node, IRUnsafeBlock):
            lines = [f"{prefix}// unsafe boundary (host emulation)"]
            lines.extend(self._emit_block(node.body, indent))
            return lines
        if isinstance(node, IRSpawn):
            lines = [f"{prefix}queueMicrotask(() => {{"]
            lines.extend(self._emit_block(node.body, indent + 1))
            lines.append(f"{prefix}}});")
            return lines
        if isinstance(node, IRAssert):
            message = "Assertion failed" if node.message is None else f"Assertion failed: {node.message}"
            return [
                f"{prefix}if (!({self._condition(node.condition)})) throw new Error({self._string(message)});"
            ]
        if isinstance(node, IRMatch):
            return self._emit_match(node, indent)
        if isinstance(node, IRTryCatch):
            error_name = self._symbol(node.error_symbol, node.error_name)
            caught_name = self._temporary("caught")
            lines = [f"{prefix}try {{"]
            lines.extend(self._emit_block(node.try_body, indent + 1))
            lines.append(f"{prefix}}} catch ({caught_name}) {{")
            lines.append(
                f"{prefix}    const {error_name} = {caught_name} instanceof Error "
                f"? {caught_name}.message : String({caught_name});"
            )
            lines.extend(self._emit_block(node.catch_body, indent + 1))
            lines.append(f"{prefix}}}")
            return lines
        if isinstance(node, IRTestBlock):
            lines = [f"{prefix}// test: {node.description}"]
            lines.extend(self._emit_block(node.body, indent, top_level=top_level))
            return lines
        raise JavaScriptEmissionError(f"Unsupported HIR statement: {type(node).__name__}")

    def _emit_match(self, node: IRMatch, indent: int) -> List[str]:
        prefix = "    " * indent
        value = self._temporary("match")
        lines = [f"{prefix}const {value} = {self._expr(node.expr)};"]
        emitted_condition = False
        for case in node.cases:
            pattern = case.pattern
            wildcard = (
                isinstance(pattern, IRReference) and pattern.name == "_"
            ) or (
                isinstance(pattern, IRLiteral) and pattern.value == "_"
            )
            binding = isinstance(pattern, IRReference) and pattern.name != "_"
            payload = None
            variant = self.enum_variants.get(pattern.callee_symbol) if isinstance(pattern, IRCall) else None
            payload_bindings = []
            if variant is not None:
                enum_node, member = variant
                condition = (
                    f"{value} instanceof NyxEnumValue && "
                    f"{value}.enum_name === {self._string(enum_node.name)} && "
                    f"{value}.variant_name === {self._string(member.name)}"
                )
                for index, argument in enumerate(pattern.args):
                    if isinstance(argument, IRReference) and argument.name != "_":
                        payload_bindings.append(
                            f"{prefix}    const {self._symbol(argument.symbol, argument.name)} = "
                            f"{value}.payload[{index}];"
                        )
            elif isinstance(pattern, IRCall) and pattern.callee in ("Ok", "Err"):
                expected = "true" if pattern.callee == "Ok" else "false"
                condition = f"{value} instanceof Result && {value}.is_ok === {expected}"
                if pattern.args and isinstance(pattern.args[0], IRReference):
                    payload = self._symbol(pattern.args[0].symbol, pattern.args[0].name)
            elif wildcard or binding:
                condition = "true"
            elif isinstance(pattern, IRCall):
                raise JavaScriptEmissionError(
                    f"Unsupported constructor pattern '{pattern.callee}' on js"
                )
            else:
                condition = f"{value} === {self._expr(pattern)}"

            if (wildcard or binding) and emitted_condition:
                lines.append(f"{prefix}else {{")
            else:
                keyword_text = "if" if not emitted_condition else "else if"
                lines.append(f"{prefix}{keyword_text} ({condition}) {{")
            if binding:
                lines.append(f"{prefix}    const {self._symbol(pattern.symbol, pattern.name)} = {value};")
            if payload is not None:
                lines.append(f"{prefix}    const {payload} = {value}.value;")
            lines.extend(payload_bindings)
            lines.extend(self._emit_block(case.body, indent + 1))
            lines.append(f"{prefix}}}")
            emitted_condition = True
            if wildcard or binding:
                break
        return lines

    def _expr(self, node: IRExpr | None) -> str:
        if node is None:
            raise JavaScriptEmissionError("Missing HIR expression")
        if isinstance(node, IRLiteral):
            if node.value is None:
                return "null"
            if isinstance(node.value, bool):
                return "true" if node.value else "false"
            if isinstance(node.value, str):
                return self._string(node.value)
            if node.type.name == "int" and isinstance(node.value, int):
                return f"{node.value}n"
            return repr(node.value)
        if isinstance(node, IRReference):
            return self._symbol(node.symbol, node.name)
        if isinstance(node, IRBinary):
            comparison = node.op in ("==", "!=", "<", "<=", ">", ">=")
            promote_to_float = node.type.name == "float" or (
                comparison and (node.left.type.name == "float" or node.right.type.name == "float")
            )
            expected = FLOAT if promote_to_float else None
            left = self._expr_as(node.left, expected)
            right = self._expr_as(node.right, expected)
            integer_operators = {
                "+": "_nyxI64Add",
                "-": "_nyxI64Sub",
                "*": "_nyxI64Mul",
                "/": "_nyxIntDiv",
                "%": "_nyxIntMod",
                "&": "_nyxI64And",
                "^": "_nyxI64Xor",
                "|": "_nyxI64Or",
                "<<": "_nyxI64Shl",
                ">>": "_nyxI64Shr",
            }
            if node.type.name == "int" and node.op in integer_operators:
                return f"{integer_operators[node.op]}({left}, {right})"
            if node.type.name == "float" and node.op == "/":
                return f"_nyxF64Div({left}, {right})"
            if node.type.name == "float" and node.op == "%":
                return f"_nyxF64Mod({left}, {right})"
            operator = {
                "and": "&&",
                "or": "||",
                "==": "===",
                "!=": "!==",
            }.get(node.op, node.op)
            return f"({left} {operator} {right})"
        if isinstance(node, IRUnary):
            operator = "!" if node.op in ("!", "not") else node.op
            if node.type.name == "int":
                if node.op == "-":
                    return f"_nyxI64Neg({self._expr(node.expr)})"
                if node.op == "~":
                    return f"_nyxI64Not({self._expr(node.expr)})"
                if node.op == "+":
                    return self._expr(node.expr)
            operand = self._expr_as(node.expr, FLOAT if node.type.name == "float" else None)
            return f"({operator}{operand})"
        if isinstance(node, IRAwait):
            return f"(await {self._expr(node.expr)})"
        if isinstance(node, IRResultPropagate):
            return f"_nyxPropagate({self._expr(node.expr)})"
        if isinstance(node, IRCall):
            expected_types = self._call_parameter_types(node)
            args = ", ".join(
                self._copy_value(
                    self._expr_as(
                        argument,
                        expected_types[index] if index < len(expected_types) else None,
                    ),
                    expected_types[index] if index < len(expected_types) else argument.type,
                )
                for index, argument in enumerate(node.args)
            )
            if node.receiver is not None:
                receiver = self._expr(node.receiver)
                if not node.args and (
                    node.callee == "len" or (
                        node.callee in ("length", "size")
                        and node.receiver.type.name in ("string", "Array")
                    )
                ):
                    return f"len({receiver})"
                return f"{receiver}.{self._identifier(node.callee)}({args})"
            collection_builtins = {
                "map": "_nyxMap",
                "filter": "_nyxFilter",
                "fold": "_nyxFold",
            }
            if node.callee_symbol.startswith("builtin::") and node.callee in collection_builtins:
                callee = collection_builtins[node.callee]
            else:
                callee = self._symbol(node.callee_symbol, node.callee)
            if node.callee_symbol.startswith("type::struct::"):
                return f"new {callee}({args})"
            return f"{callee}({args})"
        if isinstance(node, IRMemberAccess):
            operator = "?." if node.safe else "."
            return f"{self._expr(node.obj)}{operator}{self._identifier(node.member)}"
        if isinstance(node, IRIndexAccess):
            if node.obj.type.name == "string":
                return f"_nyxStringIndex({self._expr(node.obj)}, {self._expr(node.index)})"
            return f"{self._expr(node.obj)}[Number({self._expr(node.index)})]"
        if isinstance(node, IRArray):
            element_type = node.type.arguments[0] if node.type.arguments else None
            return "[" + ", ".join(
                self._expr_as(element, element_type) for element in node.elements
            ) + "]"
        if isinstance(node, IRNullCoalesce):
            return f"({self._expr(node.left)} ?? {self._expr(node.right)})"
        if isinstance(node, IRConditional):
            return (
                f"({self._expr(node.condition)} ? "
                f"{self._expr_as(node.then_expr, node.type)} : "
                f"{self._expr_as(node.else_expr, node.type)})"
            )
        if isinstance(node, IRMatchExpression):
            temporary = self._temporary("match")
            rendered = self._expr_as(node.cases[-1].value, node.type)
            for case in reversed(node.cases[:-1]):
                rendered = (
                    f"({temporary} === {self._expr(case.pattern)} ? "
                    f"{self._expr_as(case.value, node.type)} : {rendered})"
                )
            return f"(({temporary}) => {rendered})({self._expr(node.subject)})"
        if isinstance(node, IRLambda):
            parameters = [self._parameter_name(param.symbol, param.name) for param in node.params]
            return f"(({', '.join(parameters)}) => {self._expr(node.body)})"
        raise JavaScriptEmissionError(f"Unsupported HIR expression: {type(node).__name__}")

    def _expr_as(self, node: IRExpr, expected: IRType | None) -> str:
        rendered = self._expr(node)
        if expected is not None and expected.name == "float" and node.type.name == "int":
            return f"Number({rendered})"
        return rendered

    def _copy_value(self, rendered: str, value_type: IRType | None) -> str:
        if value_type is None:
            return rendered
        if value_type.name == "Array" or value_type.name in self.structs:
            return f"_nyxCloneValue({rendered})"
        if value_type.name in ("Option", "Result") and any(
            argument.name == "Array" or argument.name in self.structs
            for argument in value_type.arguments
        ):
            return f"_nyxCloneValue({rendered})"
        return rendered

    def _call_parameter_types(self, node: IRCall) -> Sequence[IRType]:
        if node.receiver is not None:
            method = self.methods.get((node.receiver.type.name, node.callee))
            if method is None:
                return ()
            parameters = list(method.params)
            if parameters and parameters[0].name in ("self", "this"):
                parameters = parameters[1:]
            return tuple(parameter.type for parameter in parameters)

        if node.callee_symbol.startswith("type::struct::"):
            struct = self.structs.get(node.callee)
            return tuple(field.type for field in struct.fields) if struct is not None else ()

        function = self.functions.get(node.callee_symbol)
        if function is not None:
            return tuple(parameter.type for parameter in function.params)
        signature = BUILTINS.get(node.callee) or INTRINSICS.get(node.callee)
        return signature.parameters if signature is not None else ()

    def _parameter_name(self, symbol: str, preferred: str) -> str:
        if symbol not in self.symbol_names:
            self.symbol_names[symbol] = self._identifier(preferred)
        return self.symbol_names[symbol]

    def _symbol(self, symbol: str, preferred: str) -> str:
        if symbol == "pattern::_":
            return "_"
        if symbol not in self.symbol_names:
            self.symbol_names[symbol] = self._identifier(preferred)
        return self.symbol_names[symbol]

    def _temporary(self, purpose: str) -> str:
        self.counter += 1
        return f"_nyx_{purpose}_{self.counter}"

    @staticmethod
    def _identifier(name: str) -> str:
        clean = _IDENTIFIER_CHARS.sub("_", name)
        if not clean:
            clean = "_nyxValue"
        if clean[0].isdigit():
            clean = "_" + clean
        if clean in _RESERVED:
            clean += "_nyx"
        return clean

    @staticmethod
    def _string(value: str) -> str:
        return json.dumps(value, ensure_ascii=False)


def emit_javascript(module: IRModule, esm: bool = False) -> str:
    """Convenience entry point used by the public compiler API."""

    return HIRJavaScriptEmitter(module, esm=esm).emit()
