"""Python 3 source emission from verified Nyx HIR.

This backend deliberately has no dependency on parser AST classes.  Symbol
identities from HIR are used to preserve lexical shadowing even though Python
itself has function rather than block scope.
"""

from __future__ import annotations

import hashlib
import keyword
import re
from typing import Dict, List, Sequence

from src.ir.builtins import BUILTINS, INTRINSICS
from src.ir.model import (
    IRAssign,
    IRArray,
    IRAssert,
    IRAwait,
    IRBinary,
    IRBreak,
    IRCall,
    IRContinue,
    IRDefer,
    IREnum,
    IRExpr,
    IRExprStatement,
    IRExternFunction,
    IRFor,
    IRFunction,
    IRGuard,
    IRIf,
    IRImpl,
    IRIndexAccess,
    IRLambda,
    IRLiteral,
    IRMatch,
    IRMemberAccess,
    IRModule,
    IRNativeDirective,
    IRNode,
    IRNullCoalesce,
    IRReference,
    IRReturn,
    IRSpawn,
    IRStatement,
    IRStruct,
    IRTestBlock,
    IRThrow,
    IRTrait,
    IRTryCatch,
    IRTypeAlias,
    IRUnary,
    IRUnsafeBlock,
    IRVarDecl,
    IRWhile,
)
from src.ir.types import FLOAT, IRType


class PythonEmissionError(ValueError):
    """Raised when verified HIR has no faithful Python representation."""


_IDENTIFIER_CHARS = re.compile(r"[^0-9A-Za-z_]")


_PYTHON_RUNTIME = r'''# Auto-generated by Nyx Compiler (hepy HIR backend)
from __future__ import annotations

import base64 as _nyx_base64
import asyncio as _nyx_asyncio
import builtins as _nyx_builtins
import math as _nyx_math
import os as _nyx_os
import queue as _nyx_queue
import shutil as _nyx_shutil
import subprocess as _nyx_subprocess
import sys as _nyx_sys
import threading as _nyx_threading
import time as _nyx_time


if (getattr(_nyx_sys.stdout, "encoding", "") or "").lower().replace("-", "") != "utf8":
    try:
        _nyx_sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, OSError):
        pass


class Result:
    def __init__(self, is_ok, value):
        self.is_ok = bool(is_ok)
        self.value = value
        self.error = None if self.is_ok else value

    def unwrap(self):
        if not self.is_ok:
            raise RuntimeError(f"Called unwrap on an Err: {self.error}")
        return self.value

    def __repr__(self):
        name = "Ok" if self.is_ok else "Err"
        return f"{name}({self.value!r})"


class _NyxTask:
    """Reusable Nyx Task<T> facade over one asyncio Task."""

    def __init__(self, coroutine):
        self._coroutine = coroutine
        self._task = None
        try:
            loop = _nyx_asyncio.get_running_loop()
        except RuntimeError:
            return
        self._task = loop.create_task(coroutine)
        self._coroutine = None

    def _ensure_task(self):
        if self._task is None:
            loop = _nyx_asyncio.get_running_loop()
            self._task = loop.create_task(self._coroutine)
            self._coroutine = None
        return self._task

    def __await__(self):
        return self._ensure_task().__await__()


async def _nyx_run_task(task):
    return await task


def Ok(value):
    return Result(True, value)


def Err(error):
    return Result(False, error)


def _nyx_normalize_decimal(text):
    text = text.lower()
    if text in ("nan", "inf", "-inf"):
        return text
    negative = text.startswith("-")
    if text[:1] in ("+", "-"):
        text = text[1:]
    mantissa, marker, exponent_text = text.partition("e")
    exponent = int(exponent_text) if marker else 0
    dot = mantissa.find(".")
    decimal_position = (len(mantissa) if dot < 0 else dot) + exponent
    digits = mantissa.replace(".", "")
    first = 0
    while first < len(digits) and digits[first] == "0":
        first += 1
    if first == len(digits):
        return "0"
    decimal_position -= first
    digits = digits[first:].rstrip("0") or "0"
    if -6 < decimal_position <= 21:
        if decimal_position <= 0:
            result = "0." + ("0" * -decimal_position) + digits
        elif decimal_position >= len(digits):
            result = digits + ("0" * (decimal_position - len(digits)))
        else:
            result = digits[:decimal_position] + "." + digits[decimal_position:]
    else:
        result = digits[0]
        if len(digits) > 1:
            result += "." + digits[1:]
        scientific_exponent = decimal_position - 1
        result += "e" + ("+" if scientific_exponent >= 0 else "") + str(scientific_exponent)
    return ("-" if negative else "") + result


def _nyx_f64_to_string(value):
    if _nyx_math.isnan(value):
        return "nan"
    if _nyx_math.isinf(value):
        return "-inf" if value < 0.0 else "inf"
    return _nyx_normalize_decimal(repr(float(value)))


def _nyx_display(value):
    if isinstance(value, float):
        return _nyx_f64_to_string(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    return value


def print(*values):
    _nyx_builtins.print(*(_nyx_display(value) for value in values))


def to_string(value):
    if isinstance(value, float):
        return _nyx_f64_to_string(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


to_str = to_string


def to_int(value):
    try:
        return _nyx_i64(int(str(value).strip()))
    except (TypeError, ValueError):
        return 0


def _nyx_require_bool(value):
    if type(value) is not bool:
        raise TypeError("Nyx condition must have type bool")
    return value


_NYX_I64_MASK = (1 << 64) - 1
_NYX_I64_SIGN = 1 << 63


def _nyx_i64(value):
    bits = int(value) & _NYX_I64_MASK
    return bits - (1 << 64) if bits & _NYX_I64_SIGN else bits


def _nyx_i64_add(left, right):
    return _nyx_i64(left + right)


def _nyx_i64_sub(left, right):
    return _nyx_i64(left - right)


def _nyx_i64_mul(left, right):
    return _nyx_i64(left * right)


def _nyx_i64_neg(value):
    return _nyx_i64(-value)


def _nyx_i64_not(value):
    return _nyx_i64(~value)


def _nyx_i64_and(left, right):
    return _nyx_i64(left & right)


def _nyx_i64_xor(left, right):
    return _nyx_i64(left ^ right)


def _nyx_i64_or(left, right):
    return _nyx_i64(left | right)


def _nyx_i64_shl(value, amount):
    return _nyx_i64(value << (amount & 63))


def _nyx_i64_shr(value, amount):
    return _nyx_i64(_nyx_i64(value) >> (amount & 63))

def _nyx_utf8_from_codepoint(value):
    codepoint = int(value)
    if codepoint < 0 or codepoint > 0x10FFFF or 0xD800 <= codepoint <= 0xDFFF:
        codepoint = 0xFFFD
    return chr(codepoint)


def _nyx_bootstrap_read_file(path):
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return handle.read()
    except OSError:
        return ""


def _nyx_bootstrap_write_file(path, content):
    try:
        with open(path, "w", encoding="utf-8", newline="") as handle:
            handle.write(content)
        return True
    except OSError:
        return False


def _nyx_bootstrap_file_exists(path):
    return _nyx_os.path.isfile(path)


def _nyx_bootstrap_remove_file(path):
    try:
        _nyx_os.remove(path)
        return True
    except OSError:
        return False


def _nyx_process_exit(code):
    raise SystemExit(int(code))


_nyx_toolchain_error = ""


def _nyx_toolchain_compile_cpp(source, output):
    global _nyx_toolchain_error
    candidates = [_nyx_os.environ.get("NYX_CXX"), "clang++", "g++", "c++"]
    for compiler in candidates:
        if not compiler or (not _nyx_os.path.isabs(compiler) and not _nyx_shutil.which(compiler)):
            continue
        result = _nyx_subprocess.run(
            [compiler, "-std=c++20", "-O2", source, "-o", output], check=False
        )
        if result.returncode == 0:
            _nyx_toolchain_error = ""
            return 0
        _nyx_toolchain_error = f"{compiler} exited with code {result.returncode}"
        return result.returncode
    _nyx_toolchain_error = "No C++20 compiler found (set NYX_CXX or install clang++/g++)"
    return 127


def _nyx_toolchain_last_error():
    return _nyx_toolchain_error


def contains(value, part):
    return str(part) in str(value)


def is_number(value):
    try:
        float(str(value).strip())
        return True
    except (TypeError, ValueError):
        return False


def args():
    return list(_nyx_sys.argv)


def addr(value):
    return id(value)


def peek(_address):
    return 1337


def memdump(address, length=16):
    del length
    print(f"0x{address:016X}: 48 6F 6C 79 45 61 73 79 4C 61 6E 67 20 54 69 74  | Nyx Tit")


def delay_ms(milliseconds):
    _nyx_time.sleep(milliseconds / 1000.0)


class _NyxChannel:
    def __init__(self):
        self._queue = _nyx_queue.Queue()

    def send(self, value):
        self._queue.put(value)

    def receive(self):
        return self._queue.get()


def channel(*_type_arguments):
    return _NyxChannel()


def _nyx_safe_getattr(value, member):
    return None if value is None else getattr(value, member, None)


def _nyx_coalesce(value, fallback):
    return value if value is not None else fallback()


def _nyx_int_div(left, right):
    if right == 0:
        raise ZeroDivisionError("integer division by zero")
    quotient = abs(left) // abs(right)
    value = -quotient if (left < 0) != (right < 0) else quotient
    return _nyx_i64(value)


def _nyx_int_mod(left, right):
    if right == 0:
        raise ZeroDivisionError("integer division by zero")
    return _nyx_i64(left - _nyx_int_div(left, right) * right)


def _nyx_f64_div(left, right):
    left = float(left)
    right = float(right)
    if right != 0.0:
        return left / right
    if left == 0.0 or _nyx_math.isnan(left):
        return float("nan")
    negative = _nyx_math.copysign(1.0, left) != _nyx_math.copysign(1.0, right)
    return -float("inf") if negative else float("inf")


def _nyx_f64_mod(left, right):
    try:
        return _nyx_math.fmod(float(left), float(right))
    except ValueError:
        return float("nan")


class _NyxDeferScope:
    def __init__(self):
        self._callbacks = []

    def __enter__(self):
        return self

    def push(self, callback):
        self._callbacks.append(callback)

    def __exit__(self, exc_type, exc, traceback):
        del exc_type, exc, traceback
        while self._callbacks:
            self._callbacks.pop()()
        return False


_nyx_math_sin = _nyx_math.sin
_nyx_math_cos = _nyx_math.cos
_nyx_math_tan = _nyx_math.tan
_nyx_math_sqrt = _nyx_math.sqrt
_nyx_math_pow = _nyx_math.pow
_nyx_math_abs = abs
_nyx_math_floor = _nyx_math.floor
_nyx_math_ceil = _nyx_math.ceil
_nyx_math_round = round
_nyx_math_clamp = lambda value, low, high: max(low, min(high, value))

_nyx_time_now_ms = lambda: _nyx_i64(int(_nyx_time.time() * 1_000))
_nyx_time_now_us = lambda: _nyx_i64(int(_nyx_time.time() * 1_000_000))
_nyx_time_sleep_ms = lambda milliseconds: _nyx_time.sleep(milliseconds / 1_000.0)

_nyx_base64_encode = lambda value: _nyx_base64.b64encode(value.encode("utf-8")).decode("ascii")
_nyx_base64_decode = lambda value: _nyx_base64.b64decode(value.encode("ascii")).decode("utf-8")


def _nyx_hash_fnv1a_64_hex(value):
    result = 0xCBF29CE484222325
    for byte in value.encode("utf-8"):
        result = ((result ^ byte) * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return f"{result:016x}"


def _nyx_fs_read_to_string(path):
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return handle.read()
    except OSError:
        return ""


def _nyx_fs_write_string(path, content):
    try:
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(content)
        return True
    except OSError:
        return False


def _nyx_fs_append_string(path, content):
    try:
        with open(path, "a", encoding="utf-8") as handle:
            handle.write(content)
        return True
    except OSError:
        return False


def _nyx_fs_exists(path):
    return _nyx_os.path.exists(path)


def _nyx_fs_remove_file(path):
    try:
        _nyx_os.remove(path)
        return True
    except OSError:
        return False


def _nyx_json_get_string(document, key):
    marker = f'"{key}":'
    start = document.find(marker)
    if start < 0:
        return ""
    start += len(marker)
    while start < len(document) and document[start] in " \t":
        start += 1
    if start >= len(document) or document[start] != '"':
        return ""
    start += 1
    end = document.find('"', start)
    return "" if end < 0 else document[start:end]


def _nyx_json_get_int(document, key):
    marker = f'"{key}":'
    start = document.find(marker)
    if start < 0:
        return 0
    start += len(marker)
    while start < len(document) and document[start] in " \t":
        start += 1
    end = start + (1 if start < len(document) and document[start] == "-" else 0)
    while end < len(document) and document[end].isdigit():
        end += 1
    try:
        return _nyx_i64(int(document[start:end]))
    except ValueError:
        return 0
'''


class HIRPythonEmitter:
    """Emit standalone Python 3 source from an immutable HIR module."""

    def __init__(self, module: IRModule):
        self.module = module
        self.symbol_names: Dict[str, str] = {}
        self.public_symbols = {
            item.symbol
            for item in module.items
            if isinstance(item, IRVarDecl)
        }
        self.impls: Dict[str, List[IRImpl]] = {}
        self.functions = {
            item.symbol: item for item in module.items if isinstance(item, IRFunction)
        }
        self.structs = {
            item.name: item for item in module.items if isinstance(item, IRStruct)
        }
        self.methods = {}
        self.current_return_type: IRType | None = None
        self.counter = 0
        for item in module.items:
            if isinstance(item, IRImpl):
                self.impls.setdefault(item.target_type, []).append(item)
                for method in item.methods:
                    self.methods[(item.target_type, method.name)] = method
        self._register_declarations()

    def emit(self) -> str:
        lines = _PYTHON_RUNTIME.splitlines()
        lines.append("")

        declarations: List[IRNode] = []
        statements: List[IRStatement] = []
        for item in self.module.items:
            if isinstance(item, IRStatement):
                statements.append(item)
            elif isinstance(item, (IRImpl, IRNativeDirective)):
                continue
            else:
                declarations.append(item)

        declaration_order = (
            IRTypeAlias,
            IREnum,
            IRTrait,
            IRStruct,
            IRExternFunction,
            IRFunction,
        )
        for declaration_type in declaration_order:
            for item in declarations:
                if isinstance(item, declaration_type):
                    lines.extend(self._emit_declaration(item))
                    lines.append("")

        unknown = [
            type(item).__name__
            for item in declarations
            if not isinstance(item, declaration_order)
        ]
        if unknown:
            raise PythonEmissionError(f"Unsupported HIR declaration(s): {', '.join(unknown)}")

        if statements:
            lines.extend(self._emit_block(statements, 0))
            lines.append("")

        main = next(
            (item for item in self.module.items if isinstance(item, IRFunction) and item.name == "main"),
            None,
        )
        explicitly_called = any(
            isinstance(item, IRExprStatement)
            and isinstance(item.expr, IRCall)
            and item.expr.receiver is None
            and item.expr.callee == "main"
            for item in statements
        )
        if main is not None and not explicitly_called:
            lines.append("if __name__ == \"__main__\":")
            if main.is_async:
                lines.append(
                    f"    _nyx_asyncio.run(_nyx_run_task({self._symbol(main.symbol, main.name)}()))"
                )
            else:
                lines.append(f"    {self._symbol(main.symbol, main.name)}()")

        return "\n".join(lines).rstrip() + "\n"

    def _register_declarations(self) -> None:
        for item in self.module.items:
            if isinstance(
                item,
                (IRFunction, IRStruct, IRTrait, IRTypeAlias, IREnum, IRExternFunction),
            ):
                self.symbol_names[item.symbol] = self._identifier(item.name)
            elif isinstance(item, IRVarDecl):
                self.symbol_names[item.symbol] = self._identifier(item.name)

    def _emit_declaration(self, node: IRNode) -> List[str]:
        if isinstance(node, IRTypeAlias):
            return [f"{self._symbol(node.symbol, node.name)} = {self._type_name(node.actual_type)}"]
        if isinstance(node, IREnum):
            name = self._symbol(node.symbol, node.name)
            lines = [f"class {name}:"]
            if not node.members:
                lines.append("    pass")
            for member in node.members:
                value = self._expr(member.value) if member.value is not None else repr(member.name)
                lines.append(f"    {self._identifier(member.name)} = {value}")
            return lines
        if isinstance(node, IRTrait):
            lines = [f"class {self._symbol(node.symbol, node.name)}:"]
            if not node.methods:
                lines.append("    pass")
            for method in node.methods:
                lines.extend(self._emit_function(method, 1, method=True, abstract=True))
            return lines
        if isinstance(node, IRStruct):
            return self._emit_struct(node)
        if isinstance(node, IRExternFunction):
            parameters = [self._parameter_name(param.symbol, param.name) for param in node.params]
            if node.varargs:
                parameters.append("*_nyx_varargs")
            lines = [f"def {self._symbol(node.symbol, node.name)}({', '.join(parameters)}):"]
            lines.append(
                f"    raise RuntimeError({repr(f'extern {node.abi} function {node.name} is unavailable on hepy')})"
            )
            return lines
        if isinstance(node, IRFunction):
            return self._emit_function(node, 0)
        raise PythonEmissionError(f"Unsupported HIR declaration: {type(node).__name__}")

    def _emit_struct(self, node: IRStruct) -> List[str]:
        name = self._symbol(node.symbol, node.name)
        lines = [f"class {name}:"]
        fields = []
        for field in node.fields:
            field_name = self._identifier(field.name)
            if field.default is None:
                fields.append(field_name)
            else:
                fields.append(f"{field_name}={self._expr_as(field.default, field.type)}")
        methods = [method for impl in self.impls.get(node.name, ()) for method in impl.methods]
        if fields:
            lines.append(f"    def __init__(self, {', '.join(fields)}):")
            for field in node.fields:
                field_name = self._identifier(field.name)
                lines.append(f"        self.{field_name} = {field_name}")
        elif not methods:
            lines.append("    pass")
        else:
            lines.append("    def __init__(self):")
            lines.append("        pass")
        for method in methods:
            lines.extend(self._emit_function(method, 1, method=True))
        return lines

    def _emit_function(
        self,
        node: IRFunction,
        indent: int,
        *,
        method: bool = False,
        abstract: bool = False,
    ) -> List[str]:
        prefix = "    " * indent
        parameters: List[str] = []
        plain_parameters: List[str] = []
        call_arguments: List[str] = []
        for index, parameter in enumerate(node.params):
            if method and index == 0 and parameter.name in ("self", "this"):
                name = "self"
                self.symbol_names[parameter.symbol] = name
            else:
                name = self._parameter_name(parameter.symbol, parameter.name)
            plain_parameters.append(name)
            if not (method and index == 0 and parameter.name in ("self", "this")):
                call_arguments.append(name)
            if parameter.default is not None:
                name += f"={self._expr_as(parameter.default, parameter.type)}"
            parameters.append(name)
        public_name = self._identifier(node.name)
        if node.is_async:
            implementation_name = f"_nyx_async_impl_{public_name}"
            lines = [
                f"{prefix}async def {implementation_name}({', '.join(plain_parameters)}):"
            ]
        else:
            lines = [f"{prefix}def {public_name}({', '.join(parameters)}):"]
        if node.doc_comment:
            lines.append(f"{prefix}    {repr(node.doc_comment)}")
        previous_return = self.current_return_type
        self.current_return_type = node.return_type
        try:
            if abstract:
                lines.append(f"{prefix}    raise NotImplementedError({repr(node.name)})")
            else:
                lines.extend(self._emit_block(node.body, indent + 1))
        finally:
            self.current_return_type = previous_return
        if node.is_async:
            lines.append(f"{prefix}def {public_name}({', '.join(parameters)}):")
            if node.doc_comment:
                lines.append(f"{prefix}    {repr(node.doc_comment)}")
            callee = f"self.{implementation_name}" if method else implementation_name
            lines.append(
                f"{prefix}    return _NyxTask({callee}({', '.join(call_arguments)}))"
            )
        return lines

    def _emit_block(self, statements: Sequence[IRStatement], indent: int) -> List[str]:
        prefix = "    " * indent
        if not statements:
            return [f"{prefix}pass"]
        if any(isinstance(statement, IRDefer) for statement in statements):
            scope = self._temporary("defer")
            lines = [f"{prefix}with _NyxDeferScope() as {scope}:"]
            for statement in statements:
                if isinstance(statement, IRDefer):
                    lines.append(f"{prefix}    {scope}.push(lambda: {self._expr(statement.expr)})")
                else:
                    lines.extend(self._emit_statement(statement, indent + 1))
            return lines
        lines: List[str] = []
        for statement in statements:
            lines.extend(self._emit_statement(statement, indent))
        return lines or [f"{prefix}pass"]

    def _condition(self, node: IRExpr) -> str:
        rendered = self._expr(node)
        return f"_nyx_require_bool({rendered})" if node.type.is_unknown else rendered

    def _emit_statement(self, node: IRStatement, indent: int) -> List[str]:
        prefix = "    " * indent
        if isinstance(node, IRVarDecl):
            name = self._symbol(node.symbol, node.name)
            return [f"{prefix}{name} = {self._expr_as(node.expr, node.type)}"]
        if isinstance(node, IRAssign):
            return [
                f"{prefix}{self._expr(node.target)} = {self._expr_as(node.expr, node.target.type)}"
            ]
        if isinstance(node, IRExprStatement):
            return [f"{prefix}{self._expr(node.expr)}"]
        if isinstance(node, IRReturn):
            return [
                f"{prefix}return"
                if node.expr is None
                else f"{prefix}return {self._expr_as(node.expr, self.current_return_type)}"
            ]
        if isinstance(node, IRThrow):
            return [f"{prefix}raise RuntimeError(to_string({self._expr(node.expr)}))"]
        if isinstance(node, IRIf):
            lines = [f"{prefix}if {self._condition(node.condition)}:"]
            lines.extend(self._emit_block(node.then_branch, indent + 1))
            for condition, body in node.elif_branches:
                lines.append(f"{prefix}elif {self._condition(condition)}:")
                lines.extend(self._emit_block(body, indent + 1))
            if node.else_branch is not None:
                lines.append(f"{prefix}else:")
                lines.extend(self._emit_block(node.else_branch, indent + 1))
            return lines
        if isinstance(node, IRWhile):
            lines = [f"{prefix}while {self._condition(node.condition)}:"]
            lines.extend(self._emit_block(node.body, indent + 1))
            return lines
        if isinstance(node, IRFor):
            variable = self._symbol(node.symbol, node.var_name)
            if node.collection_expr is not None:
                iterator = self._expr(node.collection_expr)
            elif node.start_expr is not None and node.end_expr is not None:
                iterator = f"range({self._expr(node.start_expr)}, {self._expr(node.end_expr)} + 1)"
            else:
                raise PythonEmissionError("HIR for-loop has neither a collection nor a range")
            lines = [f"{prefix}for {variable} in {iterator}:"]
            lines.extend(self._emit_block(node.body, indent + 1))
            return lines
        if isinstance(node, IRBreak):
            return [f"{prefix}break"]
        if isinstance(node, IRContinue):
            return [f"{prefix}continue"]
        if isinstance(node, IRDefer):
            raise PythonEmissionError("defer must be emitted by its lexical block")
        if isinstance(node, IRGuard):
            lines = [f"{prefix}if not ({self._condition(node.condition)}):"]
            lines.extend(self._emit_block(node.else_body, indent + 1))
            return lines
        if isinstance(node, IRUnsafeBlock):
            lines = [f"{prefix}# unsafe boundary"]
            lines.extend(self._emit_block(node.body, indent))
            return lines
        if isinstance(node, IRSpawn):
            worker = self._temporary("spawn")
            lines = [f"{prefix}def {worker}():"]
            lines.extend(self._emit_block(node.body, indent + 1))
            lines.append(f"{prefix}_nyx_threading.Thread(target={worker}, daemon=True).start()")
            return lines
        if isinstance(node, IRAssert):
            suffix = "" if node.message is None else f", {node.message!r}"
            return [f"{prefix}assert {self._condition(node.condition)}{suffix}"]
        if isinstance(node, IRMatch):
            return self._emit_match(node, indent)
        if isinstance(node, IRTryCatch):
            error_name = self._symbol(node.error_symbol, node.error_name)
            caught_name = self._temporary("caught")
            lines = [f"{prefix}try:"]
            lines.extend(self._emit_block(node.try_body, indent + 1))
            lines.append(f"{prefix}except Exception as {caught_name}:")
            lines.append(f"{prefix}    {error_name} = str({caught_name})")
            lines.extend(self._emit_block(node.catch_body, indent + 1))
            return lines
        if isinstance(node, IRTestBlock):
            lines = [f"{prefix}# test: {node.description}"]
            lines.extend(self._emit_block(node.body, indent))
            return lines
        raise PythonEmissionError(f"Unsupported HIR statement: {type(node).__name__}")

    def _emit_match(self, node: IRMatch, indent: int) -> List[str]:
        prefix = "    " * indent
        value = self._temporary("match")
        lines = [f"{prefix}{value} = {self._expr(node.expr)}"]
        emitted_condition = False
        for case in node.cases:
            pattern = case.pattern
            wildcard = (
                isinstance(pattern, IRReference) and pattern.name == "_"
            ) or (
                isinstance(pattern, IRLiteral) and pattern.value == "_"
            )
            binding = isinstance(pattern, IRReference) and pattern.name != "_"
            payload = None
            if isinstance(pattern, IRCall) and pattern.callee in ("Ok", "Err"):
                expected = "True" if pattern.callee == "Ok" else "False"
                condition = f"isinstance({value}, Result) and {value}.is_ok is {expected}"
                if pattern.args and isinstance(pattern.args[0], IRReference):
                    payload = self._symbol(pattern.args[0].symbol, pattern.args[0].name)
            elif wildcard or binding:
                condition = "True"
            elif isinstance(pattern, IRCall):
                raise PythonEmissionError(
                    f"Unsupported constructor pattern '{pattern.callee}' on hepy"
                )
            else:
                condition = f"{value} == {self._expr(pattern)}"

            if (wildcard or binding) and emitted_condition:
                lines.append(f"{prefix}else:")
            else:
                keyword_text = "if" if not emitted_condition else "elif"
                lines.append(f"{prefix}{keyword_text} {condition}:")
            if binding:
                binding_name = self._symbol(pattern.symbol, pattern.name)
                lines.append(f"{prefix}    {binding_name} = {value}")
            if payload is not None:
                lines.append(f"{prefix}    {payload} = {value}.value")
            lines.extend(self._emit_block(case.body, indent + 1))
            emitted_condition = True
            if wildcard or binding:
                break
        return lines

    def _expr(self, node: IRExpr | None) -> str:
        if node is None:
            raise PythonEmissionError("Missing HIR expression")
        if isinstance(node, IRLiteral):
            if node.value is None:
                return "None"
            if isinstance(node.value, bool):
                return "True" if node.value else "False"
            if node.type.name == "int" and isinstance(node.value, int):
                return f"_nyx_i64({node.value!r})"
            return repr(node.value)
        if isinstance(node, IRReference):
            return self._symbol(node.symbol, node.name)
        if isinstance(node, IRBinary):
            comparison = node.op in ("==", "!=", "<", "<=", ">", ">=")
            promote_to_float = node.type.name == "float" or (
                comparison and (node.left.type.name == "float" or node.right.type.name == "float")
            )
            expected = FLOAT if promote_to_float else None
            left = self._expr_as(node.left, expected)
            right = self._expr_as(node.right, expected)
            integer_operators = {
                "+": "_nyx_i64_add",
                "-": "_nyx_i64_sub",
                "*": "_nyx_i64_mul",
                "/": "_nyx_int_div",
                "%": "_nyx_int_mod",
                "&": "_nyx_i64_and",
                "^": "_nyx_i64_xor",
                "|": "_nyx_i64_or",
                "<<": "_nyx_i64_shl",
                ">>": "_nyx_i64_shr",
            }
            if node.type.name == "int" and node.op in integer_operators:
                return f"{integer_operators[node.op]}({left}, {right})"
            if node.type.name == "float" and node.op == "/":
                return f"_nyx_f64_div({left}, {right})"
            if node.type.name == "float" and node.op == "%":
                return f"_nyx_f64_mod({left}, {right})"
            operator = {"&&": "and", "||": "or"}.get(node.op, node.op)
            return f"({left} {operator} {right})"
        if isinstance(node, IRUnary):
            operator = "not " if node.op in ("!", "not") else node.op
            if node.type.name == "int":
                if node.op == "-":
                    return f"_nyx_i64_neg({self._expr(node.expr)})"
                if node.op == "~":
                    return f"_nyx_i64_not({self._expr(node.expr)})"
                if node.op == "+":
                    return self._expr(node.expr)
            operand = self._expr_as(node.expr, FLOAT if node.type.name == "float" else None)
            return f"({operator}{operand})"
        if isinstance(node, IRAwait):
            return f"(await {self._expr(node.expr)})"
        if isinstance(node, IRCall):
            expected_types = self._call_parameter_types(node)
            args = ", ".join(
                self._expr_as(
                    argument,
                    expected_types[index] if index < len(expected_types) else None,
                )
                for index, argument in enumerate(node.args)
            )
            if node.receiver is not None:
                receiver = self._expr(node.receiver)
                if node.callee == "push":
                    return f"{receiver}.append({args})"
                if node.callee == "len" and not node.args:
                    return f"_nyx_i64(len({receiver}))"
                return f"{receiver}.{self._identifier(node.callee)}({args})"
            callee = self._symbol(node.callee_symbol, node.callee)
            if node.callee_symbol == "builtin::len":
                return f"_nyx_i64(len({args}))"
            return f"{callee}({args})"
        if isinstance(node, IRMemberAccess):
            obj = self._expr(node.obj)
            member = self._identifier(node.member)
            if node.safe:
                return f"_nyx_safe_getattr({obj}, {member!r})"
            return f"{obj}.{member}"
        if isinstance(node, IRIndexAccess):
            return f"{self._expr(node.obj)}[{self._expr(node.index)}]"
        if isinstance(node, IRArray):
            element_type = node.type.arguments[0] if node.type.arguments else None
            return "[" + ", ".join(
                self._expr_as(element, element_type) for element in node.elements
            ) + "]"
        if isinstance(node, IRNullCoalesce):
            return f"_nyx_coalesce({self._expr(node.left)}, lambda: {self._expr(node.right)})"
        if isinstance(node, IRLambda):
            parameters = [self._parameter_name(param.symbol, param.name) for param in node.params]
            return f"(lambda {', '.join(parameters)}: {self._expr(node.body)})"
        raise PythonEmissionError(f"Unsupported HIR expression: {type(node).__name__}")

    def _expr_as(self, node: IRExpr, expected: IRType | None) -> str:
        rendered = self._expr(node)
        if expected is not None and expected.name == "float" and node.type.name == "int":
            return f"float({rendered})"
        return rendered

    def _call_parameter_types(self, node: IRCall) -> Sequence[IRType]:
        if node.receiver is not None:
            method = self.methods.get((node.receiver.type.name, node.callee))
            if method is None:
                return ()
            parameters = list(method.params)
            if parameters and parameters[0].name in ("self", "this"):
                parameters = parameters[1:]
            return tuple(parameter.type for parameter in parameters)

        if node.callee_symbol.startswith("type::struct::"):
            struct = self.structs.get(node.callee)
            return tuple(field.type for field in struct.fields) if struct is not None else ()

        function = self.functions.get(node.callee_symbol)
        if function is not None:
            return tuple(parameter.type for parameter in function.params)
        signature = BUILTINS.get(node.callee) or INTRINSICS.get(node.callee)
        return signature.parameters if signature is not None else ()

    def _parameter_name(self, symbol: str, preferred: str) -> str:
        if symbol not in self.symbol_names:
            self.symbol_names[symbol] = self._identifier(preferred)
        return self.symbol_names[symbol]

    def _symbol(self, symbol: str, preferred: str) -> str:
        existing = self.symbol_names.get(symbol)
        if existing is not None:
            return existing
        base = self._identifier(preferred)
        if symbol.startswith(("builtin::", "intrinsic::", "function::", "extern::", "type::")):
            name = base
        elif "::param::" in symbol:
            name = base
        elif symbol in self.public_symbols:
            name = base
        elif symbol == "pattern::_":
            name = "_"
        else:
            digest = hashlib.sha256(symbol.encode("utf-8")).hexdigest()[:8]
            name = f"{base}__nyx_{digest}"
        self.symbol_names[symbol] = name
        return name

    def _temporary(self, purpose: str) -> str:
        self.counter += 1
        return f"_nyx_{purpose}_{self.counter}"

    @staticmethod
    def _identifier(name: str) -> str:
        clean = _IDENTIFIER_CHARS.sub("_", name)
        if not clean:
            clean = "_nyx_value"
        if clean[0].isdigit():
            clean = "_" + clean
        if keyword.iskeyword(clean):
            clean += "_nyx"
        return clean

    def _type_name(self, value_type: IRType) -> str:
        mapping = {
            "any": "object",
            "void": "type(None)",
            "bool": "bool",
            "int": "int",
            "float": "float",
            "string": "str",
            "Array": "list",
        }
        return mapping.get(value_type.name, self._identifier(value_type.name))


def emit_python(module: IRModule) -> str:
    """Convenience entry point used by the public compiler API."""

    return HIRPythonEmitter(module).emit()
