"""C++20 emission from verified Nyx HIR.

The emitter consumes only immutable HIR.  A small whole-module constraint pass
resolves legacy inference holes left as ``any`` by the current frontend.  This
keeps convenient unannotated Nyx source native-compilable without reviving AST
heuristics in the backend.
"""

from __future__ import annotations

from collections import defaultdict
import hashlib
import re
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

from src.ir.model import (
    IRAssign,
    IRArray,
    IRAssert,
    IRAwait,
    IRBinary,
    IRBreak,
    IRCall,
    IRContinue,
    IRDefer,
    IREnum,
    IRExpr,
    IRExprStatement,
    IRExternFunction,
    IRFor,
    IRFunction,
    IRGuard,
    IRIf,
    IRImpl,
    IRIndexAccess,
    IRLambda,
    IRLiteral,
    IRMatch,
    IRMemberAccess,
    IRModule,
    IRNativeDirective,
    IRNode,
    IRNullCoalesce,
    IRReference,
    IRReturn,
    IRSpawn,
    IRStatement,
    IRStruct,
    IRTestBlock,
    IRThrow,
    IRTrait,
    IRTryCatch,
    IRTypeAlias,
    IRUnary,
    IRUnsafeBlock,
    IRVarDecl,
    IRWhile,
)
from src.ir.types import ANY, BOOL, FLOAT, INT, NULL, STRING, VOID, IRType, array_of, task_of


class CppEmissionError(ValueError):
    """Raised when verified HIR has no faithful C++20 representation."""


_IDENTIFIER_CHARS = re.compile(r"[^0-9A-Za-z_]")
_CPP_RESERVED = frozenset(
    "alignas alignof and and_eq asm atomic_cancel atomic_commit atomic_noexcept auto "
    "bitand bitor bool break case catch char char8_t char16_t char32_t class compl "
    "concept const consteval constexpr constinit const_cast continue co_await co_return "
    "co_yield decltype default delete do double dynamic_cast else enum explicit export "
    "extern false float for friend goto if inline int long mutable namespace new noexcept "
    "not not_eq nullptr operator or or_eq private protected public reflexpr register "
    "reinterpret_cast requires return short signed sizeof static static_assert static_cast "
    "struct switch synchronized template this thread_local throw true try typedef typeid "
    "typename union unsigned using virtual void volatile wchar_t while xor xor_eq".split()
)


_CPP_RUNTIME = r'''// Auto-generated by Nyx Compiler (hecpp HIR backend)
// Target: ISO C++20
#include <algorithm>
#include <any>
#include <charconv>
#include <chrono>
#include <cctype>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <exception>
#include <fstream>
#include <functional>
#include <future>
#include <iomanip>
#include <iostream>
#include <memory>
#include <mutex>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <thread>
#include <type_traits>
#include <utility>
#include <variant>
#include <vector>

#ifdef _WIN32
#include <windows.h>
#include <process.h>
#else
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#endif

template <typename T, typename E = std::string>
struct NyxResult {
    bool is_ok;
    T value;
    E error;

    T unwrap() const {
        if (!is_ok) throw std::runtime_error("Called unwrap on an Err");
        return value;
    }
};

template <typename T>
using NyxTask = std::shared_future<T>;

template <typename F>
auto _nyx_async(F&& function) -> NyxTask<std::invoke_result_t<std::decay_t<F>>> {
    return std::async(std::launch::async, std::forward<F>(function)).share();
}

template <typename T>
NyxResult<std::decay_t<T>, std::string> _nyx_ok(T&& value) {
    return {true, std::forward<T>(value), {}};
}

template <typename E>
NyxResult<int64_t, std::decay_t<E>> _nyx_err(E&& error) {
    return {false, 0, std::forward<E>(error)};
}

inline std::string _nyx_normalize_decimal(std::string text) {
    bool negative = !text.empty() && text.front() == '-';
    if (!text.empty() && (text.front() == '+' || text.front() == '-')) text.erase(text.begin());
    const size_t exponent_marker = text.find_first_of("eE");
    std::string mantissa = exponent_marker == std::string::npos
        ? text : text.substr(0, exponent_marker);
    const int exponent = exponent_marker == std::string::npos
        ? 0 : std::stoi(text.substr(exponent_marker + 1));
    const size_t dot = mantissa.find('.');
    int decimal_position = static_cast<int>(
        (dot == std::string::npos ? mantissa.size() : dot)
    ) + exponent;
    if (dot != std::string::npos) mantissa.erase(dot, 1);
    const size_t first = mantissa.find_first_not_of('0');
    if (first == std::string::npos) return "0";
    decimal_position -= static_cast<int>(first);
    std::string digits = mantissa.substr(first);
    while (digits.size() > 1 && digits.back() == '0') digits.pop_back();

    std::string result;
    if (decimal_position > -6 && decimal_position <= 21) {
        if (decimal_position <= 0) {
            result = "0." + std::string(static_cast<size_t>(-decimal_position), '0') + digits;
        } else if (static_cast<size_t>(decimal_position) >= digits.size()) {
            result = digits + std::string(static_cast<size_t>(decimal_position) - digits.size(), '0');
        } else {
            result = digits.substr(0, static_cast<size_t>(decimal_position)) + "." +
                digits.substr(static_cast<size_t>(decimal_position));
        }
    } else {
        result.assign(1, digits.front());
        if (digits.size() > 1) result += "." + digits.substr(1);
        const int scientific_exponent = decimal_position - 1;
        result += "e";
        if (scientific_exponent >= 0) result += "+";
        result += std::to_string(scientific_exponent);
    }
    return (negative ? "-" : "") + result;
}

inline std::string _nyx_f64_to_string(double value) {
    if (std::isnan(value)) return "nan";
    if (std::isinf(value)) return std::signbit(value) ? "-inf" : "inf";
    char buffer[128]{};
    const auto converted = std::to_chars(
        buffer, buffer + sizeof(buffer), value, std::chars_format::general
    );
    if (converted.ec != std::errc{}) {
        std::ostringstream fallback;
        fallback << std::setprecision(17) << value;
        return _nyx_normalize_decimal(fallback.str());
    }
    return _nyx_normalize_decimal(std::string(buffer, converted.ptr));
}

inline void _nyx_print_value(double value) { std::cout << _nyx_f64_to_string(value); }

template <typename T>
void _nyx_print_value(T&& value) {
    std::cout << std::boolalpha << std::forward<T>(value);
}

inline void _nyx_print() { std::cout << '\n'; }

template <typename First, typename... Rest>
void _nyx_print(First&& first, Rest&&... rest) {
    _nyx_print_value(std::forward<First>(first));
    ((std::cout << ' ', _nyx_print_value(std::forward<Rest>(rest))), ...);
    std::cout << '\n';
}

inline std::string _nyx_input(const std::string& prompt = "") {
    if (!prompt.empty()) std::cout << prompt;
    std::string value;
    std::getline(std::cin, value);
    return value;
}

inline std::vector<std::string> _nyx_cli_arguments;

inline std::vector<std::string> _nyx_args() {
    return _nyx_cli_arguments;
}

inline std::string _nyx_bootstrap_read_file(const std::string& path) {
    std::ifstream file(path, std::ios::binary);
    if (!file.is_open()) return {};
    std::ostringstream buffer;
    buffer << file.rdbuf();
    return buffer.str();
}

inline bool _nyx_bootstrap_write_file(const std::string& path, const std::string& content) {
    std::ofstream file(path, std::ios::binary);
    if (!file.is_open()) return false;
    file.write(content.data(), static_cast<std::streamsize>(content.size()));
    return file.good();
}

inline bool _nyx_bootstrap_file_exists(const std::string& path) {
    std::ifstream file(path, std::ios::binary);
    return file.good();
}

inline bool _nyx_bootstrap_remove_file(const std::string& path) {
    return std::remove(path.c_str()) == 0;
}

[[noreturn]] inline void _nyx_process_exit(int64_t code) {
    std::exit(static_cast<int>(code));
}

inline std::string _nyx_toolchain_error;

inline int _nyx_spawn_wait(const std::vector<std::string>& command) {
    if (command.empty()) return -1;
    std::vector<char*> arguments;
    arguments.reserve(command.size() + 1);
    for (const auto& part : command) arguments.push_back(const_cast<char*>(part.c_str()));
    arguments.push_back(nullptr);
#ifdef _WIN32
    const intptr_t result = _spawnvp(_P_WAIT, command[0].c_str(), arguments.data());
    return result == -1 ? -1 : static_cast<int>(result);
#else
    const pid_t child = fork();
    if (child < 0) return -1;
    if (child == 0) {
        execvp(command[0].c_str(), arguments.data());
        _exit(127);
    }
    int status = 0;
    if (waitpid(child, &status, 0) < 0) return -1;
    if (WIFEXITED(status)) return WEXITSTATUS(status);
    if (WIFSIGNALED(status)) return 128 + WTERMSIG(status);
    return -1;
#endif
}

inline int _nyx_toolchain_compile_cpp(const std::string& source, const std::string& output) {
    std::vector<std::string> compilers;
    if (const char* configured = std::getenv("NYX_CXX"); configured && *configured) {
        compilers.emplace_back(configured);
    }
    compilers.emplace_back("clang++");
    compilers.emplace_back("g++");
    compilers.emplace_back("c++");
    for (const auto& compiler : compilers) {
        const int result = _nyx_spawn_wait(
            {compiler, "-std=c++20", "-O2", source, "-o", output}
        );
        if (result == 0) { _nyx_toolchain_error.clear(); return 0; }
        if (result == -1 || result == 127) continue;
        _nyx_toolchain_error = compiler + " exited with code " + std::to_string(result);
        return result;
    }
    _nyx_toolchain_error = "No C++20 compiler found (set NYX_CXX or install clang++/g++)";
    return 127;
}

inline std::string _nyx_toolchain_last_error() { return _nyx_toolchain_error; }

inline std::string _nyx_to_string(const std::string& value) { return value; }
inline std::string _nyx_to_string(const char* value) { return value ? std::string(value) : std::string(); }
inline std::string _nyx_to_string(bool value) { return value ? "true" : "false"; }
inline std::string _nyx_to_string(double value) { return _nyx_f64_to_string(value); }
inline double _nyx_math_sin(double value) { return std::sin(value); }
inline double _nyx_math_cos(double value) { return std::cos(value); }
inline double _nyx_math_tan(double value) { return std::tan(value); }

template <typename T>
std::string _nyx_to_string(const T& value) {
    std::ostringstream stream;
    stream << value;
    return stream.str();
}

inline bool _nyx_require_bool(bool value) { return value; }

template <typename T>
bool _nyx_require_bool(const T&) {
    throw std::runtime_error("Nyx condition must have type bool");
}

inline uint64_t _nyx_i64_bits(int64_t value) noexcept {
    uint64_t bits = 0;
    std::memcpy(&bits, &value, sizeof(bits));
    return bits;
}

inline int64_t _nyx_i64_from_bits(uint64_t bits) noexcept {
    int64_t value = 0;
    std::memcpy(&value, &bits, sizeof(value));
    return value;
}

inline int64_t _nyx_i64_add(int64_t left, int64_t right) noexcept {
    return _nyx_i64_from_bits(_nyx_i64_bits(left) + _nyx_i64_bits(right));
}

inline int64_t _nyx_i64_sub(int64_t left, int64_t right) noexcept {
    return _nyx_i64_from_bits(_nyx_i64_bits(left) - _nyx_i64_bits(right));
}

inline int64_t _nyx_i64_mul(int64_t left, int64_t right) noexcept {
    return _nyx_i64_from_bits(_nyx_i64_bits(left) * _nyx_i64_bits(right));
}

inline int64_t _nyx_i64_neg(int64_t value) noexcept {
    return _nyx_i64_from_bits(uint64_t{0} - _nyx_i64_bits(value));
}

inline int64_t _nyx_i64_not(int64_t value) noexcept {
    return _nyx_i64_from_bits(~_nyx_i64_bits(value));
}

inline int64_t _nyx_i64_and(int64_t left, int64_t right) noexcept {
    return _nyx_i64_from_bits(_nyx_i64_bits(left) & _nyx_i64_bits(right));
}

inline int64_t _nyx_i64_xor(int64_t left, int64_t right) noexcept {
    return _nyx_i64_from_bits(_nyx_i64_bits(left) ^ _nyx_i64_bits(right));
}

inline int64_t _nyx_i64_or(int64_t left, int64_t right) noexcept {
    return _nyx_i64_from_bits(_nyx_i64_bits(left) | _nyx_i64_bits(right));
}

inline int64_t _nyx_i64_shl(int64_t value, int64_t amount) noexcept {
    const uint64_t count = _nyx_i64_bits(amount) & UINT64_C(63);
    return _nyx_i64_from_bits(_nyx_i64_bits(value) << count);
}

inline int64_t _nyx_i64_shr(int64_t value, int64_t amount) noexcept {
    const uint64_t count = _nyx_i64_bits(amount) & UINT64_C(63);
    if (count == 0) return value;
    const uint64_t bits = _nyx_i64_bits(value);
    uint64_t shifted = bits >> count;
    if ((bits & (UINT64_C(1) << 63)) != 0) {
        shifted |= (~uint64_t{0}) << (64 - count);
    }
    return _nyx_i64_from_bits(shifted);
}

inline int64_t _nyx_i64_div(int64_t left, int64_t right) {
    if (right == 0) throw std::runtime_error("integer division by zero");
    const int64_t minimum = _nyx_i64_from_bits(UINT64_C(1) << 63);
    if (left == minimum && right == -1) return minimum;
    return left / right;
}

inline int64_t _nyx_i64_mod(int64_t left, int64_t right) {
    if (right == 0) throw std::runtime_error("integer division by zero");
    const int64_t minimum = _nyx_i64_from_bits(UINT64_C(1) << 63);
    if (left == minimum && right == -1) return 0;
    return left % right;
}

inline double _nyx_f64_div(double left, double right) noexcept {
    return left / right;
}

inline double _nyx_f64_mod(double left, double right) noexcept {
    return std::fmod(left, right);
}

inline int64_t _nyx_to_int(const std::string& value) {
    size_t cursor = 0;
    while (cursor < value.size() && std::isspace(static_cast<unsigned char>(value[cursor]))) {
        ++cursor;
    }
    bool negative = false;
    if (cursor < value.size() && (value[cursor] == '+' || value[cursor] == '-')) {
        negative = value[cursor] == '-';
        ++cursor;
    }
    uint64_t result = 0;
    const size_t digits_begin = cursor;
    while (cursor < value.size() && value[cursor] >= '0' && value[cursor] <= '9') {
        result = result * UINT64_C(10) + static_cast<uint64_t>(value[cursor] - '0');
        ++cursor;
    }
    if (cursor == digits_begin) return 0;
    while (cursor < value.size() && std::isspace(static_cast<unsigned char>(value[cursor]))) {
        ++cursor;
    }
    if (cursor != value.size()) return 0;
    if (negative) result = uint64_t{0} - result;
    return _nyx_i64_from_bits(result);
}

inline std::string _nyx_utf8_from_codepoint(int64_t raw_codepoint) {
    uint32_t codepoint = static_cast<uint32_t>(raw_codepoint);
    if (raw_codepoint < 0 || codepoint > 0x10FFFF ||
        (codepoint >= 0xD800 && codepoint <= 0xDFFF)) {
        codepoint = 0xFFFD;
    }
    std::string result;
    if (codepoint <= 0x7F) {
        result.push_back(static_cast<char>(codepoint));
    } else if (codepoint <= 0x7FF) {
        result.push_back(static_cast<char>(0xC0 | (codepoint >> 6)));
        result.push_back(static_cast<char>(0x80 | (codepoint & 0x3F)));
    } else if (codepoint <= 0xFFFF) {
        result.push_back(static_cast<char>(0xE0 | (codepoint >> 12)));
        result.push_back(static_cast<char>(0x80 | ((codepoint >> 6) & 0x3F)));
        result.push_back(static_cast<char>(0x80 | (codepoint & 0x3F)));
    } else {
        result.push_back(static_cast<char>(0xF0 | (codepoint >> 18)));
        result.push_back(static_cast<char>(0x80 | ((codepoint >> 12) & 0x3F)));
        result.push_back(static_cast<char>(0x80 | ((codepoint >> 6) & 0x3F)));
        result.push_back(static_cast<char>(0x80 | (codepoint & 0x3F)));
    }
    return result;
}

inline bool _nyx_contains(const std::string& value, const std::string& part) {
    return value.find(part) != std::string::npos;
}

inline bool _nyx_is_number(const std::string& value) {
    if (value.empty()) return false;
    char* end = nullptr;
    std::strtod(value.c_str(), &end);
    return end != value.c_str() && end && *end == '\0';
}

template <typename T>
int64_t _nyx_len(const T& value) { return static_cast<int64_t>(value.size()); }

inline std::string _nyx_string_index(const std::string& value, int64_t index) {
    if (index < 0 || static_cast<size_t>(index) >= value.size()) return "";
    return std::string(1, value[static_cast<size_t>(index)]);
}

template <typename T>
uintptr_t _nyx_addr(T& value) { return reinterpret_cast<uintptr_t>(&value); }

inline uintptr_t _nyx_addr(void* value) { return reinterpret_cast<uintptr_t>(value); }
inline int64_t _nyx_peek(uintptr_t address) { return *reinterpret_cast<int64_t*>(address); }

inline void _nyx_memdump(uintptr_t address, int64_t length = 16) {
    auto* bytes = reinterpret_cast<const uint8_t*>(address);
    for (int64_t offset = 0; offset < length; offset += 16) {
        std::cout << "0x" << std::hex << std::uppercase << std::setw(16)
                  << std::setfill('0') << (address + static_cast<uintptr_t>(offset)) << ": ";
        for (int64_t column = 0; column < 16; ++column) {
            if (offset + column < length) {
                std::cout << std::setw(2) << static_cast<int>(bytes[offset + column]) << ' ';
            } else {
                std::cout << "   ";
            }
        }
        std::cout << std::dec << '\n';
    }
}

inline void _nyx_delay_ms(int64_t milliseconds) {
    std::this_thread::sleep_for(std::chrono::milliseconds(milliseconds));
}

class _NyxChannel {
public:
    template <typename T>
    void send(T value) {
        std::lock_guard<std::mutex> lock(mutex_);
        values_.emplace_back(std::move(value));
    }

    std::any receive() {
        std::lock_guard<std::mutex> lock(mutex_);
        if (values_.empty()) throw std::runtime_error("receive from empty Nyx channel");
        std::any value = std::move(values_.front());
        values_.pop_front();
        return value;
    }

private:
    std::mutex mutex_;
    std::deque<std::any> values_;
};

inline _NyxChannel _nyx_channel() { return {}; }

template <typename F>
class _NyxScopeExit {
public:
    explicit _NyxScopeExit(F callback) : callback_(std::move(callback)) {}
    _NyxScopeExit(const _NyxScopeExit&) = delete;
    _NyxScopeExit& operator=(const _NyxScopeExit&) = delete;
    _NyxScopeExit(_NyxScopeExit&& other) noexcept
        : callback_(std::move(other.callback_)), active_(other.active_) { other.active_ = false; }
    ~_NyxScopeExit() { if (active_) callback_(); }

private:
    F callback_;
    bool active_ = true;
};

template <typename F>
_NyxScopeExit<F> _nyx_make_scope_exit(F callback) {
    return _NyxScopeExit<F>(std::move(callback));
}

template <typename T>
struct _NyxIsOptional : std::false_type {};

template <typename T>
struct _NyxIsOptional<std::optional<T>> : std::true_type {};

template <typename T, typename Accessor>
auto _nyx_safe_member(const std::optional<T>& value, Accessor&& accessor) {
    using Raw = std::decay_t<decltype(accessor(*value))>;
    if constexpr (_NyxIsOptional<Raw>::value) {
        if (!value) return Raw{};
        return accessor(*value);
    } else {
        if (!value) return std::optional<Raw>{};
        return std::optional<Raw>{accessor(*value)};
    }
}

template <typename T, typename Accessor>
auto _nyx_safe_member(const T& value, Accessor&& accessor) {
    using Raw = std::decay_t<decltype(accessor(value))>;
    if constexpr (_NyxIsOptional<Raw>::value) {
        return accessor(value);
    } else {
        return std::optional<Raw>{accessor(value)};
    }
}

template <typename T, typename Fallback>
T _nyx_coalesce(const std::optional<T>& value, Fallback&& fallback) {
    return value ? *value : static_cast<T>(fallback());
}

#if defined(__GNUC__) || defined(__clang__)
#define NYX_WEAK __attribute__((weak))
#else
#define NYX_WEAK
#endif

extern "C" {
NYX_WEAK void nyx_hal_gpio_mode(int64_t, int64_t) {}
NYX_WEAK void nyx_hal_gpio_write(int64_t, int64_t) {}
NYX_WEAK int64_t nyx_hal_gpio_read(int64_t) { return 0; }
NYX_WEAK void nyx_hal_gpio_toggle(int64_t) {}
NYX_WEAK void nyx_hal_serial_init(int64_t) {}
NYX_WEAK void nyx_hal_serial_write(const char* value) { if (value) std::fputs(value, stdout); }
NYX_WEAK void nyx_hal_serial_write_byte(int64_t value) { std::putchar(static_cast<int>(value)); }
NYX_WEAK int64_t nyx_hal_serial_read_byte() { return std::getchar(); }
NYX_WEAK bool nyx_hal_serial_available() { return true; }
}

inline int64_t nyx_mmio_read8(uintptr_t address) {
    return *reinterpret_cast<volatile uint8_t*>(address);
}
inline void nyx_mmio_write8(uintptr_t address, int64_t value) {
    *reinterpret_cast<volatile uint8_t*>(address) = static_cast<uint8_t>(value);
}
inline int64_t nyx_mmio_read16(uintptr_t address) {
    return *reinterpret_cast<volatile uint16_t*>(address);
}
inline void nyx_mmio_write16(uintptr_t address, int64_t value) {
    *reinterpret_cast<volatile uint16_t*>(address) = static_cast<uint16_t>(value);
}
inline int64_t nyx_mmio_read32(uintptr_t address) {
    return *reinterpret_cast<volatile uint32_t*>(address);
}
inline void nyx_mmio_write32(uintptr_t address, int64_t value) {
    *reinterpret_cast<volatile uint32_t*>(address) = static_cast<uint32_t>(value);
}
'''


def _is_known(value_type: IRType) -> bool:
    if value_type.is_unknown or value_type.name == "null":
        return False
    if value_type.arguments and not all(_is_known(argument) for argument in value_type.arguments):
        return False
    if value_type.is_function:
        return all(_is_known(parameter) for parameter in value_type.parameter_types) and _is_known(
            value_type.return_type or VOID
        )
    return True


def _strip_optional(value_type: IRType) -> IRType:
    return value_type.with_optional(False) if value_type.optional else value_type


def _merge_types(current: IRType, candidate: IRType) -> IRType:
    if not _is_known(candidate):
        return current
    if not _is_known(current):
        return candidate
    if current == candidate:
        return current
    left = _strip_optional(current)
    right = _strip_optional(candidate)
    if left == right:
        return left.with_optional(current.optional or candidate.optional)
    if left.is_numeric and right.is_numeric:
        return FLOAT.with_optional(current.optional or candidate.optional)
    return current


class ModuleTypeInference:
    """Resolve HIR ``any`` slots from whole-module value-flow constraints."""

    def __init__(self, module: IRModule):
        self.module = module
        self.symbol_types: Dict[str, IRType] = {}
        self.function_returns: Dict[str, IRType] = {}
        self.functions: Dict[str, IRFunction] = {}
        self.structs: Dict[str, IRStruct] = {}
        self.struct_fields: Dict[Tuple[str, str], IRType] = {}
        self.methods: Dict[Tuple[str, str], IRFunction] = {}
        self.method_owner: Dict[str, str] = {}
        self.changed = False
        self._register()
        for _ in range(32):
            self.changed = False
            self._scan_module()
            if not self.changed:
                break

    def _register(self) -> None:
        for item in self.module.items:
            if isinstance(item, IRFunction):
                self.functions[item.symbol] = item
                self.function_returns[item.symbol] = item.return_type
                for parameter in item.params:
                    self.symbol_types[parameter.symbol] = parameter.type
            elif isinstance(item, IRStruct):
                self.structs[item.name] = item
                for field in item.fields:
                    self.symbol_types[field.symbol] = field.type
                    self.struct_fields[(item.name, field.name)] = field.type
            elif isinstance(item, IRImpl):
                for method in item.methods:
                    self.functions[method.symbol] = method
                    self.methods[(item.target_type, method.name)] = method
                    self.method_owner[method.symbol] = item.target_type
                    self.function_returns[method.symbol] = method.return_type
                    for index, parameter in enumerate(method.params):
                        value_type = parameter.type
                        if index == 0 and parameter.name in ("self", "this"):
                            value_type = IRType(item.target_type)
                        self.symbol_types[parameter.symbol] = value_type
            elif isinstance(item, IRTrait):
                for method in item.methods:
                    self.functions[method.symbol] = method
                    self.function_returns[method.symbol] = method.return_type
                    for parameter in method.params:
                        self.symbol_types[parameter.symbol] = parameter.type
            elif isinstance(item, IRVarDecl):
                self.symbol_types[item.symbol] = item.type

    def type_of_symbol(self, symbol: str, fallback: IRType = ANY) -> IRType:
        return self.symbol_types.get(symbol, fallback)

    def return_type(self, function: IRFunction) -> IRType:
        return self.function_returns.get(function.symbol, function.return_type)

    def field_type(self, struct_name: str, field_name: str, fallback: IRType = ANY) -> IRType:
        return self.struct_fields.get((struct_name, field_name), fallback)

    def expression_type(self, node: IRExpr) -> IRType:
        if isinstance(node, IRReference):
            return self.type_of_symbol(node.symbol, node.type)
        if isinstance(node, IRCall):
            if node.callee_symbol.startswith("type::struct::"):
                return IRType(node.callee)
            function = self.functions.get(node.callee_symbol)
            if function is not None:
                result = self.return_type(function)
                return task_of(result) if function.is_async else result
            if node.receiver is not None:
                receiver_type = _strip_optional(self.expression_type(node.receiver))
                method = self.methods.get((receiver_type.name, node.callee))
                if method is not None:
                    result = self.return_type(method)
                    return task_of(result) if method.is_async else result
            return node.type
        if isinstance(node, IRAwait):
            awaited = self.expression_type(node.expr)
            if awaited.name == "Task" and awaited.arguments:
                return awaited.arguments[0]
            return node.type
        if isinstance(node, IRMemberAccess):
            owner = _strip_optional(self.expression_type(node.obj)).name
            value_type = self.field_type(owner, node.member, node.type)
            return value_type.with_optional() if node.safe else value_type
        if isinstance(node, IRIndexAccess):
            owner = self.expression_type(node.obj)
            if owner.name == "string":
                return STRING
            if owner.name == "Array" and owner.arguments:
                return owner.arguments[0]
            return node.type
        if isinstance(node, IRArray):
            if node.elements:
                result = self.expression_type(node.elements[0])
                for element in node.elements[1:]:
                    result = _merge_types(result, self.expression_type(element))
                return array_of(result)
            return node.type
        if isinstance(node, IRNullCoalesce):
            left = _strip_optional(self.expression_type(node.left))
            return _merge_types(left, self.expression_type(node.right))
        if isinstance(node, IRBinary):
            if _is_known(node.type):
                return node.type
            if node.op in ("==", "!=", "<", ">", "<=", ">=", "and", "or", "&&", "||"):
                return BOOL
            left = self.expression_type(node.left)
            right = self.expression_type(node.right)
            if node.op == "+" and (left.name == "string" or right.name == "string"):
                return STRING
            return _merge_types(left, right)
        if isinstance(node, IRUnary):
            return BOOL if node.op in ("!", "not") else self.expression_type(node.expr)
        if isinstance(node, IRLambda):
            return node.type
        return node.type

    def _update_symbol(self, symbol: str, candidate: IRType) -> None:
        current = self.symbol_types.get(symbol, ANY)
        # This pass fills legacy ``any`` holes; it must never rewrite a
        # concrete Nyx declaration merely because a use site performs a legal
        # widening conversion (for example int passed to a float parameter).
        if _is_known(current):
            return
        merged = _merge_types(current, candidate)
        if merged != current:
            self.symbol_types[symbol] = merged
            self.changed = True

    def _update_return(self, symbol: str, candidate: IRType) -> None:
        current = self.function_returns.get(symbol, ANY)
        if _is_known(current):
            return
        merged = _merge_types(current, candidate)
        if merged != current:
            self.function_returns[symbol] = merged
            self.changed = True

    def _update_field(self, owner: str, field: str, candidate: IRType) -> None:
        key = (owner, field)
        current = self.struct_fields.get(key, ANY)
        if _is_known(current):
            return
        merged = _merge_types(current, _strip_optional(candidate))
        if merged != current:
            self.struct_fields[key] = merged
            struct = self.structs.get(owner)
            if struct is not None:
                for parameter in struct.fields:
                    if parameter.name == field:
                        self._update_symbol(parameter.symbol, merged)
                        break
            self.changed = True

    def _constrain_expr(self, node: IRExpr, expected: IRType) -> None:
        if not _is_known(expected):
            return
        if isinstance(node, IRReference):
            self._update_symbol(node.symbol, expected)
        elif isinstance(node, IRMemberAccess):
            owner = _strip_optional(self.expression_type(node.obj)).name
            self._update_field(owner, node.member, _strip_optional(expected))
        elif isinstance(node, IRNullCoalesce):
            self._constrain_expr(node.left, expected.with_optional())
            self._constrain_expr(node.right, expected)
        elif isinstance(node, IRCall):
            function = self.functions.get(node.callee_symbol)
            if function is not None:
                if function.is_async:
                    if expected.name == "Task" and expected.arguments:
                        self._update_return(function.symbol, expected.arguments[0])
                else:
                    self._update_return(function.symbol, expected)
        elif isinstance(node, IRAwait):
            self._constrain_expr(node.expr, task_of(expected))
        elif isinstance(node, IRBinary):
            if node.op in ("+", "-", "*", "/", "%", "|", "&", "^", "<<", ">>"):
                self._constrain_expr(node.left, expected)
                self._constrain_expr(node.right, expected)

    def _scan_module(self) -> None:
        for item in self.module.items:
            if isinstance(item, IRFunction):
                self._scan_function(item)
            elif isinstance(item, IRImpl):
                for method in item.methods:
                    self._scan_function(method)
            elif isinstance(item, IRTrait):
                for method in item.methods:
                    self._scan_function(method)
            elif isinstance(item, IRStatement):
                self._scan_statement(item, None)

    def _scan_function(self, function: IRFunction) -> None:
        return_exprs: List[IRExpr] = []
        self._collect_returns(function.body, return_exprs)
        if not return_exprs and function.return_type in (ANY, VOID):
            self._update_return(function.symbol, VOID)
        for expression in return_exprs:
            declared = self.function_returns.get(function.symbol, function.return_type)
            if _is_known(declared):
                self._constrain_expr(expression, declared)
            self._scan_expr(expression)
            self._update_return(function.symbol, self.expression_type(expression))
        for statement in function.body:
            self._scan_statement(statement, function)

    def _collect_returns(self, statements: Sequence[IRStatement], output: List[IRExpr]) -> None:
        for statement in statements:
            if isinstance(statement, IRReturn) and statement.expr is not None:
                output.append(statement.expr)
            elif isinstance(statement, IRIf):
                self._collect_returns(statement.then_branch, output)
                for _, body in statement.elif_branches:
                    self._collect_returns(body, output)
                if statement.else_branch is not None:
                    self._collect_returns(statement.else_branch, output)
            elif isinstance(statement, (IRWhile, IRFor, IRGuard, IRUnsafeBlock, IRSpawn, IRTestBlock)):
                body = statement.else_body if isinstance(statement, IRGuard) else statement.body
                self._collect_returns(body, output)
            elif isinstance(statement, IRTryCatch):
                self._collect_returns(statement.try_body, output)
                self._collect_returns(statement.catch_body, output)
            elif isinstance(statement, IRMatch):
                for case in statement.cases:
                    self._collect_returns(case.body, output)

    def _scan_statement(self, node: IRStatement, owner: Optional[IRFunction]) -> None:
        if isinstance(node, IRVarDecl):
            self._scan_expr(node.expr)
            if _is_known(node.type):
                self._update_symbol(node.symbol, node.type)
                self._constrain_expr(node.expr, node.type)
            self._update_symbol(node.symbol, self.expression_type(node.expr))
        elif isinstance(node, IRAssign):
            self._scan_expr(node.target)
            self._scan_expr(node.expr)
            target_type = self.expression_type(node.target)
            value_type = self.expression_type(node.expr)
            self._constrain_expr(node.target, value_type)
            self._constrain_expr(node.expr, target_type)
        elif isinstance(node, IRExprStatement):
            self._scan_expr(node.expr)
        elif isinstance(node, IRReturn):
            if node.expr is not None:
                self._scan_expr(node.expr)
        elif isinstance(node, IRThrow):
            self._scan_expr(node.expr)
        elif isinstance(node, IRIf):
            self._scan_expr(node.condition)
            for statement in node.then_branch:
                self._scan_statement(statement, owner)
            for condition, body in node.elif_branches:
                self._scan_expr(condition)
                for statement in body:
                    self._scan_statement(statement, owner)
            if node.else_branch is not None:
                for statement in node.else_branch:
                    self._scan_statement(statement, owner)
        elif isinstance(node, IRWhile):
            self._scan_expr(node.condition)
            for statement in node.body:
                self._scan_statement(statement, owner)
        elif isinstance(node, IRFor):
            if node.collection_expr is not None:
                self._scan_expr(node.collection_expr)
                collection_type = self.expression_type(node.collection_expr)
                if collection_type.name == "Array" and collection_type.arguments:
                    self._update_symbol(node.symbol, collection_type.arguments[0])
                elif collection_type.name == "string":
                    self._update_symbol(node.symbol, STRING)
            else:
                if node.start_expr is not None:
                    self._scan_expr(node.start_expr)
                if node.end_expr is not None:
                    self._scan_expr(node.end_expr)
                self._update_symbol(node.symbol, INT)
            for statement in node.body:
                self._scan_statement(statement, owner)
        elif isinstance(node, IRDefer):
            self._scan_expr(node.expr)
        elif isinstance(node, IRGuard):
            self._scan_expr(node.condition)
            for statement in node.else_body:
                self._scan_statement(statement, owner)
        elif isinstance(node, (IRUnsafeBlock, IRSpawn, IRTestBlock)):
            for statement in node.body:
                self._scan_statement(statement, owner)
        elif isinstance(node, IRAssert):
            self._scan_expr(node.condition)
        elif isinstance(node, IRMatch):
            self._scan_expr(node.expr)
            for case in node.cases:
                self._scan_expr(case.pattern)
                for statement in case.body:
                    self._scan_statement(statement, owner)
        elif isinstance(node, IRTryCatch):
            self._update_symbol(node.error_symbol, STRING)
            for statement in node.try_body:
                self._scan_statement(statement, owner)
            for statement in node.catch_body:
                self._scan_statement(statement, owner)

    def _scan_expr(self, node: IRExpr) -> None:
        if isinstance(node, IRBinary):
            self._scan_expr(node.left)
            self._scan_expr(node.right)
            if node.op == "+" and self.expression_type(node) == STRING:
                self._constrain_expr(node.left, STRING)
                self._constrain_expr(node.right, STRING)
            elif node.op in ("==", "!=", "<", ">", "<=", ">="):
                left = self.expression_type(node.left)
                right = self.expression_type(node.right)
                self._constrain_expr(node.left, right)
                self._constrain_expr(node.right, left)
        elif isinstance(node, IRUnary):
            self._scan_expr(node.expr)
        elif isinstance(node, IRAwait):
            self._scan_expr(node.expr)
        elif isinstance(node, IRCall):
            if node.receiver is not None:
                self._scan_expr(node.receiver)
            for argument in node.args:
                self._scan_expr(argument)
            if node.callee_symbol.startswith("type::struct::"):
                struct = self.structs.get(node.callee)
                if struct is not None:
                    for field, argument in zip(struct.fields, node.args):
                        self._update_field(struct.name, field.name, self.expression_type(argument))
                        expected = self.field_type(struct.name, field.name, field.type)
                        self._constrain_expr(argument, expected)
                return
            function = self.functions.get(node.callee_symbol)
            if function is None and node.receiver is not None:
                receiver_type = _strip_optional(self.expression_type(node.receiver))
                function = self.methods.get((receiver_type.name, node.callee))
            if function is not None:
                parameters = list(function.params)
                if node.receiver is not None and parameters and parameters[0].name in ("self", "this"):
                    self._update_symbol(parameters[0].symbol, _strip_optional(self.expression_type(node.receiver)))
                    parameters = parameters[1:]
                for parameter, argument in zip(parameters, node.args):
                    argument_type = self.expression_type(argument)
                    self._update_symbol(parameter.symbol, argument_type)
                    expected = self.type_of_symbol(parameter.symbol, parameter.type)
                    self._constrain_expr(argument, expected)
        elif isinstance(node, IRMemberAccess):
            self._scan_expr(node.obj)
        elif isinstance(node, IRIndexAccess):
            self._scan_expr(node.obj)
            self._scan_expr(node.index)
        elif isinstance(node, IRArray):
            for element in node.elements:
                self._scan_expr(element)
        elif isinstance(node, IRNullCoalesce):
            self._scan_expr(node.left)
            self._scan_expr(node.right)
            right = self.expression_type(node.right)
            self._constrain_expr(node.left, right.with_optional())
            self._constrain_expr(node.right, _strip_optional(self.expression_type(node.left)))
        elif isinstance(node, IRLambda):
            for parameter in node.params:
                self.symbol_types.setdefault(parameter.symbol, parameter.type)
            self._scan_expr(node.body)


class HIRCppEmitter:
    """Emit a standalone hosted C++20 translation unit from verified HIR."""

    _KNOWN_CRT_FUNCTIONS = frozenset(
        "getenv system exit _exit abort malloc calloc realloc free abs labs llabs puts "
        "putchar getchar printf scanf sprintf snprintf strlen wcslen sqrt pow sin cos tan "
        "memset memcpy memmove strcpy strncpy strcmp strncmp strcat strncat fopen fclose "
        "fread fwrite fseek ftell rewind clock time".split()
    )

    _BUILTIN_NAMES = {
        "print": "_nyx_print",
        "input": "_nyx_input",
        "to_string": "_nyx_to_string",
        "to_str": "_nyx_to_string",
        "to_int": "_nyx_to_int",
        "contains": "_nyx_contains",
        "is_number": "_nyx_is_number",
        "addr": "_nyx_addr",
        "peek": "_nyx_peek",
        "memdump": "_nyx_memdump",
        "delay_ms": "_nyx_delay_ms",
        "channel": "_nyx_channel",
        "Ok": "_nyx_ok",
        "Err": "_nyx_err",
        "len": "_nyx_len",
        "args": "_nyx_args",
    }

    def __init__(self, module: IRModule):
        self.module = module
        self.inference = ModuleTypeInference(module)
        self.symbol_names: Dict[str, str] = {}
        self.public_symbols = {
            item.symbol
            for item in module.items
            if isinstance(item, (IRFunction, IRStruct, IRTrait, IRTypeAlias, IREnum, IRExternFunction, IRVarDecl))
        }
        self.impls: Dict[str, List[IRImpl]] = defaultdict(list)
        self.externs: Dict[str, IRExternFunction] = {}
        self.declared_types = {
            item.name
            for item in module.items
            if isinstance(item, (IRStruct, IRTrait, IRTypeAlias, IREnum))
        }
        self.current_return_type: Optional[IRType] = None
        self.counter = 0
        for item in module.items:
            if isinstance(item, IRImpl):
                self.impls[item.target_type].append(item)
            elif isinstance(item, IRExternFunction):
                self.externs[item.symbol] = item
        self._register_declarations()

    def emit(self) -> str:
        lines = _CPP_RUNTIME.splitlines()
        lines.append("")
        lines.extend(self._emit_native_directives())

        aliases = [item for item in self.module.items if isinstance(item, IRTypeAlias)]
        enums = [item for item in self.module.items if isinstance(item, IREnum)]
        traits = [item for item in self.module.items if isinstance(item, IRTrait)]
        structs = [item for item in self.module.items if isinstance(item, IRStruct)]
        externs = [item for item in self.module.items if isinstance(item, IRExternFunction)]
        functions = [item for item in self.module.items if isinstance(item, IRFunction)]
        statements = [item for item in self.module.items if isinstance(item, IRStatement)]

        for struct in structs:
            if struct.generic_params:
                params = ", ".join(f"typename {self._identifier(name)}" for name in struct.generic_params)
                lines.append(f"template <{params}> struct {self._symbol(struct.symbol, struct.name)};")
            else:
                lines.append(f"struct {self._symbol(struct.symbol, struct.name)};")
        if structs:
            lines.append("")

        for alias in aliases:
            lines.extend(self._emit_type_alias(alias))
        for enum in enums:
            lines.extend(self._emit_enum(enum))
        for trait in traits:
            lines.extend(self._emit_trait(trait))
        if aliases or enums or traits:
            lines.append("")

        for external in externs:
            declaration = self._emit_extern(external)
            if declaration:
                lines.extend(declaration)
        if externs:
            lines.append("")

        for function in functions:
            lines.extend(self._emit_function_forward(function))
        if functions:
            lines.append("")

        # Inline impl methods may call module functions. Struct forward
        # declarations make function signatures legal before full struct
        # definitions, so emit callable prototypes first.
        for struct in self._order_structs(structs):
            lines.extend(self._emit_struct(struct))
        if structs:
            lines.append("")

        globals_ = [statement for statement in statements if isinstance(statement, IRVarDecl)]
        executable = [statement for statement in statements if not isinstance(statement, IRVarDecl)]
        for declaration in globals_:
            lines.extend(self._emit_var(declaration, 0, global_scope=True))
        if globals_:
            lines.append("")

        for function in functions:
            lines.extend(self._emit_function(function, 0))
            lines.append("")

        lines.append("int main(int argc, char** argv) {")
        lines.append("    for (int index = 0; index < argc; ++index) {")
        lines.append("        _nyx_cli_arguments.emplace_back(argv[index] ? argv[index] : \"\");")
        lines.append("    }")
        lines.append("#ifdef _WIN32")
        lines.append("    SetConsoleOutputCP(65001);")
        lines.append("    SetConsoleCP(65001);")
        lines.append("#endif")
        for statement in executable:
            lines.extend(self._emit_statement(statement, 1))

        user_main = next((function for function in functions if function.name == "main"), None)
        explicitly_called = any(
            isinstance(statement, IRExprStatement)
            and isinstance(statement.expr, IRCall)
            and statement.expr.receiver is None
            and statement.expr.callee == "main"
            for statement in executable
        )
        if user_main is not None and not explicitly_called:
            suffix = ".get()" if user_main.is_async else ""
            lines.append(f"    {self._symbol(user_main.symbol, user_main.name)}(){suffix};")
        lines.append("    return 0;")
        lines.append("}")
        return "\n".join(lines).rstrip() + "\n"

    def _register_declarations(self) -> None:
        for item in self.module.items:
            if isinstance(item, IRFunction):
                preferred = "_nyx_user_main" if item.name == "main" else item.name
                self.symbol_names[item.symbol] = self._identifier(preferred)
            elif isinstance(item, (IRStruct, IRTrait, IRTypeAlias, IREnum, IRExternFunction, IRVarDecl)):
                self.symbol_names[item.symbol] = self._identifier(item.name)
        for name, emitted in self._BUILTIN_NAMES.items():
            self.symbol_names[f"builtin::{name}"] = emitted

    def _emit_native_directives(self) -> List[str]:
        directives = [item for item in self.module.items if isinstance(item, IRNativeDirective)]
        lines: List[str] = []
        seen_includes = set()
        for directive in directives:
            if directive.kind != "include" or directive.value in seen_includes:
                continue
            seen_includes.add(directive.value)
            value = directive.value.strip()
            if value.startswith(("<", '"')):
                lines.append(f"#include {value}")
            else:
                lines.append(f"#include <{value}>")
        if seen_includes:
            lines.append("")

        for directive in directives:
            if directive.kind == "use":
                value = directive.value.strip().rstrip(";")
                if value.startswith("using "):
                    lines.append(value + ";")
                elif value.startswith("namespace "):
                    lines.append("using " + value + ";")
                elif "::" in value:
                    lines.append(f"using {value};")
                else:
                    lines.append(f"using namespace {value};")
            elif directive.kind == "raw":
                lines.append("// --- BEGIN NYX NATIVE RAW ---")
                lines.extend(directive.value.splitlines())
                lines.append("// --- END NYX NATIVE RAW ---")
        if lines:
            lines.append("")
        return lines

    def _order_structs(self, structs: Sequence[IRStruct]) -> List[IRStruct]:
        # Nyx declaration order is semantically significant for inline impl
        # methods: a later struct may take an earlier one by value even when no
        # field dependency exists.  Front declarations cover recursive vectors;
        # retaining source order covers method signatures and bodies.
        return list(structs)

    def _emit_type_alias(self, node: IRTypeAlias) -> List[str]:
        return [
            f"using {self._symbol(node.symbol, node.name)} = {self._cpp_type(node.actual_type, role='alias')};"
        ]

    def _emit_enum(self, node: IREnum) -> List[str]:
        members = []
        for member in node.members:
            if member.value is None:
                members.append(self._identifier(member.name))
            else:
                members.append(f"{self._identifier(member.name)} = {self._expr(member.value)}")
        return [
            f"enum class {self._symbol(node.symbol, node.name)} {{ {', '.join(members)} }};"
        ]

    def _emit_trait(self, node: IRTrait) -> List[str]:
        name = self._symbol(node.symbol, node.name)
        lines = [f"class {name} {{", "public:", f"    virtual ~{name}() = default;"]
        for method in node.methods:
            return_type = self.inference.return_type(method)
            if not _is_known(return_type):
                raise CppEmissionError(
                    f"Cannot infer trait method return type '{node.name}.{method.name}'"
                )
            parameters = []
            for parameter in method.params:
                if parameter.name in ("self", "this"):
                    continue
                value_type = self.inference.type_of_symbol(parameter.symbol, parameter.type)
                parameters.append(
                    f"{self._cpp_type(value_type, role='parameter')} {self._parameter_name(parameter.symbol, parameter.name)}"
                )
            rendered_return = self._cpp_type(return_type, role="return")
            if method.is_async:
                rendered_return = f"NyxTask<{rendered_return}>"
            lines.append(
                f"    virtual {rendered_return} "
                f"{self._identifier(method.name)}({', '.join(parameters)}) = 0;"
            )
        lines.append("};")
        return lines

    def _emit_struct(self, node: IRStruct) -> List[str]:
        name = self._symbol(node.symbol, node.name)
        lines: List[str] = []
        if node.generic_params:
            params = ", ".join(f"typename {self._identifier(item)}" for item in node.generic_params)
            lines.append(f"template <{params}>")
        base_traits = [
            self._identifier(impl.trait_name)
            for impl in self.impls.get(node.name, ())
            if impl.trait_name
        ]
        inheritance = "" if not base_traits else " : " + ", ".join(
            f"public {trait}" for trait in base_traits
        )
        lines.append(f"struct {name}{inheritance} {{")

        field_types: Dict[str, IRType] = {}
        for field in node.fields:
            value_type = self.inference.field_type(node.name, field.name, field.type)
            if not _is_known(value_type):
                raise CppEmissionError(
                    f"Cannot infer native type for field '{node.name}.{field.name}'; add a Nyx annotation"
                )
            field_types[field.name] = value_type
            lines.append(
                f"    {self._cpp_type(value_type, role='field')} {self._identifier(field.name)}{{}};"
            )

        lines.append(f"    {name}() = default;")
        if node.fields:
            parameters = []
            initializers = []
            for field in node.fields:
                field_name = self._identifier(field.name)
                parameter_name = f"_nyx_{field_name}"
                value_type = field_types[field.name]
                parameter = f"{self._cpp_type(value_type, role='parameter')} {parameter_name}"
                if field.default is not None:
                    parameter += f" = {self._expr(field.default, value_type)}"
                parameters.append(parameter)
                initializers.append(f"{field_name}(std::move({parameter_name}))")
            lines.append(
                f"    {name}({', '.join(parameters)}) : {', '.join(initializers)} {{}}"
            )

        methods = [method for impl in self.impls.get(node.name, ()) for method in impl.methods]
        for method in methods:
            lines.extend(self._emit_method(method, node.name, 1))
        drop_method = next(
            (method for method in methods if method.name in ("drop", "destroy", "cleanup", "dispose")),
            None,
        )
        if drop_method is not None:
            lines.append(f"    ~{name}() {{ this->{self._identifier(drop_method.name)}(); }}")
        lines.append("};")
        return lines

    def _emit_method(self, node: IRFunction, owner: str, indent: int) -> List[str]:
        prefix = "    " * indent
        parameters = []
        has_receiver = bool(node.params and node.params[0].name in ("self", "this"))
        for index, parameter in enumerate(node.params):
            if index == 0 and parameter.name in ("self", "this"):
                self.symbol_names[parameter.symbol] = "this"
                continue
            value_type = self.inference.type_of_symbol(parameter.symbol, parameter.type)
            rendered_type = self._cpp_type(value_type, role="parameter")
            name = self._parameter_name(parameter.symbol, parameter.name)
            rendered = f"{rendered_type} {name}"
            if parameter.default is not None:
                rendered += f" = {self._expr(parameter.default, value_type)}"
            parameters.append(rendered)
        return_type = self.inference.return_type(node)
        if not _is_known(return_type):
            raise CppEmissionError(f"Cannot infer return type for method '{owner}.{node.name}'")
        rendered_return = self._cpp_type(return_type, role="return")
        public_return = f"NyxTask<{rendered_return}>" if node.is_async else rendered_return
        lines = [f"{prefix}{public_return} {self._identifier(node.name)}({', '.join(parameters)}) {{"]
        previous = self.current_return_type
        self.current_return_type = return_type
        try:
            if node.is_async:
                capture = "[=, this]" if has_receiver else "[=]"
                lines.append(
                    f"{prefix}    return _nyx_async({capture}() mutable -> {rendered_return} {{"
                )
                lines.extend(self._emit_block(node.body, indent + 2))
                lines.append(f"{prefix}    }});")
            else:
                lines.extend(self._emit_block(node.body, indent + 1))
        finally:
            self.current_return_type = previous
        lines.append(f"{prefix}}}")
        return lines

    def _emit_extern(self, node: IRExternFunction) -> List[str]:
        if node.name in self._KNOWN_CRT_FUNCTIONS or node.name.startswith(("nyx_hal_", "nyx_mmio_")):
            return []
        parameters = []
        for parameter in node.params:
            value_type = self.inference.type_of_symbol(parameter.symbol, parameter.type)
            parameters.append(
                self._c_ffi_parameter_declaration(
                    value_type,
                    self._parameter_name(parameter.symbol, parameter.name),
                )
            )
        if node.varargs:
            parameters.append("...")
        abi = 'extern "C" ' if node.abi.upper() == "C" else ""
        return [
            f"{abi}{self._c_ffi_type(node.return_type)} "
            f"{self._symbol(node.symbol, node.name)}({', '.join(parameters)});"
        ]

    def _emit_function_forward(self, node: IRFunction) -> List[str]:
        return_type = self.inference.return_type(node)
        if not _is_known(return_type):
            raise CppEmissionError(f"Cannot infer return type for function '{node.name}'")
        lines = []
        if node.generic_params:
            params = ", ".join(f"typename {self._identifier(item)}" for item in node.generic_params)
            lines.append(f"template <{params}>")
        parameters = []
        for parameter in node.params:
            value_type = self.inference.type_of_symbol(parameter.symbol, parameter.type)
            rendered = (
                f"{self._cpp_type(value_type, role='parameter')} "
                f"{self._parameter_name(parameter.symbol, parameter.name)}"
            )
            if parameter.default is not None:
                rendered += f" = {self._expr(parameter.default, value_type)}"
            parameters.append(rendered)
        rendered_return = self._cpp_type(return_type, role="return")
        if node.is_async:
            rendered_return = f"NyxTask<{rendered_return}>"
        lines.append(
            f"{rendered_return} "
            f"{self._symbol(node.symbol, node.name)}({', '.join(parameters)});"
        )
        return lines

    def _emit_function(self, node: IRFunction, indent: int) -> List[str]:
        prefix = "    " * indent
        return_type = self.inference.return_type(node)
        if not _is_known(return_type):
            raise CppEmissionError(f"Cannot infer return type for function '{node.name}'")
        lines: List[str] = []
        if node.generic_params:
            params = ", ".join(f"typename {self._identifier(item)}" for item in node.generic_params)
            lines.append(f"{prefix}template <{params}>")
        parameters = []
        for parameter in node.params:
            value_type = self.inference.type_of_symbol(parameter.symbol, parameter.type)
            parameters.append(
                f"{self._cpp_type(value_type, role='parameter')} "
                f"{self._parameter_name(parameter.symbol, parameter.name)}"
            )
        rendered_return = self._cpp_type(return_type, role="return")
        public_return = f"NyxTask<{rendered_return}>" if node.is_async else rendered_return
        lines.append(
            f"{prefix}{public_return} "
            f"{self._symbol(node.symbol, node.name)}({', '.join(parameters)}) {{"
        )
        previous = self.current_return_type
        self.current_return_type = return_type
        try:
            if node.is_async:
                lines.append(
                    f"{prefix}    return _nyx_async([=]() mutable -> {rendered_return} {{"
                )
                lines.extend(self._emit_block(node.body, indent + 2))
                lines.append(f"{prefix}    }});")
            else:
                lines.extend(self._emit_block(node.body, indent + 1))
        finally:
            self.current_return_type = previous
        lines.append(f"{prefix}}}")
        return lines

    def _emit_block(self, statements: Sequence[IRStatement], indent: int) -> List[str]:
        if not statements:
            return ["    " * indent + "// empty"]
        lines: List[str] = []
        for statement in statements:
            lines.extend(self._emit_statement(statement, indent))
        return lines

    def _condition(self, node: IRExpr) -> str:
        rendered = self._expr(node)
        return f"_nyx_require_bool({rendered})" if node.type.is_unknown else rendered

    def _emit_statement(self, node: IRStatement, indent: int) -> List[str]:
        prefix = "    " * indent
        if isinstance(node, IRVarDecl):
            return self._emit_var(node, indent)
        if isinstance(node, IRAssign):
            expected = self.inference.expression_type(node.target)
            return [f"{prefix}{self._expr(node.target)} = {self._expr(node.expr, expected)};"]
        if isinstance(node, IRExprStatement):
            return [f"{prefix}{self._expr(node.expr)};"]
        if isinstance(node, IRReturn):
            if node.expr is None:
                return [f"{prefix}return;"]
            return [f"{prefix}return {self._expr(node.expr, self.current_return_type)};"]
        if isinstance(node, IRThrow):
            return [f"{prefix}throw std::runtime_error(_nyx_to_string({self._expr(node.expr)}));"]
        if isinstance(node, IRIf):
            lines = [f"{prefix}if ({self._condition(node.condition)}) {{"]
            lines.extend(self._emit_block(node.then_branch, indent + 1))
            for condition, body in node.elif_branches:
                lines.append(f"{prefix}}} else if ({self._condition(condition)}) {{")
                lines.extend(self._emit_block(body, indent + 1))
            if node.else_branch is not None:
                lines.append(f"{prefix}}} else {{")
                lines.extend(self._emit_block(node.else_branch, indent + 1))
            lines.append(f"{prefix}}}")
            return lines
        if isinstance(node, IRWhile):
            lines = [f"{prefix}while ({self._condition(node.condition)}) {{"]
            lines.extend(self._emit_block(node.body, indent + 1))
            lines.append(f"{prefix}}}")
            return lines
        if isinstance(node, IRFor):
            variable = self._symbol(node.symbol, node.var_name)
            if node.collection_expr is not None:
                collection_type = self.inference.expression_type(node.collection_expr)
                if collection_type.name == "string":
                    iterator = self._temporary("string_iter")
                    lines = [f"{prefix}for (char {iterator} : {self._expr(node.collection_expr)}) {{"]
                    lines.append(f"{prefix}    std::string {variable}(1, {iterator});")
                else:
                    lines = [
                        f"{prefix}for (auto& {variable} : {self._expr(node.collection_expr)}) {{"
                    ]
            elif node.start_expr is not None and node.end_expr is not None:
                lines = [
                    f"{prefix}for (int64_t {variable} = {self._expr(node.start_expr)}; "
                    f"{variable} <= static_cast<int64_t>({self._expr(node.end_expr)}); ++{variable}) {{"
                ]
            else:
                raise CppEmissionError("HIR for-loop has neither a collection nor a range")
            lines.extend(self._emit_block(node.body, indent + 1))
            lines.append(f"{prefix}}}")
            return lines
        if isinstance(node, IRBreak):
            return [f"{prefix}break;"]
        if isinstance(node, IRContinue):
            return [f"{prefix}continue;"]
        if isinstance(node, IRDefer):
            guard = self._temporary("defer")
            return [
                f"{prefix}auto {guard} = _nyx_make_scope_exit([&]() {{ {self._expr(node.expr)}; }});"
            ]
        if isinstance(node, IRGuard):
            lines = [f"{prefix}if (!({self._condition(node.condition)})) {{"]
            lines.extend(self._emit_block(node.else_body, indent + 1))
            lines.append(f"{prefix}}}")
            return lines
        if isinstance(node, IRUnsafeBlock):
            lines = [f"{prefix}// unsafe boundary"]
            lines.extend(self._emit_block(node.body, indent))
            return lines
        if isinstance(node, IRSpawn):
            lines = [f"{prefix}std::thread([=]() mutable {{"]
            lines.extend(self._emit_block(node.body, indent + 1))
            lines.append(f"{prefix}}}).detach();")
            return lines
        if isinstance(node, IRAssert):
            message = node.message or "Assertion failed"
            return [
                f"{prefix}if (!({self._condition(node.condition)})) "
                f"throw std::runtime_error({self._string_literal(message)});"
            ]
        if isinstance(node, IRMatch):
            return self._emit_match(node, indent)
        if isinstance(node, IRTryCatch):
            error_name = self._symbol(node.error_symbol, node.error_name)
            caught_name = self._temporary("caught")
            lines = [f"{prefix}try {{"]
            lines.extend(self._emit_block(node.try_body, indent + 1))
            lines.append(f"{prefix}}} catch (const std::exception& {caught_name}) {{")
            lines.append(f"{prefix}    const std::string {error_name} = {caught_name}.what();")
            lines.extend(self._emit_block(node.catch_body, indent + 1))
            lines.append(f"{prefix}}}")
            return lines
        if isinstance(node, IRTestBlock):
            lines = [f"{prefix}// test: {node.description}"]
            lines.extend(self._emit_block(node.body, indent))
            return lines
        raise CppEmissionError(f"Unsupported HIR statement: {type(node).__name__}")

    def _emit_var(self, node: IRVarDecl, indent: int, *, global_scope: bool = False) -> List[str]:
        prefix = "    " * indent
        value_type = self.inference.type_of_symbol(node.symbol, node.type)
        rendered_type = self._cpp_type(value_type, role="variable")
        # Nyx ``let``/``const`` freeze the binding, not the value reachable
        # through it.  C++ ``const`` would impose a stronger, deep receiver
        # restriction (for example rejecting a method call on ``let worker``)
        # that the JS and Python backends do not have.  The verified HIR is the
        # enforcement boundary for rebinding, so keep the emitted C++ storage
        # mutable and use only the linkage qualifier required at module scope.
        qualifier = "inline " if global_scope else ""
        return [
            f"{prefix}{qualifier}{rendered_type} {self._symbol(node.symbol, node.name)} = "
            f"{self._expr(node.expr, value_type)};"
        ]

    def _emit_match(self, node: IRMatch, indent: int) -> List[str]:
        prefix = "    " * indent
        value = self._temporary("match")
        lines = [f"{prefix}auto {value} = {self._expr(node.expr)};"]
        emitted = False
        for case in node.cases:
            pattern = case.pattern
            wildcard = (
                isinstance(pattern, IRReference) and pattern.name == "_"
            ) or (
                isinstance(pattern, IRLiteral) and pattern.value == "_"
            )
            binding = isinstance(pattern, IRReference) and pattern.name != "_"
            payload_name: Optional[str] = None
            payload_member = "value"
            if isinstance(pattern, IRCall) and pattern.callee in ("Ok", "Err"):
                expected = "true" if pattern.callee == "Ok" else "false"
                condition = f"{value}.is_ok == {expected}"
                payload_member = "value" if pattern.callee == "Ok" else "error"
                if pattern.args and isinstance(pattern.args[0], IRReference):
                    payload_name = self._symbol(pattern.args[0].symbol, pattern.args[0].name)
            elif wildcard or binding:
                condition = "true"
            elif isinstance(pattern, IRCall):
                raise CppEmissionError(
                    f"Unsupported constructor pattern '{pattern.callee}' on hecpp"
                )
            else:
                condition = f"{value} == {self._expr(pattern)}"

            if emitted and (wildcard or binding):
                lines.append(f"{prefix}else {{")
            else:
                keyword = "if" if not emitted else "else if"
                lines.append(f"{prefix}{keyword} ({condition}) {{")
            if binding:
                lines.append(
                    f"{prefix}    const auto& {self._symbol(pattern.symbol, pattern.name)} = {value};"
                )
            if payload_name is not None:
                lines.append(f"{prefix}    auto {payload_name} = {value}.{payload_member};")
            lines.extend(self._emit_block(case.body, indent + 1))
            lines.append(f"{prefix}}}")
            emitted = True
            if wildcard or binding:
                break
        return lines

    def _expr(self, node: IRExpr | None, expected: Optional[IRType] = None) -> str:
        if node is None:
            raise CppEmissionError("Missing HIR expression")
        if isinstance(node, IRLiteral):
            if node.value is None:
                if expected is not None and expected.name == "null":
                    return "nullptr"
                if expected is not None and expected.optional:
                    return "std::nullopt"
                return "nullptr"
            if isinstance(node.value, bool):
                return "true" if node.value else "false"
            if isinstance(node.value, str):
                return self._string_literal(node.value)
            if node.type.name == "int" and node.value == -(1 << 63):
                # Writing -9223372036854775808 directly is ill-formed on C++
                # implementations where its positive token fits no signed type.
                return "(-INT64_C(9223372036854775807) - INT64_C(1))"
            if node.type.name == "int":
                # C++ otherwise gives small literals the host type ``int``.
                # Nyx integers are always signed i64, including during template
                # deduction (for example Ok(42) -> Result<int64_t, E>).
                return f"static_cast<int64_t>({node.value})"
            return repr(node.value)
        if isinstance(node, IRReference):
            return self._symbol(node.symbol, node.name)
        if isinstance(node, IRBinary):
            left_type = self.inference.expression_type(node.left)
            right_type = self.inference.expression_type(node.right)
            if isinstance(node.left, IRLiteral) and node.left.value is None:
                left = "std::nullopt" if right_type.optional and right_type.name != "null" else "nullptr"
            else:
                left = self._expr(node.left, right_type)
            if isinstance(node.right, IRLiteral) and node.right.value is None:
                right = "std::nullopt" if left_type.optional and left_type.name != "null" else "nullptr"
            else:
                right = self._expr(node.right, left_type)
            integer_operators = {
                "+": "_nyx_i64_add",
                "-": "_nyx_i64_sub",
                "*": "_nyx_i64_mul",
                "/": "_nyx_i64_div",
                "%": "_nyx_i64_mod",
                "&": "_nyx_i64_and",
                "^": "_nyx_i64_xor",
                "|": "_nyx_i64_or",
                "<<": "_nyx_i64_shl",
                ">>": "_nyx_i64_shr",
            }
            if node.type.name == "int" and node.op in integer_operators:
                return f"{integer_operators[node.op]}({left}, {right})"
            if node.type.name == "float" and node.op == "/":
                return f"_nyx_f64_div({left}, {right})"
            if node.type.name == "float" and node.op == "%":
                return f"_nyx_f64_mod({left}, {right})"
            operator = {"and": "&&", "or": "||"}.get(node.op, node.op)
            return f"({left} {operator} {right})"
        if isinstance(node, IRUnary):
            operator = "!" if node.op in ("!", "not") else node.op
            if node.type.name == "int":
                if node.op == "-":
                    return f"_nyx_i64_neg({self._expr(node.expr)})"
                if node.op == "~":
                    return f"_nyx_i64_not({self._expr(node.expr)})"
                if node.op == "+":
                    return self._expr(node.expr)
            return f"({operator}{self._expr(node.expr)})"
        if isinstance(node, IRAwait):
            return f"({self._expr(node.expr)}).get()"
        if isinstance(node, IRCall):
            if (
                node.callee_symbol.startswith("builtin::")
                and node.callee in ("Ok", "Err")
                and expected is not None
                and expected.name == "Result"
                and len(expected.arguments) >= 2
                and all(_is_known(item) for item in expected.arguments[:2])
                and len(node.args) == 1
            ):
                result_type = self._cpp_type(expected, role="result")
                payload_index = 0 if node.callee == "Ok" else 1
                payload = self._expr(node.args[0], expected.arguments[payload_index])
                if node.callee == "Ok":
                    return f"{result_type}{{true, {payload}, {{}}}}"
                return f"{result_type}{{false, {{}}, {payload}}}"
            if node.receiver is not None:
                receiver = self._expr(node.receiver)
                if isinstance(node.receiver, IRReference) and node.receiver.name in ("self", "this"):
                    receiver = "this"
                    separator = "->"
                else:
                    separator = "."
                args = ", ".join(self._expr(argument) for argument in node.args)
                if node.callee == "push" and len(node.args) == 1:
                    return f"{receiver}{separator}push_back({args})"
                if node.callee in ("len", "length", "size") and not node.args:
                    return f"static_cast<int64_t>({receiver}{separator}size())"
                if node.callee == "pop" and not node.args:
                    return f"{receiver}{separator}pop_back()"
                return f"{receiver}{separator}{self._identifier(node.callee)}({args})"

            if node.callee_symbol.startswith("builtin::"):
                callee = self._BUILTIN_NAMES.get(node.callee, self._identifier(node.callee))
            else:
                callee = self._symbol(node.callee_symbol, node.callee)

            external = self.externs.get(node.callee_symbol)
            expected_arguments: List[IRType] = []
            if node.callee_symbol.startswith("type::struct::"):
                struct = self.inference.structs.get(node.callee)
                if struct is not None:
                    expected_arguments = [
                        self.inference.field_type(struct.name, field.name, field.type)
                        for field in struct.fields
                    ]
            else:
                function = self.inference.functions.get(node.callee_symbol)
                if function is not None:
                    expected_arguments = [
                        self.inference.type_of_symbol(parameter.symbol, parameter.type)
                        for parameter in function.params
                    ]
            rendered_args = []
            for index, argument in enumerate(node.args):
                argument_expected = (
                    expected_arguments[index] if index < len(expected_arguments) else None
                )
                argument_text = self._expr(argument, argument_expected)
                if external is not None and index < len(external.params):
                    parameter_type = external.params[index].type
                    if parameter_type.name == "string" and not parameter_type.pointer:
                        argument_text = f"({argument_text}).c_str()"
                rendered_args.append(argument_text)
            call = f"{callee}({', '.join(rendered_args)})"
            if node.callee_symbol.startswith("type::struct::"):
                return call
            if external is not None and external.return_type.name == "string":
                return f"std::string({call})"
            return call
        if isinstance(node, IRMemberAccess):
            member = self._identifier(node.member)
            if node.safe:
                obj = self._expr(node.obj)
                return f"_nyx_safe_member({obj}, [](const auto& _nyx_value) {{ return _nyx_value.{member}; }})"
            if isinstance(node.obj, IRReference) and node.obj.name in ("self", "this"):
                return f"this->{member}"
            return f"{self._expr(node.obj)}.{member}"
        if isinstance(node, IRIndexAccess):
            if self.inference.expression_type(node.obj).name == "string":
                return f"_nyx_string_index({self._expr(node.obj)}, {self._expr(node.index)})"
            return f"{self._expr(node.obj)}[static_cast<size_t>({self._expr(node.index)})]"
        if isinstance(node, IRArray):
            value_type = self.inference.expression_type(node)
            if expected is not None and expected.name == "Array" and expected.arguments:
                expected_element = expected.arguments[0]
                if not _is_known(value_type) or (
                    value_type.arguments and not _is_known(value_type.arguments[0])
                ):
                    value_type = expected
            element_type = value_type.arguments[0] if value_type.name == "Array" and value_type.arguments else ANY
            if not _is_known(element_type):
                if node.elements:
                    element_type = self.inference.expression_type(node.elements[0])
                else:
                    element_type = INT
            values = ", ".join(self._expr(element, element_type) for element in node.elements)
            return f"std::vector<{self._cpp_type(element_type, role='array')}>{{{values}}}"
        if isinstance(node, IRNullCoalesce):
            if isinstance(node.left, IRLiteral) and node.left.value is None:
                return self._expr(node.right, self.inference.expression_type(node))
            return (
                f"_nyx_coalesce({self._expr(node.left)}, [&]() {{ return {self._expr(node.right)}; }})"
            )
        if isinstance(node, IRLambda):
            parameters = []
            for parameter in node.params:
                value_type = self.inference.type_of_symbol(parameter.symbol, parameter.type)
                parameters.append(
                    f"{self._cpp_type(value_type, role='parameter')} "
                    f"{self._parameter_name(parameter.symbol, parameter.name)}"
                )
            return f"[=]({', '.join(parameters)}) {{ return {self._expr(node.body)}; }}"
        raise CppEmissionError(f"Unsupported HIR expression: {type(node).__name__}")

    def _cpp_type(self, value_type: IRType, *, role: str) -> str:
        if value_type.pointer:
            base = _strip_optional(IRType(value_type.name, value_type.arguments))
            rendered = "void" if base.name == "void" else self._cpp_type(base, role="pointer")
            return rendered + "*"
        if value_type.name == "null":
            return "std::nullptr_t"
        if value_type.optional:
            base = value_type.with_optional(False)
            if not _is_known(base):
                raise CppEmissionError(f"Cannot infer optional {role} type")
            builtin_names = {
                "void", "bool", "int", "i8", "i16", "i32", "i64", "u8", "u16", "u32", "u64",
                "int64", "int32", "float", "f32", "f64", "double",
                "string", "char", "uintptr", "size_t", "Exception", "Channel", "Array", "Result", "Task",
            }
            if base.name not in builtin_names and base.name not in self.declared_types:
                return "std::optional<std::monostate>"
            return f"std::optional<{self._cpp_type(base, role=role)}>"
        if value_type.is_function:
            result = self._cpp_type(value_type.return_type or VOID, role="return")
            parameters = ", ".join(
                self._cpp_type(parameter, role="parameter") for parameter in value_type.parameter_types
            )
            return f"std::function<{result}({parameters})>"
        if value_type.name == "any":
            if role in ("parameter", "variable"):
                return "auto"
            raise CppEmissionError(f"Cannot infer C++ {role} type")
        mapping = {
            "void": "void",
            "bool": "bool",
            "int": "int64_t",
            "i8": "int8_t",
            "i16": "int16_t",
            "i32": "int32_t",
            "u8": "uint8_t",
            "u16": "uint16_t",
            "u32": "uint32_t",
            "u64": "uint64_t",
            "int64": "int64_t",
            "i64": "int64_t",
            "int32": "int32_t",
            "i32": "int32_t",
            "float": "double",
            "f32": "float",
            "f64": "double",
            "double": "double",
            "string": "std::string",
            "char": "char",
            "uintptr": "uintptr_t",
            "size_t": "size_t",
            "Exception": "std::exception",
            "Channel": "_NyxChannel",
        }
        if value_type.name == "Array":
            element = value_type.arguments[0] if value_type.arguments else ANY
            if not _is_known(element):
                if role == "variable":
                    return "auto"
                raise CppEmissionError(f"Cannot infer Array element type for C++ {role}")
            return f"std::vector<{self._cpp_type(element, role='array')}>"
        if value_type.name == "Result":
            if len(value_type.arguments) >= 2 and all(_is_known(item) for item in value_type.arguments[:2]):
                return (
                    f"NyxResult<{self._cpp_type(value_type.arguments[0], role='result')}, "
                    f"{self._cpp_type(value_type.arguments[1], role='result')}>"
                )
            if role == "variable":
                return "auto"
            raise CppEmissionError(f"Cannot infer Result payload types for C++ {role}")
        if value_type.name == "Task":
            if len(value_type.arguments) == 1 and _is_known(value_type.arguments[0]):
                return f"NyxTask<{self._cpp_type(value_type.arguments[0], role='task')}>"
            if role == "variable":
                return "auto"
            raise CppEmissionError(f"Cannot infer Task result type for C++ {role}")
        rendered = mapping.get(value_type.name, self._identifier(value_type.name))
        if value_type.arguments:
            args = ", ".join(self._cpp_type(item, role="generic") for item in value_type.arguments)
            rendered += f"<{args}>"
        return rendered

    def _c_ffi_parameter_declaration(self, value_type: IRType, name: str) -> str:
        if value_type.is_function:
            if value_type.optional:
                raise CppEmissionError("Optional callback types are not supported by the C ABI")
            result = self._c_ffi_type(value_type.return_type or VOID)
            parameters = ", ".join(
                self._c_ffi_type(parameter) for parameter in value_type.parameter_types
            ) or "void"
            return f"{result} (*{name})({parameters})"
        return f"{self._c_ffi_type(value_type)} {name}"

    def _c_ffi_type(self, value_type: IRType) -> str:
        if value_type.is_function:
            raise CppEmissionError(
                "C ABI callback types require a named function-pointer declarator"
            )
        if value_type.pointer:
            base = IRType(value_type.name, value_type.arguments)
            rendered = "void" if base.name == "void" else self._c_ffi_type(base)
            return rendered + "*"
        mapping = {
            "any": "void*",
            "void": "void",
            "bool": "bool",
            "int": "int64_t",
            "i8": "int8_t",
            "i16": "int16_t",
            "i32": "int32_t",
            "u8": "uint8_t",
            "u16": "uint16_t",
            "u32": "uint32_t",
            "u64": "uint64_t",
            "int64": "int64_t",
            "i64": "int64_t",
            "int32": "int32_t",
            "i32": "int32_t",
            "float": "double",
            "f32": "float",
            "f64": "double",
            "double": "double",
            "string": "const char*",
            "char": "char",
            "uintptr": "uintptr_t",
            "size_t": "size_t",
        }
        return mapping.get(value_type.name, self._identifier(value_type.name))

    def _parameter_name(self, symbol: str, preferred: str) -> str:
        if symbol not in self.symbol_names:
            self.symbol_names[symbol] = self._identifier(preferred)
        return self.symbol_names[symbol]

    def _symbol(self, symbol: str, preferred: str) -> str:
        if symbol == "pattern::_":
            return "_"
        existing = self.symbol_names.get(symbol)
        if existing is not None:
            return existing
        base = self._identifier(preferred)
        if symbol.startswith("function::") and preferred in ("abs", "min", "max"):
            base = f"_nyx_user_{preferred}"
        if symbol.startswith(("builtin::", "intrinsic::", "function::", "extern::", "type::")):
            name = base
        elif "::param::" in symbol:
            name = base
        elif symbol in self.public_symbols:
            name = base
        else:
            digest = hashlib.sha256(symbol.encode("utf-8")).hexdigest()[:8]
            name = f"{base}__nyx_{digest}"
        self.symbol_names[symbol] = name
        return name

    def _temporary(self, purpose: str) -> str:
        self.counter += 1
        return f"_nyx_{purpose}_{self.counter}"

    @staticmethod
    def _identifier(name: str) -> str:
        clean = _IDENTIFIER_CHARS.sub("_", name)
        if not clean:
            clean = "_nyx_value"
        if clean[0].isdigit():
            clean = "_" + clean
        if clean in _CPP_RESERVED:
            clean += "_nyx"
        return clean

    @staticmethod
    def _string_literal(value: str) -> str:
        data = value.encode("utf-8")
        encoded = "".join(f"\\x{byte:02x}" for byte in data)
        return f"std::string(\"{encoded}\", {len(data)})"


def emit_cpp(module: IRModule) -> str:
    """Convenience entry point used by the public compiler API."""

    return HIRCppEmitter(module).emit()
