"""Typed WebAssembly IR and lowering for ``nyx bundle``.

The bundle backend intentionally uses one instruction graph for both WAT and
binary WASM emission.  This prevents the two artifacts from drifting apart and
makes unsupported Nyx constructs fail at compile time instead of silently
producing placeholder behavior.
"""

from __future__ import annotations

import struct
from dataclasses import dataclass, field, fields, is_dataclass
from typing import Callable, Dict, Iterable, List, Optional, Sequence, Tuple

from src.ir.model import (
    IRAssign,
    IRBinary,
    IRBreak,
    IRCall,
    IRContinue,
    IRConditional,
    IRExpr,
    IRExprStatement,
    IRExternFunction,
    IRFor,
    IRFunction,
    IRIf,
    IRLiteral,
    IRMatchExpression,
    IRMemberAccess,
    IRModule,
    IRReference,
    IRReturn,
    IRStatement,
    IRStruct,
    IRTypeAlias,
    IRUnary,
    IRVarDecl,
    IRWhile,
)
from src.ir.verifier import IRVerificationError, verify_hir


I32 = "i32"
I64 = "i64"
F64 = "f64"
VOID = "void"
STRING = "string"
ARRAY_I32 = "array_i32"
ARRAY_F64 = "array_f64"
STRUCT_PREFIX = "struct:"

WASM_TYPE_CODES = {I32: 0x7F, I64: 0x7E, F64: 0x7C}


class BundleCompileError(ValueError):
    """Raised when a Nyx construct has no semantics in the bundle backend."""


@dataclass(frozen=True)
class Instruction:
    op: str
    arg: object = None


@dataclass
class FunctionIR:
    name: str
    params: List[Tuple[str, str]]
    result: str
    locals: List[Tuple[str, str]] = field(default_factory=list)
    body: List[Instruction] = field(default_factory=list)
    export: bool = True

    def local_indices(self) -> Dict[str, int]:
        names = [name for name, _ in self.params] + [name for name, _ in self.locals]
        return {name: index for index, name in enumerate(names)}


@dataclass(frozen=True)
class ImportFunctionIR:
    module: str
    name: str
    params: Tuple[str, ...]
    result: str


@dataclass(frozen=True)
class GlobalIR:
    name: str
    value_type: str
    initial: object
    mutable: bool = True


@dataclass(frozen=True)
class DataSegment:
    offset: int
    data: bytes


class ModuleIR:
    """A complete, encodable WebAssembly module."""

    def __init__(
        self,
        module_name: str,
        functions: List[FunctionIR],
        data: List[DataSegment],
        heap_start: int,
        imports: Optional[List[ImportFunctionIR]] = None,
        globals_: Optional[List[GlobalIR]] = None,
    ):
        self.module_name = module_name
        self.functions = functions
        self.data = data
        self.heap_start = heap_start
        self.imports = imports or []
        self.globals = globals_ or []

    def to_wat(self) -> str:
        lines = [
            f";; Auto-generated by nyx bundle ({self.module_name}) - ABI v1",
            "(module",
        ]

        for imported in self.imports:
            params = " ".join(f"(param {value_type})" for value_type in imported.params)
            result = "" if imported.result == VOID else f" (result {imported.result})"
            signature = f'  (import "{imported.module}" "{imported.name}" (func ${imported.name}'
            if params:
                signature += f" {params}"
            signature += f"{result}))"
            lines.append(signature)
        if self.imports:
            lines.append("")

        lines.extend((
            '  (memory (export "memory") 2)',
            f"  (global $heap_ptr (mut i32) (i32.const {self.heap_start}))",
            "",
        ))

        for global_value in self.globals:
            mutability = f"(mut {global_value.value_type})" if global_value.mutable else global_value.value_type
            lines.append(
                f"  (global ${global_value.name} {mutability} "
                f"({global_value.value_type}.const {global_value.initial}))"
            )
        if self.globals:
            lines.append("")

        for function in self.functions:
            params = " ".join(f"(param ${name} {value_type})" for name, value_type in function.params)
            result = "" if function.result == VOID else f" (result {function.result})"
            export = f' (export "{function.name}")' if function.export else ""
            signature = f"  (func ${function.name}{export}"
            if params:
                signature += f" {params}"
            signature += result
            lines.append(signature)
            for name, value_type in function.locals:
                lines.append(f"    (local ${name} {value_type})")
            lines.extend(self._wat_instructions(function.body, indent=4))
            lines.append("  )")
            lines.append("")

        for segment in self.data:
            lines.append(f'  (data (i32.const {segment.offset}) "{_wat_bytes(segment.data)}")')
        if self.data:
            lines.append("")
        lines.append(")")
        return "\n".join(lines)

    def _wat_instructions(self, instructions: Sequence[Instruction], indent: int) -> List[str]:
        lines: List[str] = []
        current_indent = indent
        simple_ops = {
            "i32.add", "i32.sub", "i32.mul", "i32.div_s", "i32.rem_s",
            "i32.and", "i32.or", "i32.xor", "i32.shl", "i32.shr_s",
            "i32.eqz", "i32.eq", "i32.ne", "i32.lt_s", "i32.gt_s",
            "i32.le_s", "i32.ge_s", "i64.extend_i32_u", "i64.shl",
            "i64.or", "f64.add", "f64.sub", "f64.mul", "f64.div",
            "f64.neg", "f64.eq", "f64.ne", "f64.lt", "f64.gt", "f64.le",
            "f64.ge", "f64.convert_i32_s", "return", "drop", "memory.size",
            "memory.grow", "memory.copy", "unreachable",
            "i32.load", "f64.load", "i32.store", "i32.wrap_i64", "i64.shr_u",
        }
        for instruction in instructions:
            op = instruction.op
            arg = instruction.arg
            if op in ("end", "else"):
                current_indent -= 2
            prefix = " " * current_indent
            if op == "block":
                lines.append(f"{prefix}block ${arg}")
                current_indent += 2
            elif op == "loop":
                lines.append(f"{prefix}loop ${arg}")
                current_indent += 2
            elif op == "if":
                lines.append(f"{prefix}if")
                current_indent += 2
            elif op == "if_result":
                lines.append(f"{prefix}if (result {arg})")
                current_indent += 2
            elif op == "else":
                lines.append(f"{prefix}else")
                current_indent += 2
            elif op == "end":
                lines.append(f"{prefix}end")
            elif op in ("local.get", "local.set", "local.tee", "global.get", "global.set"):
                lines.append(f"{prefix}{op} ${arg}")
            elif op in ("br", "br_if"):
                lines.append(f"{prefix}{op} ${arg}")
            elif op == "call":
                lines.append(f"{prefix}call ${arg}")
            elif op in ("i32.const", "i64.const", "f64.const"):
                lines.append(f"{prefix}{op} {arg}")
            elif op in simple_ops:
                lines.append(f"{prefix}{op}")
            else:
                raise BundleCompileError(f"Cannot render unknown WASM instruction '{op}'")
        return lines

    def to_wasm(self) -> bytes:
        wasm = bytearray(b"\x00\x61\x73\x6d\x01\x00\x00\x00")

        type_indices: Dict[Tuple[Tuple[str, ...], str], int] = {}
        types: List[Tuple[Tuple[str, ...], str]] = []
        function_type_indices: List[int] = []
        signatures = [
            (imported.params, imported.result) for imported in self.imports
        ] + [
            (tuple(value_type for _, value_type in function.params), function.result)
            for function in self.functions
        ]
        for signature in signatures:
            if signature not in type_indices:
                type_indices[signature] = len(types)
                types.append(signature)
        for function in self.functions:
            signature = (tuple(value_type for _, value_type in function.params), function.result)
            function_type_indices.append(type_indices[signature])

        type_payload = bytearray(_u32(len(types)))
        for params, result in types:
            type_payload.append(0x60)
            type_payload.extend(_u32(len(params)))
            type_payload.extend(WASM_TYPE_CODES[param] for param in params)
            if result == VOID:
                type_payload.append(0)
            else:
                type_payload.extend((1, WASM_TYPE_CODES[result]))
        _append_section(wasm, 1, type_payload)

        if self.imports:
            import_payload = bytearray(_u32(len(self.imports)))
            for imported in self.imports:
                import_payload.extend(_string(imported.module))
                import_payload.extend(_string(imported.name))
                import_payload.append(0x00)
                import_payload.extend(_u32(type_indices[(imported.params, imported.result)]))
            _append_section(wasm, 2, import_payload)

        function_payload = bytearray(_u32(len(self.functions)))
        for type_index in function_type_indices:
            function_payload.extend(_u32(type_index))
        _append_section(wasm, 3, function_payload)

        _append_section(wasm, 5, bytes((1, 0, 2)))

        global_payload = bytearray(_u32(1 + len(self.globals)))
        global_payload.extend((WASM_TYPE_CODES[I32], 1, 0x41))
        global_payload.extend(_s32(self.heap_start))
        global_payload.append(0x0B)
        for global_value in self.globals:
            global_payload.extend((WASM_TYPE_CODES[global_value.value_type], 1 if global_value.mutable else 0))
            if global_value.value_type == I32:
                global_payload.append(0x41)
                global_payload.extend(_s32(int(global_value.initial)))
            elif global_value.value_type == F64:
                global_payload.append(0x44)
                global_payload.extend(struct.pack("<d", float(global_value.initial)))
            else:
                raise BundleCompileError(f"Unsupported WASM global type '{global_value.value_type}'")
            global_payload.append(0x0B)
        _append_section(wasm, 6, global_payload)

        exports = [("memory", 0x02, 0)]
        imported_count = len(self.imports)
        exports.extend(
            (function.name, 0x00, imported_count + index)
            for index, function in enumerate(self.functions)
            if function.export
        )
        export_payload = bytearray(_u32(len(exports)))
        for name, kind, index in exports:
            export_payload.extend(_string(name))
            export_payload.append(kind)
            export_payload.extend(_u32(index))
        _append_section(wasm, 7, export_payload)

        function_indices = {imported.name: index for index, imported in enumerate(self.imports)}
        function_indices.update({
            function.name: imported_count + index
            for index, function in enumerate(self.functions)
        })
        global_indices = {"heap_ptr": 0}
        global_indices.update({item.name: index + 1 for index, item in enumerate(self.globals)})
        code_payload = bytearray(_u32(len(self.functions)))
        for function in self.functions:
            body = bytearray()
            local_groups: List[Tuple[int, str]] = []
            for _, value_type in function.locals:
                if local_groups and local_groups[-1][1] == value_type:
                    count, existing_type = local_groups[-1]
                    local_groups[-1] = (count + 1, existing_type)
                else:
                    local_groups.append((1, value_type))
            body.extend(_u32(len(local_groups)))
            for count, value_type in local_groups:
                body.extend(_u32(count))
                body.append(WASM_TYPE_CODES[value_type])
            body.extend(self._encode_instructions(function, function_indices, global_indices))
            body.append(0x0B)
            code_payload.extend(_u32(len(body)))
            code_payload.extend(body)
        _append_section(wasm, 10, code_payload)

        if self.data:
            data_payload = bytearray(_u32(len(self.data)))
            for segment in self.data:
                data_payload.extend((0, 0x41))
                data_payload.extend(_s32(segment.offset))
                data_payload.append(0x0B)
                data_payload.extend(_u32(len(segment.data)))
                data_payload.extend(segment.data)
            _append_section(wasm, 11, data_payload)

        return bytes(wasm)

    def _encode_instructions(
        self,
        function: FunctionIR,
        function_indices: Dict[str, int],
        global_indices: Dict[str, int],
    ) -> bytes:
        output = bytearray()
        locals_by_name = function.local_indices()
        controls: List[Optional[str]] = []
        simple_opcodes = {
            "unreachable": 0x00, "return": 0x0F, "drop": 0x1A,
            "i32.eqz": 0x45, "i32.eq": 0x46, "i32.ne": 0x47,
            "i32.lt_s": 0x48, "i32.gt_s": 0x4A, "i32.le_s": 0x4C,
            "i32.ge_s": 0x4E, "f64.eq": 0x61, "f64.ne": 0x62,
            "f64.lt": 0x63, "f64.gt": 0x64, "f64.le": 0x65,
            "f64.ge": 0x66, "i32.add": 0x6A, "i32.sub": 0x6B,
            "i32.mul": 0x6C, "i32.div_s": 0x6D, "i32.rem_s": 0x6F,
            "i32.and": 0x71, "i32.or": 0x72, "i32.xor": 0x73,
            "i32.shl": 0x74, "i32.shr_s": 0x75, "f64.neg": 0x9A,
            "f64.add": 0xA0, "f64.sub": 0xA1, "f64.mul": 0xA2,
            "f64.div": 0xA3, "i64.extend_i32_u": 0xAD,
            "f64.convert_i32_s": 0xB7, "i32.wrap_i64": 0xA7,
            "i64.or": 0x84, "i64.shl": 0x86, "i64.shr_u": 0x88,
        }
        for instruction in function.body:
            op = instruction.op
            arg = instruction.arg
            if op in simple_opcodes:
                output.append(simple_opcodes[op])
            elif op == "i32.const":
                output.append(0x41)
                output.extend(_s32(int(arg)))
            elif op == "i64.const":
                output.append(0x42)
                output.extend(_s64(int(arg)))
            elif op == "f64.const":
                output.append(0x44)
                output.extend(struct.pack("<d", float(arg)))
            elif op in ("i32.load", "f64.load"):
                output.append(0x28 if op == "i32.load" else 0x2B)
                output.extend(_u32(2 if op == "i32.load" else 3))
                output.extend(_u32(0))
            elif op == "i32.store":
                output.append(0x36)
                output.extend(_u32(2))
                output.extend(_u32(0))
            elif op in ("local.get", "local.set", "local.tee"):
                output.append({"local.get": 0x20, "local.set": 0x21, "local.tee": 0x22}[op])
                output.extend(_u32(locals_by_name[str(arg)]))
            elif op in ("global.get", "global.set"):
                output.append(0x23 if op == "global.get" else 0x24)
                output.extend(_u32(global_indices[str(arg)]))
            elif op == "call":
                output.append(0x10)
                output.extend(_u32(function_indices[str(arg)]))
            elif op in ("block", "loop", "if"):
                output.extend(({"block": 0x02, "loop": 0x03, "if": 0x04}[op], 0x40))
                controls.append(str(arg) if arg is not None else None)
            elif op == "if_result":
                result_type = str(arg)
                if result_type not in WASM_TYPE_CODES:
                    raise BundleCompileError(f"Invalid WASM conditional result type '{result_type}'")
                output.extend((0x04, WASM_TYPE_CODES[result_type]))
                controls.append(None)
            elif op == "else":
                output.append(0x05)
            elif op == "end":
                output.append(0x0B)
                if not controls:
                    raise BundleCompileError("Unbalanced WASM control-flow end")
                controls.pop()
            elif op in ("br", "br_if"):
                output.append(0x0C if op == "br" else 0x0D)
                target = str(arg)
                try:
                    depth = next(index for index, label in enumerate(reversed(controls)) if label == target)
                except StopIteration as exc:
                    raise BundleCompileError(f"Unknown WASM branch label '{target}'") from exc
                output.extend(_u32(depth))
            elif op == "memory.size":
                output.extend((0x3F, 0x00))
            elif op == "memory.grow":
                output.extend((0x40, 0x00))
            elif op == "memory.copy":
                output.extend((0xFC, 0x0A, 0x00, 0x00))
            else:
                raise BundleCompileError(f"Cannot encode unknown WASM instruction '{op}'")
        if controls:
            raise BundleCompileError("Unclosed WASM control-flow block")
        return bytes(output)


class BundleLowerer:
    DATA_START = 2048

    def __init__(self, hir: IRModule, module_name: str, wasi: bool = False):
        self.hir = hir
        self.module_name = module_name
        self.wasi = wasi
        self.user_functions = [
            function for function in hir.functions
            if not function.name.startswith("_") and (wasi or function.name != "main")
        ]
        self.type_aliases = {
            item.name: item.actual_type for item in hir.items if isinstance(item, IRTypeAlias)
        }
        self.structs = {
            item.name: item for item in hir.items if isinstance(item, IRStruct)
        }
        self.global_types: Dict[str, str] = {}
        self.extern_functions = {
            item.name: item for item in hir.items if isinstance(item, IRExternFunction)
        }
        self.function_results = {function.name: self._type(function.return_type) for function in self.user_functions}
        self.data: List[DataSegment] = []
        self.data_by_value: Dict[bytes, int] = {}
        self.next_data_offset = self.DATA_START
        self.label_counter = 0
        self.match_locals: Dict[int, str] = {}
        self.for_index_locals: Dict[int, str] = {}

    def lower(self) -> ModuleIR:
        try:
            verify_hir(self.hir)
        except IRVerificationError as error:
            raise BundleCompileError(str(error)) from error
        globals_ = self._lower_globals()
        lowered = [self._lower_function(function) for function in self.user_functions]
        heap_start = _align8(self.next_data_offset)
        runtime = _runtime_functions()
        imports = [self._lower_import(item) for item in self.extern_functions.values()]
        if self.wasi:
            fd_write = next((item for item in imports if item.name == "fd_write"), None)
            expected_fd_write = ImportFunctionIR(
                "wasi_snapshot_preview1",
                "fd_write",
                (I32, I32, I32, I32),
                I32,
            )
            if fd_write is not None and fd_write != expected_fd_write:
                raise BundleCompileError(
                    "WASI profile reserves fd_write with signature "
                    "wasi_snapshot_preview1.(i32, i32, i32, i32) -> i32"
                )
            if fd_write is None:
                imports.append(
                    expected_fd_write
                )
            runtime.extend(_wasi_runtime_functions())
            main = next((function for function in lowered if function.name == "main"), None)
            if main is None:
                raise BundleCompileError("WASI profile requires fn main()")
            if main.params or main.result != VOID:
                raise BundleCompileError("WASI entry point must be fn main() -> void")
            main.export = False
            runtime.append(
                FunctionIR("_start", [], VOID, body=[Instruction("call", "main")])
            )
        return ModuleIR(self.module_name, runtime + lowered, self.data, heap_start, imports, globals_)

    def _lower_globals(self) -> List[GlobalIR]:
        globals_: List[GlobalIR] = []
        for item in self.hir.top_level_statements:
            if not isinstance(item, IRVarDecl):
                raise BundleCompileError(
                    f"WASM bundle top-level statement '{type(item).__name__}' is not supported"
                )
            value_type = self._type(item.type)
            if value_type not in (I32, F64) or not isinstance(item.expr, IRLiteral):
                raise BundleCompileError(
                    f"WASM global '{item.name}' requires a numeric or bool literal initializer"
                )
            initial = 1 if item.expr.type.name == "bool" and item.expr.value else item.expr.value
            globals_.append(GlobalIR(item.name, value_type, initial, not item.is_const))
            self.global_types[item.name] = value_type
        return globals_

    def _lower_import(self, external: IRExternFunction) -> ImportFunctionIR:
        abi = external.abi.strip()
        if not abi.upper().startswith("WASM:"):
            raise BundleCompileError(
                f"WASM bundle cannot lower extern ABI '{external.abi}' for '{external.name}'"
            )
        module = abi.split(":", 1)[1].strip()
        if not module:
            raise BundleCompileError(f"WASM extern '{external.name}' requires an import module name")
        params: List[str] = []
        for parameter in external.params:
            value_type = self._type(parameter.type)
            if value_type == STRING:
                params.extend((I32, I32))
            elif value_type in (I32, F64):
                params.append(value_type)
            else:
                raise BundleCompileError(
                    f"WASM extern '{external.name}' uses unsupported parameter type '{value_type}'"
                )
        result = self._type(external.return_type)
        if result == STRING:
            result = I64
        if result not in (I32, I64, F64, VOID):
            raise BundleCompileError(
                f"WASM extern '{external.name}' uses unsupported return type '{result}'"
            )
        return ImportFunctionIR(module, external.name, tuple(params), result)

    def _lower_function(self, function: IRFunction) -> FunctionIR:
        params: List[Tuple[str, str]] = []
        symbols: Dict[str, str] = {}
        for parameter in function.params:
            value_type = self._type(parameter.type_annot)
            symbols[parameter.name] = value_type
            if value_type in (STRING, ARRAY_I32, ARRAY_F64):
                params.extend(((f"{parameter.name}_ptr", I32), (f"{parameter.name}_len", I32)))
            elif value_type.startswith(STRUCT_PREFIX):
                self._struct_layout(value_type[len(STRUCT_PREFIX):])
                params.append((f"{parameter.name}_ptr", I32))
            elif value_type in (I32, F64):
                params.append((parameter.name, value_type))
            else:
                raise BundleCompileError(f"Unsupported parameter type '{value_type}' in {function.name}()")

        result = self._type(function.return_type)
        if self.wasi and function.name == "main" and result == "any":
            result = VOID
        if result == STRING:
            wasm_result = I64
        elif result in (I32, F64, VOID):
            wasm_result = result
        else:
            raise BundleCompileError(f"Unsupported return type '{result}' in {function.name}()")

        local_types: Dict[str, str] = {}
        self._collect_locals(function.body, symbols, local_types)
        if result == STRING:
            local_types.update({"__nyx_out_ptr": I32, "__nyx_out_len": I32, "__nyx_cursor": I32})

        ir = FunctionIR(function.name, params, wasm_result, list(local_types.items()))
        context = _LowerContext(function.name, self.global_types | symbols | local_types, result, self)
        for statement in function.body:
            self._emit_statement(statement, ir.body, context)
        if wasm_result != VOID and not _definitely_returns(function.body):
            raise BundleCompileError(f"Function '{function.name}' can fall through without returning a value")
        if wasm_result != VOID:
            # Keep the function-end stack valid even when all source paths return
            # from nested structured control flow. This path is provably dead.
            ir.body.append(Instruction("unreachable"))
        return ir

    def _collect_locals(
        self,
        statements: Iterable[IRStatement],
        symbols: Dict[str, str],
        locals_out: Dict[str, str],
    ) -> None:
        for statement in statements:
            self._collect_expression_locals(statement, locals_out)
            if isinstance(statement, IRVarDecl):
                value_type = self._type(statement.type)
                if value_type not in (I32, F64):
                    raise BundleCompileError(f"Bundle local '{statement.name}' uses unsupported type '{value_type}'")
                locals_out.setdefault(statement.name, value_type)
            elif isinstance(statement, IRFor):
                if statement.collection_expr is not None:
                    collection_type = self._type(statement.collection_expr.type)
                    if collection_type not in (ARRAY_I32, ARRAY_F64):
                        raise BundleCompileError(
                            "WASM collection iteration currently supports Array<int> and Array<float>"
                        )
                    locals_out.setdefault(statement.var_name, F64 if collection_type == ARRAY_F64 else I32)
                    index_local = self.for_index_locals.get(id(statement))
                    if index_local is None:
                        index_local = f"__nyx_for_index_{len(self.for_index_locals) + 1}"
                        self.for_index_locals[id(statement)] = index_local
                    locals_out.setdefault(index_local, I32)
                else:
                    locals_out.setdefault(statement.var_name, I32)
                self._collect_locals(statement.body, symbols, locals_out)
            elif isinstance(statement, IRIf):
                self._collect_locals(statement.then_branch, symbols, locals_out)
                for _, branch in statement.elif_branches:
                    self._collect_locals(branch, symbols, locals_out)
                self._collect_locals(statement.else_branch or [], symbols, locals_out)
            elif isinstance(statement, IRWhile):
                self._collect_locals(statement.body, symbols, locals_out)

    def _collect_expression_locals(self, value: object, locals_out: Dict[str, str]) -> None:
        if isinstance(value, IRMatchExpression):
            subject_type = self._type(value.subject.type)
            if subject_type not in (I32, F64):
                raise BundleCompileError(
                    f"Match expression subject type '{value.subject.type}' is not supported in WASM bundle functions"
                )
            temporary = self.match_locals.get(id(value))
            if temporary is None:
                temporary = f"__nyx_match_{len(self.match_locals) + 1}"
                self.match_locals[id(value)] = temporary
            locals_out.setdefault(temporary, subject_type)
        if is_dataclass(value):
            for descriptor in fields(value):
                self._collect_expression_locals(getattr(value, descriptor.name), locals_out)
        elif isinstance(value, (tuple, list)):
            for item in value:
                self._collect_expression_locals(item, locals_out)

    def _emit_statement(self, node: IRStatement, output: List[Instruction], context: "_LowerContext") -> None:
        if isinstance(node, IRReturn):
            if context.result_type == STRING:
                self._emit_string_return(node.expr, output, context)
            elif node.expr is not None:
                output.extend(self._emit_expr_as(node.expr, context.result_type, context.symbols))
            output.append(Instruction("return"))
            return

        if isinstance(node, IRVarDecl):
            local_type = context.symbols[node.name]
            output.extend(self._emit_expr_as(node.expr, local_type, context.symbols))
            output.append(Instruction("local.set", node.name))
            return

        if isinstance(node, IRAssign):
            if not isinstance(node.target, IRReference):
                raise BundleCompileError("Bundle assignment currently requires a local identifier target")
            target_type = context.symbols.get(node.target.name)
            if target_type not in (I32, F64):
                raise BundleCompileError(f"Unknown or unsupported bundle assignment target '{node.target.name}'")
            output.extend(self._emit_expr_as(node.expr, target_type, context.symbols))
            output.append(Instruction("global.set" if node.target.name in self.global_types else "local.set", node.target.name))
            return

        if isinstance(node, IRFor):
            if node.collection_expr is not None:
                if not isinstance(node.collection_expr, IRReference):
                    raise BundleCompileError("WASM collection iteration requires an array parameter reference")
                collection_name = node.collection_expr.name
                collection_type = context.symbols.get(collection_name)
                if collection_type not in (ARRAY_I32, ARRAY_F64):
                    raise BundleCompileError("WASM collection iteration requires Array<int> or Array<float>")
                index_local = self.for_index_locals[id(node)]
                break_label = self._label("for_break")
                loop_label = self._label("for_loop")
                continue_label = self._label("for_continue")
                stride = 8 if collection_type == ARRAY_F64 else 4
                load_op = "f64.load" if collection_type == ARRAY_F64 else "i32.load"
                output.extend((
                    Instruction("i32.const", 0), Instruction("local.set", index_local),
                    Instruction("block", break_label), Instruction("loop", loop_label),
                    Instruction("local.get", index_local), Instruction("local.get", f"{collection_name}_len"),
                    Instruction("i32.ge_s"), Instruction("br_if", break_label),
                    Instruction("local.get", f"{collection_name}_ptr"), Instruction("local.get", index_local),
                    Instruction("i32.const", stride), Instruction("i32.mul"), Instruction("i32.add"),
                    Instruction(load_op), Instruction("local.set", node.var_name),
                    Instruction("block", continue_label),
                ))
                nested = context.with_loop(break_label, continue_label)
                for statement in node.body:
                    self._emit_statement(statement, output, nested)
                output.extend((
                    Instruction("end"),
                    Instruction("local.get", index_local), Instruction("i32.const", 1),
                    Instruction("i32.add"), Instruction("local.set", index_local),
                    Instruction("br", loop_label), Instruction("end"), Instruction("end"),
                ))
                return
            break_label = self._label("for_break")
            loop_label = self._label("for_loop")
            continue_label = self._label("for_continue")
            output.extend(self._emit_expr_as(node.start_expr, I32, context.symbols))
            output.append(Instruction("local.set", node.var_name))
            output.extend((Instruction("block", break_label), Instruction("loop", loop_label)))
            output.append(Instruction("local.get", node.var_name))
            output.extend(self._emit_expr_as(node.end_expr, I32, context.symbols))
            output.extend((Instruction("i32.gt_s"), Instruction("br_if", break_label)))
            output.append(Instruction("block", continue_label))
            nested = context.with_loop(break_label, continue_label)
            for statement in node.body:
                self._emit_statement(statement, output, nested)
            output.extend((
                Instruction("end"),
                Instruction("local.get", node.var_name), Instruction("i32.const", 1),
                Instruction("i32.add"), Instruction("local.set", node.var_name),
                Instruction("br", loop_label), Instruction("end"), Instruction("end"),
            ))
            return

        if isinstance(node, IRWhile):
            break_label = self._label("while_break")
            loop_label = self._label("while_loop")
            output.extend((Instruction("block", break_label), Instruction("loop", loop_label)))
            output.extend(self._emit_expr_as(node.condition, I32, context.symbols))
            output.extend((Instruction("i32.eqz"), Instruction("br_if", break_label)))
            nested = context.with_loop(break_label, loop_label)
            for statement in node.body:
                self._emit_statement(statement, output, nested)
            output.extend((Instruction("br", loop_label), Instruction("end"), Instruction("end")))
            return

        if isinstance(node, IRIf):
            self._emit_if(node, output, context)
            return

        if isinstance(node, IRBreak):
            if not context.break_label:
                raise BundleCompileError("'break' used outside a WASM-lowered loop")
            output.append(Instruction("br", context.break_label))
            return

        if isinstance(node, IRContinue):
            if not context.continue_label:
                raise BundleCompileError("'continue' used outside a WASM-lowered loop")
            output.append(Instruction("br", context.continue_label))
            return

        if isinstance(node, IRExprStatement):
            output.extend(self._emit_expr(node.expr, context.symbols))
            if self._expr_type(node.expr, context.symbols) != VOID:
                output.append(Instruction("drop"))
            return

        raise BundleCompileError(f"Unsupported statement '{type(node).__name__}' in {context.function_name}()")

    def _emit_if(self, node: IRIf, output: List[Instruction], context: "_LowerContext") -> None:
        self._emit_if_parts(
            node.condition,
            node.then_branch,
            node.elif_branches,
            node.else_branch,
            output,
            context,
        )

    def _emit_if_parts(
        self,
        condition: IRExpr,
        then_branch: Tuple[IRStatement, ...],
        elif_branches: Tuple[Tuple[IRExpr, Tuple[IRStatement, ...]], ...],
        else_branch: Optional[Tuple[IRStatement, ...]],
        output: List[Instruction],
        context: "_LowerContext",
    ) -> None:
        output.extend(self._emit_expr_as(condition, I32, context.symbols))
        output.append(Instruction("if"))
        for statement in then_branch:
            self._emit_statement(statement, output, context)
        remaining = list(elif_branches)
        if remaining or else_branch:
            output.append(Instruction("else"))
            if remaining:
                condition, branch = remaining.pop(0)
                self._emit_if_parts(condition, branch, tuple(remaining), else_branch, output, context)
            else:
                for statement in else_branch or []:
                    self._emit_statement(statement, output, context)
        output.append(Instruction("end"))

    def _emit_expr_as(self, node: IRExpr, expected: str, symbols: Dict[str, str]) -> List[Instruction]:
        actual = self._expr_type(node, symbols)
        instructions = self._emit_expr(node, symbols)
        if actual == expected:
            return instructions
        if actual == I32 and expected == F64:
            return instructions + [Instruction("f64.convert_i32_s")]
        raise BundleCompileError(f"Cannot lower implicit WASM conversion from '{actual}' to '{expected}'")

    def _emit_expr(self, node: IRExpr, symbols: Dict[str, str]) -> List[Instruction]:
        if isinstance(node, IRLiteral):
            if node.type.name == "bool":
                return [Instruction("i32.const", 1 if node.value else 0)]
            if node.type.name == "float":
                return [Instruction("f64.const", node.value)]
            if node.type.name == "int":
                return [Instruction("i32.const", node.value)]
            raise BundleCompileError(f"Literal type '{node.type}' is not a numeric WASM value")
        if isinstance(node, IRReference):
            value_type = symbols.get(node.name)
            if value_type not in (I32, F64):
                raise BundleCompileError(f"Identifier '{node.name}' is not a numeric WASM value")
            return [Instruction("global.get" if node.name in self.global_types else "local.get", node.name)]
        if isinstance(node, IRMemberAccess):
            if not isinstance(node.obj, IRReference):
                raise BundleCompileError("WASM struct field access requires a struct parameter reference")
            struct_type = symbols.get(node.obj.name, "")
            if not struct_type.startswith(STRUCT_PREFIX):
                raise BundleCompileError(f"WASM member access requires a scalar struct parameter, found '{struct_type}'")
            struct_name = struct_type[len(STRUCT_PREFIX):]
            _, fields = self._struct_layout(struct_name)
            field = next((item for item in fields if item[0] == node.member), None)
            if field is None:
                raise BundleCompileError(f"Unknown field '{node.member}' on WASM struct '{struct_name}'")
            _, field_type, offset = field
            return [
                Instruction("local.get", f"{node.obj.name}_ptr"),
                Instruction("i32.const", offset),
                Instruction("i32.add"),
                Instruction("f64.load" if field_type == F64 else "i32.load"),
            ]
        if isinstance(node, IRUnary):
            value_type = self._expr_type(node.expr, symbols)
            if node.op in ("not", "!"):
                return self._emit_expr_as(node.expr, I32, symbols) + [Instruction("i32.eqz")]
            if node.op == "~":
                return self._emit_expr_as(node.expr, I32, symbols) + [Instruction("i32.const", -1), Instruction("i32.xor")]
            if node.op == "-":
                if value_type == F64:
                    return self._emit_expr(node.expr, symbols) + [Instruction("f64.neg")]
                return [Instruction("i32.const", 0)] + self._emit_expr_as(node.expr, I32, symbols) + [Instruction("i32.sub")]
        if isinstance(node, IRBinary):
            result_type = self._expr_type(node, symbols)
            operand_type = F64 if result_type == F64 else I32
            if node.op in ("==", "!=", "<", ">", "<=", ">="):
                left_type = self._expr_type(node.left, symbols)
                right_type = self._expr_type(node.right, symbols)
                operand_type = F64 if F64 in (left_type, right_type) else I32
            left = self._emit_expr_as(node.left, operand_type, symbols)
            right = self._emit_expr_as(node.right, operand_type, symbols)
            opcode = _binary_opcode(node.op, operand_type)
            return left + right + [Instruction(opcode)]
        if isinstance(node, IRConditional):
            result_type = self._expr_type(node, symbols)
            if result_type not in (I32, F64):
                raise BundleCompileError(
                    f"Conditional expression type '{node.type}' is not supported in WASM bundle functions"
                )
            output = self._emit_expr_as(node.condition, I32, symbols)
            output.append(Instruction("if_result", result_type))
            output.extend(self._emit_expr_as(node.then_expr, result_type, symbols))
            output.append(Instruction("else"))
            output.extend(self._emit_expr_as(node.else_expr, result_type, symbols))
            output.append(Instruction("end"))
            return output
        if isinstance(node, IRMatchExpression):
            result_type = self._expr_type(node, symbols)
            subject_type = self._expr_type(node.subject, symbols)
            if result_type not in (I32, F64) or subject_type not in (I32, F64):
                raise BundleCompileError(
                    f"Match expression types '{node.subject.type}' -> '{node.type}' are not supported in WASM bundle functions"
                )
            temporary = self.match_locals.get(id(node))
            if temporary is None:
                raise BundleCompileError("Internal WASM error: match expression local was not collected")
            output = self._emit_expr_as(node.subject, subject_type, symbols)
            output.append(Instruction("local.set", temporary))
            conditional_count = 0
            for case in node.cases:
                if case.pattern is None:
                    output.extend(self._emit_expr_as(case.value, result_type, symbols))
                    break
                output.extend((Instruction("local.get", temporary),))
                output.extend(self._emit_expr_as(case.pattern, subject_type, symbols))
                output.append(Instruction(_binary_opcode("==", subject_type)))
                output.append(Instruction("if_result", result_type))
                output.extend(self._emit_expr_as(case.value, result_type, symbols))
                output.append(Instruction("else"))
                conditional_count += 1
            output.extend(Instruction("end") for _ in range(conditional_count))
            return output
        if isinstance(node, IRCall):
            return self._emit_call(node, symbols)
        raise BundleCompileError(f"Unsupported expression '{type(node).__name__}' in WASM bundle")

    def _emit_call(self, node: IRCall, symbols: Dict[str, str]) -> List[Instruction]:
        if node.receiver is None and node.callee == "print" and self.wasi:
            return self._emit_wasi_print(node.args, symbols)
        if node.receiver is not None:
            receiver_type = self._expr_type(node.receiver, symbols)
            if node.callee in ("len", "length", "size") and not node.args:
                if not isinstance(node.receiver, IRReference):
                    raise BundleCompileError("WASM len() method requires a string or array reference")
                name = node.receiver.name
                if receiver_type in (STRING, ARRAY_I32, ARRAY_F64):
                    return [Instruction("local.get", f"{name}_len")]
            raise BundleCompileError(
                f"Method '{node.callee}' is unsupported for WASM type '{receiver_type}'"
            )
        target = next((function for function in self.user_functions if function.name == node.callee), None)
        if target is None:
            target = self.extern_functions.get(node.callee)
        if target is None:
            raise BundleCompileError(f"WASM bundle cannot call unresolved function '{node.callee}'")
        if len(node.args) != len(target.params):
            raise BundleCompileError(f"Function '{node.callee}' argument count mismatch during WASM lowering")
        output: List[Instruction] = []
        for argument, parameter in zip(node.args, target.params):
            parameter_type = self._type(parameter.type)
            if parameter_type == STRING:
                output.extend(self._emit_string_argument(argument, symbols))
            elif parameter_type in (ARRAY_I32, ARRAY_F64):
                output.extend(self._emit_array_argument(argument, parameter_type, symbols))
            elif parameter_type.startswith(STRUCT_PREFIX):
                output.extend(self._emit_struct_argument(argument, parameter_type, symbols))
            else:
                output.extend(self._emit_expr_as(argument, parameter_type, symbols))
        output.append(Instruction("call", node.callee))
        return output

    def _emit_wasi_print(
        self,
        arguments: Sequence[IRExpr],
        symbols: Dict[str, str],
    ) -> List[Instruction]:
        output: List[Instruction] = []
        separator = self._intern_data(b" ")
        newline = self._intern_data(b"\n")
        for index, argument in enumerate(arguments):
            if index:
                output.extend((
                    Instruction("i32.const", separator),
                    Instruction("i32.const", 1),
                    Instruction("call", "__nyx_wasi_write"),
                ))
            output.extend(self._emit_string_argument(argument, symbols))
            output.append(Instruction("call", "__nyx_wasi_write"))
        output.extend((
            Instruction("i32.const", newline),
            Instruction("i32.const", 1),
            Instruction("call", "__nyx_wasi_write"),
        ))
        return output

    def _emit_string_argument(self, node: IRExpr, symbols: Dict[str, str]) -> List[Instruction]:
        """Lower a borrowed string argument to the internal ``ptr, len`` ABI."""
        if isinstance(node, IRLiteral) and node.type.name == "string":
            data = node.value.encode("utf-8")
            if not data:
                return [Instruction("i32.const", 0), Instruction("i32.const", 0)]
            return [
                Instruction("i32.const", self._intern_data(data)),
                Instruction("i32.const", len(data)),
            ]
        if isinstance(node, IRReference) and symbols.get(node.name) == STRING:
            return [
                Instruction("local.get", f"{node.name}_ptr"),
                Instruction("local.get", f"{node.name}_len"),
            ]
        raise BundleCompileError(
            "WASM string arguments currently require a UTF-8 literal or string parameter"
        )

    def _emit_array_argument(
        self,
        node: IRExpr,
        expected: str,
        symbols: Dict[str, str],
    ) -> List[Instruction]:
        if isinstance(node, IRReference) and symbols.get(node.name) == expected:
            return [
                Instruction("local.get", f"{node.name}_ptr"),
                Instruction("local.get", f"{node.name}_len"),
            ]
        raise BundleCompileError("WASM array arguments currently require an array parameter reference")

    def _emit_struct_argument(
        self,
        node: IRExpr,
        expected: str,
        symbols: Dict[str, str],
    ) -> List[Instruction]:
        if isinstance(node, IRReference) and symbols.get(node.name) == expected:
            return [Instruction("local.get", f"{node.name}_ptr")]
        raise BundleCompileError("WASM struct arguments currently require a struct parameter reference")

    def _expr_type(self, node: IRExpr, symbols: Dict[str, str]) -> str:
        if isinstance(node, IRCall) and node.receiver is None and node.callee == "print":
            return VOID
        if (
            isinstance(node, IRCall)
            and node.receiver is not None
            and node.callee in ("len", "length", "size")
            and not node.args
        ):
            return I32
        return self._type(node.type)

    def _type(self, type_node: object) -> str:
        value_type = _nyx_type(type_node)
        seen = set()
        while value_type in self.type_aliases and value_type not in seen:
            seen.add(value_type)
            value_type = _nyx_type(self.type_aliases[value_type])
        if value_type in self.structs:
            return STRUCT_PREFIX + value_type
        return value_type

    def _struct_layout(self, name: str) -> Tuple[int, Tuple[Tuple[str, str, int], ...]]:
        definition = self.structs.get(name)
        if definition is None:
            raise BundleCompileError(f"Unknown WASM struct type '{name}'")
        offset = 0
        max_alignment = 1
        layout: List[Tuple[str, str, int]] = []
        for field in definition.fields:
            field_type = self._type(field.type)
            if field_type not in (I32, F64):
                raise BundleCompileError(
                    f"WASM struct ABI supports only int/float/bool fields; "
                    f"'{name}.{field.name}' is '{field.type}'"
                )
            alignment = 8 if field_type == F64 else 4
            size = alignment
            offset = (offset + alignment - 1) & -alignment
            layout.append((field.name, field_type, offset))
            offset += size
            max_alignment = max(max_alignment, alignment)
        total = (offset + max_alignment - 1) & -max_alignment
        return total, tuple(layout)

    def _emit_string_return(
        self,
        expression: Optional[IRExpr],
        output: List[Instruction],
        context: "_LowerContext",
    ) -> None:
        if expression is None:
            raise BundleCompileError("String-returning function must return a value")
        if isinstance(expression, IRConditional):
            output.extend(self._emit_expr_as(expression.condition, I32, context.symbols))
            output.append(Instruction("if_result", I64))
            self._emit_string_return(expression.then_expr, output, context)
            output.append(Instruction("else"))
            self._emit_string_return(expression.else_expr, output, context)
            output.append(Instruction("end"))
            return
        if isinstance(expression, IRCall) and self._expr_type(expression, context.symbols) == STRING:
            output.extend(self._emit_call(expression, context.symbols))
            return
        segments = self._flatten_string(expression, context.symbols)
        constant_length = sum(length for kind, _, length in segments if kind == "literal")
        output.append(Instruction("i32.const", constant_length))
        for kind, value, _ in segments:
            if kind == "param":
                output.extend((Instruction("local.get", f"{value}_len"), Instruction("i32.add")))
        output.extend((
            Instruction("local.tee", "__nyx_out_len"),
            Instruction("call", "__nyx_alloc"),
            Instruction("local.tee", "__nyx_out_ptr"),
            Instruction("local.set", "__nyx_cursor"),
        ))

        for kind, value, length in segments:
            output.append(Instruction("local.get", "__nyx_cursor"))
            if kind == "literal":
                output.extend((Instruction("i32.const", value), Instruction("i32.const", length)))
                segment_length: List[Instruction] = [Instruction("i32.const", length)]
            else:
                output.extend((Instruction("local.get", f"{value}_ptr"), Instruction("local.get", f"{value}_len")))
                segment_length = [Instruction("local.get", f"{value}_len")]
            output.append(Instruction("memory.copy"))
            output.append(Instruction("local.get", "__nyx_cursor"))
            output.extend(segment_length)
            output.extend((Instruction("i32.add"), Instruction("local.set", "__nyx_cursor")))

        output.extend((
            Instruction("local.get", "__nyx_out_len"), Instruction("i64.extend_i32_u"),
            Instruction("i64.const", 32), Instruction("i64.shl"),
            Instruction("local.get", "__nyx_out_ptr"), Instruction("i64.extend_i32_u"),
            Instruction("i64.or"),
        ))

    def _flatten_string(self, node: IRExpr, symbols: Dict[str, str]) -> List[Tuple[str, object, int]]:
        if isinstance(node, IRBinary) and node.op == "+":
            return self._flatten_string(node.left, symbols) + self._flatten_string(node.right, symbols)
        if isinstance(node, IRLiteral) and node.type.name == "string":
            data = node.value.encode("utf-8")
            if not data:
                return []
            return [("literal", self._intern_data(data), len(data))]
        if isinstance(node, IRReference) and symbols.get(node.name) == STRING:
            return [("param", node.name, 0)]
        if isinstance(node, IRCall) and node.callee == "to_string" and len(node.args) == 1:
            argument = node.args[0]
            if isinstance(argument, IRReference) and symbols.get(argument.name) == STRING:
                return [("param", argument.name, 0)]
        raise BundleCompileError("Bundle string returns currently support UTF-8 literals and string parameters")

    def _intern_data(self, data: bytes) -> int:
        if data in self.data_by_value:
            return self.data_by_value[data]
        offset = self.next_data_offset
        self.data_by_value[data] = offset
        self.data.append(DataSegment(offset, data))
        self.next_data_offset += len(data)
        return offset

    def _label(self, prefix: str) -> str:
        self.label_counter += 1
        return f"{prefix}_{self.label_counter}"


@dataclass(frozen=True)
class _LowerContext:
    function_name: str
    symbols: Dict[str, str]
    result_type: str
    lowerer: BundleLowerer
    break_label: Optional[str] = None
    continue_label: Optional[str] = None

    def with_loop(self, break_label: str, continue_label: str) -> "_LowerContext":
        return _LowerContext(
            self.function_name,
            self.symbols,
            self.result_type,
            self.lowerer,
            break_label,
            continue_label,
        )


def _runtime_functions() -> List[FunctionIR]:
    abi = FunctionIR(
        "__nyx_abi_version", [], I32,
        body=[Instruction("i32.const", 1), Instruction("return")],
    )
    alloc = FunctionIR(
        "__nyx_alloc", [("size", I32)], I32,
        locals=[("old_ptr", I32), ("new_ptr", I32), ("current_bytes", I32), ("pages", I32)],
        body=[
            Instruction("local.get", "size"), Instruction("i32.const", 0), Instruction("i32.le_s"),
            Instruction("if"), Instruction("i32.const", 0), Instruction("return"), Instruction("end"),
            Instruction("global.get", "heap_ptr"), Instruction("local.tee", "old_ptr"),
            Instruction("local.get", "size"), Instruction("i32.add"), Instruction("i32.const", 7),
            Instruction("i32.add"), Instruction("i32.const", -8), Instruction("i32.and"),
            Instruction("local.tee", "new_ptr"), Instruction("local.get", "old_ptr"), Instruction("i32.lt_s"),
            Instruction("if"), Instruction("i32.const", 0), Instruction("return"), Instruction("end"),
            Instruction("memory.size"), Instruction("i32.const", 16), Instruction("i32.shl"),
            Instruction("local.tee", "current_bytes"), Instruction("local.get", "new_ptr"), Instruction("i32.lt_s"),
            Instruction("if"),
            Instruction("local.get", "new_ptr"), Instruction("local.get", "current_bytes"), Instruction("i32.sub"),
            Instruction("i32.const", 65535), Instruction("i32.add"), Instruction("i32.const", 16), Instruction("i32.shr_s"),
            Instruction("local.tee", "pages"), Instruction("memory.grow"), Instruction("i32.const", -1), Instruction("i32.eq"),
            Instruction("if"), Instruction("i32.const", 0), Instruction("return"), Instruction("end"),
            Instruction("end"),
            Instruction("local.get", "new_ptr"), Instruction("global.set", "heap_ptr"),
            Instruction("local.get", "old_ptr"), Instruction("return"),
        ],
    )
    free = FunctionIR(
        "__nyx_free", [("ptr", I32), ("size", I32)], VOID,
        locals=[("end_ptr", I32)],
        body=[
            Instruction("local.get", "ptr"), Instruction("i32.eqz"), Instruction("if"), Instruction("return"), Instruction("end"),
            Instruction("local.get", "ptr"), Instruction("local.get", "size"), Instruction("i32.add"),
            Instruction("i32.const", 7), Instruction("i32.add"), Instruction("i32.const", -8), Instruction("i32.and"),
            Instruction("local.tee", "end_ptr"), Instruction("global.get", "heap_ptr"), Instruction("i32.eq"),
            Instruction("if"), Instruction("local.get", "ptr"), Instruction("global.set", "heap_ptr"), Instruction("end"),
        ],
    )
    return [abi, alloc, free]


def _wasi_runtime_functions() -> List[FunctionIR]:
    """Return the WASI preview1 stdout bridge used by the executable profile."""
    return [
        FunctionIR(
            "__nyx_wasi_write",
            [("ptr", I32), ("len", I32)],
            VOID,
            export=False,
            body=[
                # Linear-memory bytes 0..11 are reserved for one transient
                # iovec and nwritten. Static Nyx data starts at DATA_START.
                Instruction("i32.const", 0),
                Instruction("local.get", "ptr"),
                Instruction("i32.store"),
                Instruction("i32.const", 4),
                Instruction("local.get", "len"),
                Instruction("i32.store"),
                Instruction("i32.const", 1),
                Instruction("i32.const", 0),
                Instruction("i32.const", 1),
                Instruction("i32.const", 8),
                Instruction("call", "fd_write"),
                Instruction("drop"),
            ],
        )
    ]


def _nyx_type(type_node: object) -> str:
    if type_node is None:
        return VOID
    name = getattr(type_node, "name", str(type_node))
    if name in ("int", "bool"):
        return I32
    if name == "float":
        return F64
    if name == "string":
        return STRING
    if name == "Array":
        arguments = getattr(type_node, "arguments", ())
        element = _nyx_type(arguments[0]) if arguments else "any"
        if element in (I32,):
            return ARRAY_I32
        if element == F64:
            return ARRAY_F64
        return f"array_{element}"
    if name == "void":
        return VOID
    return str(name)


def _binary_opcode(op: str, operand_type: str) -> str:
    if operand_type == F64:
        opcodes = {
            "+": "f64.add", "-": "f64.sub", "*": "f64.mul", "/": "f64.div",
            "==": "f64.eq", "!=": "f64.ne", "<": "f64.lt", ">": "f64.gt",
            "<=": "f64.le", ">=": "f64.ge",
        }
    else:
        opcodes = {
            "+": "i32.add", "-": "i32.sub", "*": "i32.mul", "/": "i32.div_s", "%": "i32.rem_s",
            "&": "i32.and", "|": "i32.or", "^": "i32.xor", "<<": "i32.shl", ">>": "i32.shr_s",
            "and": "i32.and", "&&": "i32.and", "or": "i32.or", "||": "i32.or",
            "==": "i32.eq", "!=": "i32.ne", "<": "i32.lt_s", ">": "i32.gt_s",
            "<=": "i32.le_s", ">=": "i32.ge_s",
        }
    if op not in opcodes:
        raise BundleCompileError(f"Operator '{op}' is unsupported for WASM type '{operand_type}'")
    return opcodes[op]


def _definitely_returns(statements: Iterable[IRStatement]) -> bool:
    """Return whether every reachable path through a statement list returns.

    A value-producing WASM function cannot legally fall through to its implicit
    function end.  Merely finding a nested ``return`` is insufficient: an
    ``if`` without an ``else`` can still take the fall-through path.  This
    deliberately conservative analysis accepts straight-line returns and
    exhaustive if/elif/else chains; loops are not considered terminating
    because ``break`` and zero-iteration paths need control-flow analysis.
    """
    for statement in statements:
        if isinstance(statement, IRReturn):
            return True
        if isinstance(statement, IRIf):
            if _if_definitely_returns(statement):
                return True
    return False


def _if_definitely_returns(statement: IRIf) -> bool:
    """Return whether every branch of an ``if`` chain returns a value."""
    if statement.else_branch is None:
        return False
    if not _definitely_returns(statement.then_branch):
        return False
    if any(not _definitely_returns(branch) for _, branch in statement.elif_branches):
        return False
    return _definitely_returns(statement.else_branch)


def _align8(value: int) -> int:
    return (value + 7) & -8


def _u32(value: int) -> bytes:
    if value < 0:
        raise ValueError("u32 LEB128 cannot encode a negative value")
    output = bytearray()
    while True:
        byte = value & 0x7F
        value >>= 7
        if value:
            byte |= 0x80
        output.append(byte)
        if not value:
            return bytes(output)


def _signed_leb(value: int, bits: int) -> bytes:
    output = bytearray()
    more = True
    while more:
        byte = value & 0x7F
        value >>= 7
        sign_set = byte & 0x40
        more = not ((value == 0 and not sign_set) or (value == -1 and sign_set))
        if more:
            byte |= 0x80
        output.append(byte)
    return bytes(output)


def _s32(value: int) -> bytes:
    return _signed_leb(value, 32)


def _s64(value: int) -> bytes:
    return _signed_leb(value, 64)


def _string(value: str) -> bytes:
    encoded = value.encode("utf-8")
    return _u32(len(encoded)) + encoded


def _append_section(wasm: bytearray, section_id: int, payload: bytes) -> None:
    wasm.append(section_id)
    wasm.extend(_u32(len(payload)))
    wasm.extend(payload)


def _wat_bytes(data: bytes) -> str:
    result = []
    for byte in data:
        if 0x20 <= byte <= 0x7E and byte not in (0x22, 0x5C):
            result.append(chr(byte))
        else:
            result.append(f"\\{byte:02x}")
    return "".join(result)
