"""Bootstrap the Nyx frontend from the compiler sources written in Nyx.

The stage-1 compiler is intentionally hosted by the current Python driver while
its frontend is bootstrapped through the native C++ backend.  The important
invariant is that the source being verified is lexed, parsed, type-checked, and
code-generated by the Nyx implementations under ``compiler/`` rather than by
the Python reference frontend.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path
from typing import Tuple

from src.codegen.codegen import UniversalCodeGen
from src.codegen.cpp_toolchain import CppToolchain
from src.core.lexer import Lexer
from src.core.parser import Parser
from src.version import VERSION


ROOT_DIR = Path(__file__).resolve().parents[2]
COMPILER_DIR = ROOT_DIR / "compiler"


class SelfHostError(RuntimeError):
    """Raised when the Nyx-authored stage-1 compiler cannot be bootstrapped."""


def _without_directives(source: str, *, drop_main: bool = False) -> str:
    lines = source.splitlines()
    filtered = [
        line for line in lines
        if not line.lstrip().startswith("#target")
        and not line.lstrip().startswith("#native")
    ]
    text = "\n".join(filtered)
    if drop_main:
        marker = "fn main()"
        if marker in text:
            text = text[:text.index(marker)]
    return text.strip()


def _read_component(name: str, *, drop_main: bool = False) -> str:
    path = COMPILER_DIR / name
    if not path.exists():
        raise SelfHostError(f"Missing self-host compiler component: {path}")
    return _without_directives(path.read_text(encoding="utf-8"), drop_main=drop_main)


def _read_lexer_impl() -> str:
    """Read lexer support after Token; parser.nyx owns the composed Token type."""
    path = COMPILER_DIR / "lexer.nyx"
    if not path.exists():
        raise SelfHostError(f"Missing self-host compiler component: {path}")
    source = _without_directives(path.read_text(encoding="utf-8"), drop_main=True)
    marker = "// NYX_LEXER_SUPPORT_BEGIN:"
    if marker not in source:
        raise SelfHostError(f"Lexer support boundary missing from {path}")
    return source[source.index(marker):].strip()


def _combined_source() -> str:
    """Return the canonical stage-1 frontend as one compilable Nyx unit."""
    components = [
        _read_component("parser.nyx"),
        # parser.nyx owns the canonical Token and ASTNode definitions.  The
        # lexer file contributes only its Lexer implementation to avoid a
        # duplicate Token declaration when components are composed.
        _read_lexer_impl(),
        _read_component("type_checker.nyx"),
        _read_component("hir.nyx"),
        _read_component("hir_lowering.nyx"),
        _read_component("hir_codegen.nyx"),
    ]
    return """#target cpp
#native include <string>
#native include <vector>
#native include <cctype>
#native include <cstdint>
#native include <iostream>

""" + "\n\n".join(components)


def _nyx_string_literal(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r", "\\r")
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def _driver_source(source: str) -> str:
    return _combined_source() + "\n\n" + f"""fn main() {{
    var source = {_nyx_string_literal(source)}
    var lex = Lexer(source, 0, 1, 1)
    var tokens = lex.tokenize()
    var parser = Parser(tokens, 0, false, "", "")
    var ast = parser.parse_program()
    if parser.has_error {{
        print("SELF_HOST_PARSE_ERROR:", parser.error_msg)
        return
    }}

    var checker = TypeChecker([], [], [], "", false, false, "")
    if not checker.check_program(ast) {{
        print("SELF_HOST_TYPE_ERROR:", checker.error_msg)
        return
    }}

    var lowerer = HIRLowerer("<bootstrap-input>", "cpp", [], [], [], [], 0, "module", false, "")
    var hir_module = lowerer.lower_program(ast)
    if lowerer.has_error {{
        print("SELF_HOST_HIR_ERROR:", lowerer.error_msg)
        return
    }}

    var generator = HIRCodeGen(0, "", false, "", 0,
        HIRType("", [], false, false, [], []), false, "")
    var generated = generator.generate(hir_module)
    if generator.has_error {{
        print("SELF_HOST_CODEGEN_ERROR:", generator.error_msg)
        return
    }}
    print("SELF_HOST_OK")
    print(generated)
}}

main()
"""


def _native_driver_source() -> str:
    """Return the Nyx-authored command-line compiler used for native stages."""
    return (_combined_source() + """

fn nyxc_usage() {
    print("Usage:")
    print("  nyxc --version")
    print("  nyxc check <input.nyx>")
    print("  nyxc emit-cpp <input.nyx> -o <output.cpp>")
    print("  nyxc compile <input.nyx> -o <output-binary>")
}

fn nyxc_fail(kind: string, message: string, code: int) {
    print("NYX_" + kind + "_ERROR:", message)
    _nyx_process_exit(code)
}

fn nyxc_frontend(source_path: string, output_path: string, check_only: bool, report_emit: bool) {
    if not _nyx_bootstrap_file_exists(source_path) {
        nyxc_fail("IO", "Source file not found: " + source_path, 1)
        return
    }

    var source = _nyx_bootstrap_read_file(source_path)
    var lex = Lexer(source, 0, 1, 1)
    var tokens = lex.tokenize()
    var parser = Parser(tokens, 0, false, "", "")
    var ast = parser.parse_program()
    if parser.has_error {
        nyxc_fail("PARSE", parser.error_msg, 1)
        return
    }

    var checker = TypeChecker([], [], [], "", false, false, "")
    if not checker.check_program(ast) {
        nyxc_fail("TYPE", checker.error_msg, 1)
        return
    }

    var lowerer = HIRLowerer(source_path, "cpp", [], [], [], [], 0, "module", false, "")
    var hir_module = lowerer.lower_program(ast)
    if lowerer.has_error {
        nyxc_fail("HIR", lowerer.error_msg, 1)
        return
    }

    if check_only {
        print("NYX_CHECK_OK", source_path)
        return
    }

    if hir_module.target != "cpp" and hir_module.target != "cpp" and hir_module.target != "c++" {
        nyxc_fail("TARGET", "Native nyxc currently emits cpp only; requested " + hir_module.target, 2)
        return
    }
    var generator = HIRCodeGen(0, "", false, "", 0,
        HIRType("", [], false, false, [], []), false, "")
    var generated = generator.generate(hir_module)
    if generator.has_error {
        nyxc_fail("CODEGEN", generator.error_msg, 1)
        return
    }
    if not _nyx_bootstrap_write_file(output_path, generated) {
        nyxc_fail("WRITE", "Could not write C++ output: " + output_path, 1)
        return
    }
    print("NYX_COMPILE_OK")
    if report_emit { print("NYX_EMIT_CPP_OK", output_path) }
}

fn nyxc_build(source_path: string, output_path: string) {
    var cpp_path = output_path + ".nyx.cpp"
    nyxc_frontend(source_path, cpp_path, false, false)
    var result = _nyx_toolchain_compile_cpp(cpp_path, output_path)
    if result != 0 {
        nyxc_fail("TOOLCHAIN", _nyx_toolchain_last_error() + "; generated C++ retained at " + cpp_path, 1)
        return
    }
    _nyx_bootstrap_remove_file(cpp_path)
    print("NYX_BUILD_OK", output_path)
}

fn main() {
    var cli_args: Array<string> = args()
    if len(cli_args) < 2 {
        nyxc_usage()
        _nyx_process_exit(2)
        return
    }

    var command = cli_args[1]
    if command == "--version" or command == "version" {
        print("nyxc __NYX_VERSION__ (native self-host)")
        return
    }
    if command == "--help" or command == "-h" or command == "help" {
        nyxc_usage()
        return
    }
    if command == "check" {
        if len(cli_args) != 3 {
            nyxc_usage()
            _nyx_process_exit(2)
            return
        }
        nyxc_frontend(cli_args[2], "", true, false)
        return
    }
    if command == "emit-cpp" or command == "compile" {
        if len(cli_args) < 4 {
            nyxc_usage()
            _nyx_process_exit(2)
            return
        }
        var output_path = cli_args[3]
        if output_path == "-o" or output_path == "--output" {
            if len(cli_args) < 5 {
                nyxc_usage()
                _nyx_process_exit(2)
                return
            }
            output_path = cli_args[4]
        }
        if command == "compile" { nyxc_build(cli_args[2], output_path) }
        else { nyxc_frontend(cli_args[2], output_path, false, true) }
        return
    }

    // Stage-2 compatibility: nyxc <input.nyx> <output.cpp>
    if len(cli_args) == 3 {
        nyxc_frontend(cli_args[1], cli_args[2], false, true)
        return
    }
    nyxc_usage()
    _nyx_process_exit(2)
}

main()
""").replace("__NYX_VERSION__", VERSION)


def _compile_driver(source: str) -> Tuple[int, str]:
    """Compile and execute a temporary native bootstrap driver."""
    driver_source = _driver_source(source)
    tokens = Lexer(driver_source, "<self-host-driver>").tokenize()
    ast = Parser(tokens, driver_source, "<self-host-driver>").parse()
    cpp_code = UniversalCodeGen(ast).gen_cpp()

    with tempfile.TemporaryDirectory(prefix="nyx_self_host_") as temp_dir:
        cpp_path = os.path.join(temp_dir, "bootstrap_driver.cpp")
        exe_path = os.path.join(temp_dir, "bootstrap_driver.exe")
        with open(cpp_path, "w", encoding="utf-8") as handle:
            handle.write(cpp_code)

        ok, message = CppToolchain.compile_cpp(cpp_path, exe_path)
        if not ok:
            raise SelfHostError(f"Stage-1 bootstrap C++ compilation failed:\n{message}")
        return_code, output = CppToolchain.run_executable(exe_path)
        return return_code, output


def _extract_generated(output: str) -> str:
    marker = "SELF_HOST_OK"
    marker_index = output.find(marker)
    if marker_index < 0:
        if any(
            marker in output
            for marker in (
                "SELF_HOST_PARSE_ERROR:",
                "SELF_HOST_TYPE_ERROR:",
                "SELF_HOST_HIR_ERROR:",
                "SELF_HOST_CODEGEN_ERROR:",
            )
        ):
            raise SelfHostError(output.strip())
        raise SelfHostError("Self-host compiler produced no success marker")
    diagnostic_prefix = output[:marker_index]
    if any(
        marker in diagnostic_prefix
        for marker in (
            "SELF_HOST_PARSE_ERROR:",
            "SELF_HOST_TYPE_ERROR:",
            "SELF_HOST_HIR_ERROR:",
            "SELF_HOST_CODEGEN_ERROR:",
        )
    ):
        raise SelfHostError(diagnostic_prefix.strip())
    generated = output[marker_index + len(marker):].lstrip("\r\n").rstrip("\r\n") + "\n"
    if not generated.strip():
        raise SelfHostError("Self-host code generator produced empty C++ output")
    return generated


def compile_source(source_path: str, output_path: str) -> bool:
    """Use the Nyx-authored stage-1 pipeline to emit C++ for one source file."""
    source_file = Path(source_path)
    if not source_file.exists():
        raise SelfHostError(f"Source file not found: {source_file}")

    return_code, output = _compile_driver(source_file.read_text(encoding="utf-8"))
    if return_code != 0:
        raise SelfHostError(f"Stage-1 bootstrap driver exited with code {return_code}")
    generated = _extract_generated(output)

    target = Path(output_path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(generated, encoding="utf-8")
    return True


def build_native_compiler(output_path: str) -> bool:
    """Build the standalone stage-2 ``nyxc`` frontend executable."""
    return_code, output = _compile_driver(_native_driver_source())
    if return_code != 0:
        raise SelfHostError(f"Stage-1 self-compilation exited with code {return_code}")
    stage2_cpp = _extract_generated(output)

    target = Path(output_path)
    target.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="nyx_native_compiler_") as temp_dir:
        cpp_path = os.path.join(temp_dir, "nyxc_stage2.cpp")
        with open(cpp_path, "w", encoding="utf-8") as handle:
            handle.write(stage2_cpp)
        ok, message = CppToolchain.compile_cpp(cpp_path, str(target))
        if not ok:
            raise SelfHostError(f"Native stage-2 compiler build failed:\n{message}")
    return True


def verify_stage2() -> bool:
    """Prove stage-1 -> stage-2 self compilation and deterministic output."""
    sample = (
        "fn add(a: int, b: int) -> int { return a + b; }\n"
        'fn main() { print(add(20, 22)); print("e\\u0301"); print("a\\0b"); }\n'
    )

    stage1_return_code, stage1_output = _compile_driver(sample)
    if stage1_return_code != 0:
        raise SelfHostError(f"Stage-1 compiler exited with code {stage1_return_code}")
    stage1_sample_cpp = _extract_generated(stage1_output)

    native_compiler_source = _native_driver_source()
    compiler_return_code, compiler_output = _compile_driver(native_compiler_source)
    if compiler_return_code != 0:
        raise SelfHostError(
            f"Stage-1 self-compilation exited with code {compiler_return_code}"
        )
    stage2_cpp = _extract_generated(compiler_output)

    with tempfile.TemporaryDirectory(prefix="nyx_stage2_verify_") as temp_dir:
        stage2_cpp_path = os.path.join(temp_dir, "nyx_stage2.cpp")
        stage2_exe_path = os.path.join(temp_dir, "nyx_stage2.exe")
        with open(stage2_cpp_path, "w", encoding="utf-8") as handle:
            handle.write(stage2_cpp)

        ok, message = CppToolchain.compile_cpp(stage2_cpp_path, stage2_exe_path)
        if not ok:
            raise SelfHostError(f"Stage-2 native compilation failed:\n{message}")

        sample_source_path = os.path.join(temp_dir, "sample.nyx")
        sample_cpp_path = os.path.join(temp_dir, "sample.cpp")
        with open(sample_source_path, "w", encoding="utf-8") as handle:
            handle.write(sample)

        version_return_code, version_output = CppToolchain.run_executable(
            stage2_exe_path, ("--version",), timeout=30
        )
        if version_return_code != 0 or f"nyxc {VERSION}" not in version_output:
            raise SelfHostError(f"Stage-2 version contract failed:\n{version_output}")

        check_return_code, check_output = CppToolchain.run_executable(
            stage2_exe_path, ("check", sample_source_path), timeout=30
        )
        if check_return_code != 0 or "NYX_CHECK_OK" not in check_output:
            raise SelfHostError(f"Stage-2 check command failed:\n{check_output}")

        invalid_source_path = os.path.join(temp_dir, "invalid.nyx")
        with open(invalid_source_path, "w", encoding="utf-8") as handle:
            handle.write("fn broken(a: int) -> string { return a; }\n")
        invalid_return_code, invalid_output = CppToolchain.run_executable(
            stage2_exe_path, ("check", invalid_source_path), timeout=30
        )
        if invalid_return_code == 0 or "NYX_TYPE_ERROR:" not in invalid_output:
            raise SelfHostError(
                "Stage-2 check accepted an invalid program: "
                f"exit={invalid_return_code}, output={invalid_output!r}"
            )

        stage2_return_code, stage2_output = CppToolchain.run_executable(
            stage2_exe_path,
            ("emit-cpp", sample_source_path, "-o", sample_cpp_path),
            timeout=30,
        )
        if stage2_return_code != 0:
            raise SelfHostError(f"Stage-2 compiler exited with code {stage2_return_code}")
        if "NYX_COMPILE_OK" not in stage2_output or not os.path.exists(sample_cpp_path):
            raise SelfHostError(f"Stage-2 command-line compilation failed:\n{stage2_output}")
        with open(sample_cpp_path, "r", encoding="utf-8") as handle:
            stage2_sample_cpp = handle.read()

        if stage1_sample_cpp != stage2_sample_cpp:
            raise SelfHostError(
                "Stage-1 and stage-2 generated different C++ for the bootstrap fixture"
            )

        sample_exe_path = os.path.join(temp_dir, "sample.exe")
        build_return_code, build_output = CppToolchain.run_executable(
            stage2_exe_path,
            ("compile", sample_source_path, "-o", sample_exe_path),
            timeout=60,
        )
        if build_return_code != 0 or "NYX_BUILD_OK" not in build_output:
            raise SelfHostError(f"Stage-2 native build command failed:\n{build_output}")
        sample_return_code, sample_output = CppToolchain.run_executable(sample_exe_path)
        expected_output = "42\ne\u0301\na\0b"
        if sample_return_code != 0 or sample_output.strip() != expected_output:
            raise SelfHostError(
                "Stage-2 output runtime mismatch: "
                f"exit={sample_return_code}, output={sample_output!r}"
            )

        compiler_source_path = os.path.join(temp_dir, "compiler.nyx")
        stage3_cpp_path = os.path.join(temp_dir, "nyxc_stage3.cpp")
        stage3_exe_path = os.path.join(temp_dir, "nyxc_stage3.exe")
        with open(compiler_source_path, "w", encoding="utf-8") as handle:
            handle.write(native_compiler_source)
        stage3_return_code, stage3_output = CppToolchain.run_executable(
            stage2_exe_path,
            ("emit-cpp", compiler_source_path, "-o", stage3_cpp_path),
            timeout=30,
        )
        if stage3_return_code != 0 or "NYX_COMPILE_OK" not in stage3_output:
            raise SelfHostError(f"Stage-2 could not reproduce its compiler:\n{stage3_output}")
        with open(stage3_cpp_path, "r", encoding="utf-8") as handle:
            stage3_cpp = handle.read()
        if stage2_cpp != stage3_cpp:
            raise SelfHostError("Stage-2 and stage-3 compiler sources are not byte-identical")
        ok, message = CppToolchain.compile_cpp(stage3_cpp_path, stage3_exe_path)
        if not ok:
            raise SelfHostError(f"Stage-3 native compilation failed:\n{message}")

    return True


def verify() -> bool:
    """Run stage-1 conformance and the native stage-2 bootstrap proof."""
    valid = "fn add(a: int, b: int) -> int { return a + b; }\n"
    invalid = "fn broken(a: int) -> string { return a; }\n"

    _, valid_output = _compile_driver(valid)
    if "SELF_HOST_OK" not in valid_output:
        raise SelfHostError("Valid stage-1 program was not accepted")

    _, invalid_output = _compile_driver(invalid)
    if "SELF_HOST_PARSE_ERROR:" not in invalid_output and "SELF_HOST_TYPE_ERROR:" not in invalid_output:
        raise SelfHostError("Invalid stage-1 program was accepted")
    verify_stage2()
    return True
